# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # Class for exceptions when there is a network error, status code error, etc.
  class APIException < CoreLibrary::ApiException
  end
end
