# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Merchant provided details of the native app or mobile web browser to
  # facilitate buyer's app switch to the PayPal consumer app.
  class AppSwitchContext < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Merchant provided, buyer's native app preferences to app switch to the
    # PayPal consumer app.
    # @return [NativeAppContext]
    attr_accessor :native_app

    # Buyer's mobile web browser context to app switch to the PayPal consumer
    # app.
    # @return [MobileWebContext]
    attr_accessor :mobile_web

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['native_app'] = 'native_app'
      @_hash['mobile_web'] = 'mobile_web'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        native_app
        mobile_web
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(native_app: SKIP, mobile_web: SKIP)
      @native_app = native_app unless native_app == SKIP
      @mobile_web = mobile_web unless mobile_web == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      native_app = NativeAppContext.from_hash(hash['native_app']) if hash['native_app']
      mobile_web = MobileWebContext.from_hash(hash['mobile_web']) if hash['mobile_web']

      # Create object from extracted values.
      AppSwitchContext.new(native_app: native_app,
                           mobile_web: mobile_web)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} native_app: #{@native_app}, mobile_web: #{@mobile_web}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} native_app: #{@native_app.inspect}, mobile_web: #{@mobile_web.inspect}>"
    end
  end
end
