# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Configures the label name to `Continue` or `Subscribe Now` for subscription
  # consent experience.
  class ApplicationContextUserAction
    APPLICATION_CONTEXT_USER_ACTION = [
      # After you redirect the customer to the PayPal subscription consent page,
      # a Continue button appears. Use this option when you want to control the
      # activation of the subscription and do not want PayPal to activate the
      # subscription.
      CONTINUE = 'CONTINUE'.freeze,

      # After you redirect the customer to the PayPal subscription consent page,
      # a Subscribe Now button appears. Use this option when you want PayPal to
      # activate the subscription.
      SUBSCRIBE_NOW = 'SUBSCRIBE_NOW'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
