# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The auction information.
  class AuctionInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the auction site.
    # @return [String]
    attr_accessor :auction_site

    # The auction site URL.
    # @return [String]
    attr_accessor :auction_item_site

    # The ID of the buyer who makes the purchase in the auction. This ID might
    # be different from the payer ID provided for the payment.
    # @return [String]
    attr_accessor :auction_buyer_id

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :auction_closing_date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['auction_site'] = 'auction_site'
      @_hash['auction_item_site'] = 'auction_item_site'
      @_hash['auction_buyer_id'] = 'auction_buyer_id'
      @_hash['auction_closing_date'] = 'auction_closing_date'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        auction_site
        auction_item_site
        auction_buyer_id
        auction_closing_date
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(auction_site: SKIP, auction_item_site: SKIP,
                   auction_buyer_id: SKIP, auction_closing_date: SKIP)
      @auction_site = auction_site unless auction_site == SKIP
      @auction_item_site = auction_item_site unless auction_item_site == SKIP
      @auction_buyer_id = auction_buyer_id unless auction_buyer_id == SKIP
      @auction_closing_date = auction_closing_date unless auction_closing_date == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      auction_site = hash.key?('auction_site') ? hash['auction_site'] : SKIP
      auction_item_site =
        hash.key?('auction_item_site') ? hash['auction_item_site'] : SKIP
      auction_buyer_id =
        hash.key?('auction_buyer_id') ? hash['auction_buyer_id'] : SKIP
      auction_closing_date =
        hash.key?('auction_closing_date') ? hash['auction_closing_date'] : SKIP

      # Create object from extracted values.
      AuctionInformation.new(auction_site: auction_site,
                             auction_item_site: auction_item_site,
                             auction_buyer_id: auction_buyer_id,
                             auction_closing_date: auction_closing_date)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} auction_site: #{@auction_site}, auction_item_site: #{@auction_item_site},"\
      " auction_buyer_id: #{@auction_buyer_id}, auction_closing_date: #{@auction_closing_date}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} auction_site: #{@auction_site.inspect}, auction_item_site:"\
      " #{@auction_item_site.inspect}, auction_buyer_id: #{@auction_buyer_id.inspect},"\
      " auction_closing_date: #{@auction_closing_date.inspect}>"
    end
  end
end
