# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The balances response information.
  class BalancesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of balance detail objects.
    # @return [Array[BalanceInformation]]
    attr_accessor :balances

    # The PayPal payer ID, which is a masked version of the PayPal account
    # number intended for use with third parties. The account number is
    # reversibly encrypted and a proprietary variant of Base32 is used to encode
    # the result.
    # @return [String]
    attr_accessor :account_id

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :as_of_time

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :last_refresh_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['balances'] = 'balances'
      @_hash['account_id'] = 'account_id'
      @_hash['as_of_time'] = 'as_of_time'
      @_hash['last_refresh_time'] = 'last_refresh_time'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        balances
        account_id
        as_of_time
        last_refresh_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(balances: SKIP, account_id: SKIP, as_of_time: SKIP,
                   last_refresh_time: SKIP)
      @balances = balances unless balances == SKIP
      @account_id = account_id unless account_id == SKIP
      @as_of_time = as_of_time unless as_of_time == SKIP
      @last_refresh_time = last_refresh_time unless last_refresh_time == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      balances = nil
      unless hash['balances'].nil?
        balances = []
        hash['balances'].each do |structure|
          balances << (BalanceInformation.from_hash(structure) if structure)
        end
      end

      balances = SKIP unless hash.key?('balances')
      account_id = hash.key?('account_id') ? hash['account_id'] : SKIP
      as_of_time = hash.key?('as_of_time') ? hash['as_of_time'] : SKIP
      last_refresh_time =
        hash.key?('last_refresh_time') ? hash['last_refresh_time'] : SKIP

      # Create object from extracted values.
      BalancesResponse.new(balances: balances,
                           account_id: account_id,
                           as_of_time: as_of_time,
                           last_refresh_time: last_refresh_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} balances: #{@balances}, account_id: #{@account_id}, as_of_time:"\
      " #{@as_of_time}, last_refresh_time: #{@last_refresh_time}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} balances: #{@balances.inspect}, account_id: #{@account_id.inspect},"\
      " as_of_time: #{@as_of_time.inspect}, last_refresh_time: #{@last_refresh_time.inspect}>"
    end
  end
end
