# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The plan details.
  class BillingPlan < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique PayPal-generated ID for the plan.
    # @return [String]
    attr_accessor :id

    # The ID for the product.
    # @return [String]
    attr_accessor :product_id

    # The plan name.
    # @return [String]
    attr_accessor :name

    # The plan status.
    # @return [SubscriptionPlanStatus]
    attr_accessor :status

    # The detailed description of the plan.
    # @return [String]
    attr_accessor :description

    # An array of billing cycles for trial billing and regular billing. A plan
    # can have at most two trial cycles and only one regular cycle.
    # @return [Array[SubscriptionBillingCycle]]
    attr_accessor :billing_cycles

    # The payment preferences for a subscription.
    # @return [PaymentPreferences]
    attr_accessor :payment_preferences

    # The merchant preferences for a subscription.
    # @return [MerchantPreferences]
    attr_accessor :merchant_preferences

    # The tax details.
    # @return [Taxes]
    attr_accessor :taxes

    # Indicates whether you can subscribe to this plan by providing a quantity
    # for the goods or service.
    # @return [TrueClass | FalseClass]
    attr_accessor :quantity_supported

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :create_time

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :update_time

    # An array of request-related [HATEOAS
    # links](/docs/api/reference/api-responses/#hateoas-links).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['product_id'] = 'product_id'
      @_hash['name'] = 'name'
      @_hash['status'] = 'status'
      @_hash['description'] = 'description'
      @_hash['billing_cycles'] = 'billing_cycles'
      @_hash['payment_preferences'] = 'payment_preferences'
      @_hash['merchant_preferences'] = 'merchant_preferences'
      @_hash['taxes'] = 'taxes'
      @_hash['quantity_supported'] = 'quantity_supported'
      @_hash['create_time'] = 'create_time'
      @_hash['update_time'] = 'update_time'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        product_id
        name
        status
        description
        billing_cycles
        payment_preferences
        merchant_preferences
        taxes
        quantity_supported
        create_time
        update_time
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, product_id: SKIP, name: SKIP, status: SKIP,
                   description: SKIP, billing_cycles: SKIP,
                   payment_preferences: SKIP, merchant_preferences: SKIP,
                   taxes: SKIP, quantity_supported: false, create_time: SKIP,
                   update_time: SKIP, links: SKIP)
      @id = id unless id == SKIP
      @product_id = product_id unless product_id == SKIP
      @name = name unless name == SKIP
      @status = status unless status == SKIP
      @description = description unless description == SKIP
      @billing_cycles = billing_cycles unless billing_cycles == SKIP
      @payment_preferences = payment_preferences unless payment_preferences == SKIP
      @merchant_preferences = merchant_preferences unless merchant_preferences == SKIP
      @taxes = taxes unless taxes == SKIP
      @quantity_supported = quantity_supported unless quantity_supported == SKIP
      @create_time = create_time unless create_time == SKIP
      @update_time = update_time unless update_time == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      product_id = hash.key?('product_id') ? hash['product_id'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      # Parameter is an array, so we need to iterate through it
      billing_cycles = nil
      unless hash['billing_cycles'].nil?
        billing_cycles = []
        hash['billing_cycles'].each do |structure|
          billing_cycles << (SubscriptionBillingCycle.from_hash(structure) if structure)
        end
      end

      billing_cycles = SKIP unless hash.key?('billing_cycles')
      payment_preferences = PaymentPreferences.from_hash(hash['payment_preferences']) if
        hash['payment_preferences']
      merchant_preferences = MerchantPreferences.from_hash(hash['merchant_preferences']) if
        hash['merchant_preferences']
      taxes = Taxes.from_hash(hash['taxes']) if hash['taxes']
      quantity_supported = hash['quantity_supported'] ||= false
      create_time = hash.key?('create_time') ? hash['create_time'] : SKIP
      update_time = hash.key?('update_time') ? hash['update_time'] : SKIP
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      BillingPlan.new(id: id,
                      product_id: product_id,
                      name: name,
                      status: status,
                      description: description,
                      billing_cycles: billing_cycles,
                      payment_preferences: payment_preferences,
                      merchant_preferences: merchant_preferences,
                      taxes: taxes,
                      quantity_supported: quantity_supported,
                      create_time: create_time,
                      update_time: update_time,
                      links: links)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, product_id: #{@product_id}, name: #{@name}, status: #{@status},"\
      " description: #{@description}, billing_cycles: #{@billing_cycles}, payment_preferences:"\
      " #{@payment_preferences}, merchant_preferences: #{@merchant_preferences}, taxes: #{@taxes},"\
      " quantity_supported: #{@quantity_supported}, create_time: #{@create_time}, update_time:"\
      " #{@update_time}, links: #{@links}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, product_id: #{@product_id.inspect}, name:"\
      " #{@name.inspect}, status: #{@status.inspect}, description: #{@description.inspect},"\
      " billing_cycles: #{@billing_cycles.inspect}, payment_preferences:"\
      " #{@payment_preferences.inspect}, merchant_preferences: #{@merchant_preferences.inspect},"\
      " taxes: #{@taxes.inspect}, quantity_supported: #{@quantity_supported.inspect}, create_time:"\
      " #{@create_time.inspect}, update_time: #{@update_time.inspect}, links: #{@links.inspect}>"
    end
  end
end
