# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # CallBack event.
  class CallbackEvents
    CALLBACK_EVENTS = [
      # When Buyer changes or selects the shipping address on the PayPal/Venmo
      # buyer approval flow , PayPal/Venmo will call merchant with the callback
      # URL to update order totals.
      SHIPPING_ADDRESS = 'SHIPPING_ADDRESS'.freeze,

      # When Buyer changes or selects the shipping options on the PayPal/Venmo
      # buyer approval flow , PayPal/Venmo will call merchant with the callback
      # URL to update order totals.
      SHIPPING_OPTIONS = 'SHIPPING_OPTIONS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = SHIPPING_ADDRESS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'shipping_address' then SHIPPING_ADDRESS
      when 'shipping_options' then SHIPPING_OPTIONS
      else
        default_value
      end
    end
  end
end
