# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # CallBack event.
  class CallbackEvents
    CALLBACK_EVENTS = [
      # When Buyer changes or selects the shipping address on the PayPal/Venmo
      # buyer approval flow , PayPal/Venmo will call merchant with the callback
      # URL to update order totals.
      SHIPPING_ADDRESS = 'SHIPPING_ADDRESS'.freeze,

      # When Buyer changes or selects the shipping options on the PayPal/Venmo
      # buyer approval flow , PayPal/Venmo will call merchant with the callback
      # URL to update order totals.
      SHIPPING_OPTIONS = 'SHIPPING_OPTIONS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
