# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The cancel subscription request details.
  class CancelSubscriptionRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The reason for the cancellation of a subscription.
    # @return [String]
    attr_accessor :reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['reason'] = 'reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(reason:)
      @reason = reason
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      reason = hash.key?('reason') ? hash['reason'] : nil

      # Create object from extracted values.
      CancelSubscriptionRequest.new(reason: reason)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} reason: #{@reason}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} reason: #{@reason.inspect}>"
    end
  end
end
