# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The type of capture.
  class CaptureType
    CAPTURE_TYPE = [
      # The outstanding balance that the subscriber must clear.
      OUTSTANDING_BALANCE = 'OUTSTANDING_BALANCE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = OUTSTANDING_BALANCE)
      return default_value if value.nil?

      default_value
    end
  end
end
