# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The status of the captured payment.
  class CaptureStatus
    CAPTURE_STATUS = [
      # The funds for this captured payment were credited to the payee's PayPal
      # account.
      COMPLETED = 'COMPLETED'.freeze,

      # The funds could not be captured.
      DECLINED = 'DECLINED'.freeze,

      # An amount less than this captured payment's amount was partially
      # refunded to the payer.
      PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED'.freeze,

      # The funds for this captured payment was not yet credited to the payee's
      # PayPal account. For more information, see status.details.
      PENDING = 'PENDING'.freeze,

      # An amount greater than or equal to this captured payment's amount was
      # refunded to the payer.
      REFUNDED = 'REFUNDED'.freeze,

      # There was an error while capturing payment.
      FAILED = 'FAILED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
