# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The payment card used to fund the payment. Card can be a credit or debit
  # card.
  class CardResponseWithBillingAddress < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The card holder's name as it appears on the card.
    # @return [String]
    attr_accessor :name

    # The portable international postal address. Maps to
    # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/
    # wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls:
    # the autocomplete
    # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-co
    # ntrols-the-autocomplete-attribute).
    # @return [Address]
    attr_accessor :billing_address

    # The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date
    # and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
    # @return [String]
    attr_accessor :expiry

    # The [three-character ISO-4217 currency
    # code](/api/rest/reference/currency-codes/) that identifies the currency.
    # @return [String]
    attr_accessor :currency_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['billing_address'] = 'billing_address'
      @_hash['expiry'] = 'expiry'
      @_hash['currency_code'] = 'currency_code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        billing_address
        expiry
        currency_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, billing_address: SKIP, expiry: SKIP,
                   currency_code: SKIP)
      @name = name unless name == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @expiry = expiry unless expiry == SKIP
      @currency_code = currency_code unless currency_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      billing_address = Address.from_hash(hash['billing_address']) if hash['billing_address']
      expiry = hash.key?('expiry') ? hash['expiry'] : SKIP
      currency_code = hash.key?('currency_code') ? hash['currency_code'] : SKIP

      # Create object from extracted values.
      CardResponseWithBillingAddress.new(name: name,
                                         billing_address: billing_address,
                                         expiry: expiry,
                                         currency_code: currency_code)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, billing_address: #{@billing_address}, expiry: #{@expiry},"\
      " currency_code: #{@currency_code}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, billing_address: #{@billing_address.inspect},"\
      " expiry: #{@expiry.inspect}, currency_code: #{@currency_code.inspect}>"
    end
  end
end
