# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Verification status of Card.
  class CardVerificationStatus
    CARD_VERIFICATION_STATUS = [
      # Card has been verified
      VERIFIED = 'VERIFIED'.freeze,

      # Card verification has failed
      FAILED = 'FAILED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = VERIFIED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'verified' then VERIFIED
      when 'failed' then FAILED
      else
        default_value
      end
    end
  end
end
