# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Verification status of Card.
  class CardVerificationStatus
    CARD_VERIFICATION_STATUS = [
      # Card has been verified
      VERIFIED = 'VERIFIED'.freeze,

      # Card verification has failed
      FAILED = 'FAILED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
