# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The cart information.
  class CartInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of item details.
    # @return [Array[ItemDetails]]
    attr_accessor :item_details

    # Indicates whether the item amount or the shipping amount already includes
    # tax.
    # @return [TrueClass | FalseClass]
    attr_accessor :tax_inclusive

    # The ID of the invoice. Appears for only PayPal-generated invoices.
    # @return [String]
    attr_accessor :paypal_invoice_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['item_details'] = 'item_details'
      @_hash['tax_inclusive'] = 'tax_inclusive'
      @_hash['paypal_invoice_id'] = 'paypal_invoice_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        item_details
        tax_inclusive
        paypal_invoice_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(item_details: SKIP, tax_inclusive: false,
                   paypal_invoice_id: SKIP)
      @item_details = item_details unless item_details == SKIP
      @tax_inclusive = tax_inclusive unless tax_inclusive == SKIP
      @paypal_invoice_id = paypal_invoice_id unless paypal_invoice_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      item_details = nil
      unless hash['item_details'].nil?
        item_details = []
        hash['item_details'].each do |structure|
          item_details << (ItemDetails.from_hash(structure) if structure)
        end
      end

      item_details = SKIP unless hash.key?('item_details')
      tax_inclusive = hash['tax_inclusive'] ||= false
      paypal_invoice_id =
        hash.key?('paypal_invoice_id') ? hash['paypal_invoice_id'] : SKIP

      # Create object from extracted values.
      CartInformation.new(item_details: item_details,
                          tax_inclusive: tax_inclusive,
                          paypal_invoice_id: paypal_invoice_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} item_details: #{@item_details}, tax_inclusive: #{@tax_inclusive},"\
      " paypal_invoice_id: #{@paypal_invoice_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} item_details: #{@item_details.inspect}, tax_inclusive:"\
      " #{@tax_inclusive.inspect}, paypal_invoice_id: #{@paypal_invoice_id.inspect}>"
    end
  end
end
