# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The intent to either capture payment immediately or authorize a payment for
  # an order after order creation.
  class CheckoutPaymentIntent
    CHECKOUT_PAYMENT_INTENT = [
      # The merchant intends to capture payment immediately after the customer
      # makes a payment.
      CAPTURE = 'CAPTURE'.freeze,

      # The merchant intends to authorize a payment and place funds on hold
      # after the customer makes a payment. Authorized payments are best
      # captured within three days of authorization but are available to capture
      # for up to 29 days. After the three-day honor period, the original
      # authorized payment expires and you must re-authorize the payment. You
      # must make a separate request to capture payments on demand. This intent
      # is not supported when you have more than one `purchase_unit` within your
      # order.
      AUTHORIZE = 'AUTHORIZE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = CAPTURE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'capture' then CAPTURE
      when 'authorize' then AUTHORIZE
      else
        default_value
      end
    end
  end
end
