# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The frequency of the terms reset cycle.
  class CycleFrequency < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The interval unit at which the the usage limits will be reset.
    # @return [FrequencyIntervalUnit]
    attr_accessor :interval_unit

    # The interval count at which the terms will be reset, this is ignored if
    # the unit is LIFETIME.
    # @return [Integer]
    attr_accessor :interval_count

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['interval_unit'] = 'interval_unit'
      @_hash['interval_count'] = 'interval_count'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        interval_count
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(interval_unit:, interval_count: 1)
      @interval_unit = interval_unit
      @interval_count = interval_count unless interval_count == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      interval_unit = hash.key?('interval_unit') ? hash['interval_unit'] : nil
      interval_count = hash['interval_count'] ||= 1

      # Create object from extracted values.
      CycleFrequency.new(interval_unit: interval_unit,
                         interval_count: interval_count)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} interval_unit: #{@interval_unit}, interval_count: #{@interval_count}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} interval_unit: #{@interval_unit.inspect}, interval_count:"\
      " #{@interval_count.inspect}>"
    end
  end
end
