# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Electronic Commerce Indicator (ECI). The ECI value is part of the 2 data
  # elements that indicate the transaction was processed electronically. This
  # should be passed on the authorization transaction to the Gateway/Processor.
  class EciFlag
    ECI_FLAG = [
      # Mastercard non-3-D Secure transaction.
      MASTERCARD_NON_3D_SECURE_TRANSACTION = 'MASTERCARD_NON_3D_SECURE_TRANSACTION'.freeze,

      # Mastercard attempted authentication transaction.
      MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION = 'MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION'.freeze,

      # Mastercard fully authenticated transaction.
      MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION = 'MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION'.freeze,

      # VISA, AMEX, JCB, DINERS CLUB fully authenticated transaction.
      FULLY_AUTHENTICATED_TRANSACTION = 'FULLY_AUTHENTICATED_TRANSACTION'.freeze,

      # VISA, AMEX, JCB, DINERS CLUB attempted authentication transaction.
      ATTEMPTED_AUTHENTICATION_TRANSACTION = 'ATTEMPTED_AUTHENTICATION_TRANSACTION'.freeze,

      # VISA, AMEX, JCB, DINERS CLUB non-3-D Secure transaction.
      NON_3D_SECURE_TRANSACTION = 'NON_3D_SECURE_TRANSACTION'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
