# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Status of Authentication eligibility.
  class EnrollmentStatus
    ENROLLMENT_STATUS = [
      # Yes. The bank is participating in 3-D Secure protocol and will return
      # the ACSUrl.
      ENROLLED = 'Y'.freeze,

      # No. The bank is not participating in 3-D Secure protocol.
      NOTENROLLED = 'N'.freeze,

      # Unavailable. The DS or ACS is not available for authentication at the
      # time of the request.
      UNAVAILABLE = 'U'.freeze,

      # Bypass. The merchant authentication rule is triggered to bypass
      # authentication.
      BYPASS = 'B'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENROLLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enrolled' then ENROLLED
      when 'notenrolled' then NOTENROLLED
      when 'unavailable' then UNAVAILABLE
      when 'bypass' then BYPASS
      else
        default_value
      end
    end
  end
end
