# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Status of Authentication eligibility.
  class EnrollmentStatus
    ENROLLMENT_STATUS = [
      # Yes. The bank is participating in 3-D Secure protocol and will return
      # the ACSUrl.
      ENROLLED = 'Y'.freeze,

      # No. The bank is not participating in 3-D Secure protocol.
      NOTENROLLED = 'N'.freeze,

      # Unavailable. The DS or ACS is not available for authentication at the
      # time of the request.
      UNAVAILABLE = 'U'.freeze,

      # Bypass. The merchant authentication rule is triggered to bypass
      # authentication.
      BYPASS = 'B'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
