# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The details for the failed payment of the subscription.
  class FailedPaymentDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :amount

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :time

    # The reason code for the payment failure.
    # @return [ReasonCode]
    attr_accessor :reason_code

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :next_payment_retry_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['time'] = 'time'
      @_hash['reason_code'] = 'reason_code'
      @_hash['next_payment_retry_time'] = 'next_payment_retry_time'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        reason_code
        next_payment_retry_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(amount:, time:, reason_code: SKIP,
                   next_payment_retry_time: SKIP)
      @amount = amount
      @time = time
      @reason_code = reason_code unless reason_code == SKIP
      @next_payment_retry_time = next_payment_retry_time unless next_payment_retry_time == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = Money.from_hash(hash['amount']) if hash['amount']
      time = hash.key?('time') ? hash['time'] : nil
      reason_code = hash.key?('reason_code') ? hash['reason_code'] : SKIP
      next_payment_retry_time =
        hash.key?('next_payment_retry_time') ? hash['next_payment_retry_time'] : SKIP

      # Create object from extracted values.
      FailedPaymentDetails.new(amount: amount,
                               time: time,
                               reason_code: reason_code,
                               next_payment_retry_time: next_payment_retry_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount}, time: #{@time}, reason_code: #{@reason_code},"\
      " next_payment_retry_time: #{@next_payment_retry_time}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} amount: #{@amount.inspect}, time: #{@time.inspect}, reason_code:"\
      " #{@reason_code.inspect}, next_payment_retry_time: #{@next_payment_retry_time.inspect}>"
    end
  end
end
