# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The incentive details.
  class IncentiveDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The type of incentive, such as a special offer or coupon.
    # @return [String]
    attr_accessor :incentive_type

    # The code that identifies an incentive, such as a coupon.
    # @return [String]
    attr_accessor :incentive_code

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :incentive_amount

    # The incentive program code that identifies a merchant loyalty or incentive
    # program.
    # @return [String]
    attr_accessor :incentive_program_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['incentive_type'] = 'incentive_type'
      @_hash['incentive_code'] = 'incentive_code'
      @_hash['incentive_amount'] = 'incentive_amount'
      @_hash['incentive_program_code'] = 'incentive_program_code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        incentive_type
        incentive_code
        incentive_amount
        incentive_program_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(incentive_type: SKIP, incentive_code: SKIP,
                   incentive_amount: SKIP, incentive_program_code: SKIP)
      @incentive_type = incentive_type unless incentive_type == SKIP
      @incentive_code = incentive_code unless incentive_code == SKIP
      @incentive_amount = incentive_amount unless incentive_amount == SKIP
      @incentive_program_code = incentive_program_code unless incentive_program_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      incentive_type =
        hash.key?('incentive_type') ? hash['incentive_type'] : SKIP
      incentive_code =
        hash.key?('incentive_code') ? hash['incentive_code'] : SKIP
      incentive_amount = Money.from_hash(hash['incentive_amount']) if hash['incentive_amount']
      incentive_program_code =
        hash.key?('incentive_program_code') ? hash['incentive_program_code'] : SKIP

      # Create object from extracted values.
      IncentiveDetails.new(incentive_type: incentive_type,
                           incentive_code: incentive_code,
                           incentive_amount: incentive_amount,
                           incentive_program_code: incentive_program_code)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} incentive_type: #{@incentive_type}, incentive_code: #{@incentive_code},"\
      " incentive_amount: #{@incentive_amount}, incentive_program_code:"\
      " #{@incentive_program_code}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} incentive_type: #{@incentive_type.inspect}, incentive_code:"\
      " #{@incentive_code.inspect}, incentive_amount: #{@incentive_amount.inspect},"\
      " incentive_program_code: #{@incentive_program_code.inspect}>"
    end
  end
end
