# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The interval at which the subscription is charged or billed.
  class IntervalUnit
    INTERVAL_UNIT = [
      # A daily billing cycle.
      DAY = 'DAY'.freeze,

      # A weekly billing cycle.
      WEEK = 'WEEK'.freeze,

      # A monthly billing cycle.
      MONTH = 'MONTH'.freeze,

      # A yearly billing cycle.
      YEAR = 'YEAR'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
