# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The item details.
  class ItemDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An item code that identifies a merchant's goods or service.
    # @return [String]
    attr_accessor :item_code

    # The item name.
    # @return [String]
    attr_accessor :item_name

    # The item description.
    # @return [String]
    attr_accessor :item_description

    # The item options. Describes option choices on the purchase of the item in
    # some detail.
    # @return [String]
    attr_accessor :item_options

    # The number of purchased units of goods or a service.
    # @return [String]
    attr_accessor :item_quantity

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :item_unit_price

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :item_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :discount_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :adjustment_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :gift_wrap_amount

    # The percentage, as a fixed-point, signed decimal number. For example,
    # define a 19.99% interest rate as `19.99`.
    # @return [String]
    attr_accessor :tax_percentage

    # An array of tax amounts levied by a government on the purchase of goods or
    # services.
    # @return [Array[TaxAmount]]
    attr_accessor :tax_amounts

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :basic_shipping_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :extra_shipping_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :handling_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :insurance_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :total_item_amount

    # The invoice number. An alphanumeric string that identifies a billing for a
    # merchant.
    # @return [String]
    attr_accessor :invoice_number

    # An array of checkout options. Each option has a name and value.
    # @return [Array[CheckoutOption]]
    attr_accessor :checkout_options

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['item_code'] = 'item_code'
      @_hash['item_name'] = 'item_name'
      @_hash['item_description'] = 'item_description'
      @_hash['item_options'] = 'item_options'
      @_hash['item_quantity'] = 'item_quantity'
      @_hash['item_unit_price'] = 'item_unit_price'
      @_hash['item_amount'] = 'item_amount'
      @_hash['discount_amount'] = 'discount_amount'
      @_hash['adjustment_amount'] = 'adjustment_amount'
      @_hash['gift_wrap_amount'] = 'gift_wrap_amount'
      @_hash['tax_percentage'] = 'tax_percentage'
      @_hash['tax_amounts'] = 'tax_amounts'
      @_hash['basic_shipping_amount'] = 'basic_shipping_amount'
      @_hash['extra_shipping_amount'] = 'extra_shipping_amount'
      @_hash['handling_amount'] = 'handling_amount'
      @_hash['insurance_amount'] = 'insurance_amount'
      @_hash['total_item_amount'] = 'total_item_amount'
      @_hash['invoice_number'] = 'invoice_number'
      @_hash['checkout_options'] = 'checkout_options'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        item_code
        item_name
        item_description
        item_options
        item_quantity
        item_unit_price
        item_amount
        discount_amount
        adjustment_amount
        gift_wrap_amount
        tax_percentage
        tax_amounts
        basic_shipping_amount
        extra_shipping_amount
        handling_amount
        insurance_amount
        total_item_amount
        invoice_number
        checkout_options
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(item_code: SKIP, item_name: SKIP, item_description: SKIP,
                   item_options: SKIP, item_quantity: SKIP,
                   item_unit_price: SKIP, item_amount: SKIP,
                   discount_amount: SKIP, adjustment_amount: SKIP,
                   gift_wrap_amount: SKIP, tax_percentage: SKIP,
                   tax_amounts: SKIP, basic_shipping_amount: SKIP,
                   extra_shipping_amount: SKIP, handling_amount: SKIP,
                   insurance_amount: SKIP, total_item_amount: SKIP,
                   invoice_number: SKIP, checkout_options: SKIP)
      @item_code = item_code unless item_code == SKIP
      @item_name = item_name unless item_name == SKIP
      @item_description = item_description unless item_description == SKIP
      @item_options = item_options unless item_options == SKIP
      @item_quantity = item_quantity unless item_quantity == SKIP
      @item_unit_price = item_unit_price unless item_unit_price == SKIP
      @item_amount = item_amount unless item_amount == SKIP
      @discount_amount = discount_amount unless discount_amount == SKIP
      @adjustment_amount = adjustment_amount unless adjustment_amount == SKIP
      @gift_wrap_amount = gift_wrap_amount unless gift_wrap_amount == SKIP
      @tax_percentage = tax_percentage unless tax_percentage == SKIP
      @tax_amounts = tax_amounts unless tax_amounts == SKIP
      @basic_shipping_amount = basic_shipping_amount unless basic_shipping_amount == SKIP
      @extra_shipping_amount = extra_shipping_amount unless extra_shipping_amount == SKIP
      @handling_amount = handling_amount unless handling_amount == SKIP
      @insurance_amount = insurance_amount unless insurance_amount == SKIP
      @total_item_amount = total_item_amount unless total_item_amount == SKIP
      @invoice_number = invoice_number unless invoice_number == SKIP
      @checkout_options = checkout_options unless checkout_options == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      item_code = hash.key?('item_code') ? hash['item_code'] : SKIP
      item_name = hash.key?('item_name') ? hash['item_name'] : SKIP
      item_description =
        hash.key?('item_description') ? hash['item_description'] : SKIP
      item_options = hash.key?('item_options') ? hash['item_options'] : SKIP
      item_quantity = hash.key?('item_quantity') ? hash['item_quantity'] : SKIP
      item_unit_price = Money.from_hash(hash['item_unit_price']) if hash['item_unit_price']
      item_amount = Money.from_hash(hash['item_amount']) if hash['item_amount']
      discount_amount = Money.from_hash(hash['discount_amount']) if hash['discount_amount']
      adjustment_amount = Money.from_hash(hash['adjustment_amount']) if hash['adjustment_amount']
      gift_wrap_amount = Money.from_hash(hash['gift_wrap_amount']) if hash['gift_wrap_amount']
      tax_percentage =
        hash.key?('tax_percentage') ? hash['tax_percentage'] : SKIP
      # Parameter is an array, so we need to iterate through it
      tax_amounts = nil
      unless hash['tax_amounts'].nil?
        tax_amounts = []
        hash['tax_amounts'].each do |structure|
          tax_amounts << (TaxAmount.from_hash(structure) if structure)
        end
      end

      tax_amounts = SKIP unless hash.key?('tax_amounts')
      basic_shipping_amount = Money.from_hash(hash['basic_shipping_amount']) if
        hash['basic_shipping_amount']
      extra_shipping_amount = Money.from_hash(hash['extra_shipping_amount']) if
        hash['extra_shipping_amount']
      handling_amount = Money.from_hash(hash['handling_amount']) if hash['handling_amount']
      insurance_amount = Money.from_hash(hash['insurance_amount']) if hash['insurance_amount']
      total_item_amount = Money.from_hash(hash['total_item_amount']) if hash['total_item_amount']
      invoice_number =
        hash.key?('invoice_number') ? hash['invoice_number'] : SKIP
      # Parameter is an array, so we need to iterate through it
      checkout_options = nil
      unless hash['checkout_options'].nil?
        checkout_options = []
        hash['checkout_options'].each do |structure|
          checkout_options << (CheckoutOption.from_hash(structure) if structure)
        end
      end

      checkout_options = SKIP unless hash.key?('checkout_options')

      # Create object from extracted values.
      ItemDetails.new(item_code: item_code,
                      item_name: item_name,
                      item_description: item_description,
                      item_options: item_options,
                      item_quantity: item_quantity,
                      item_unit_price: item_unit_price,
                      item_amount: item_amount,
                      discount_amount: discount_amount,
                      adjustment_amount: adjustment_amount,
                      gift_wrap_amount: gift_wrap_amount,
                      tax_percentage: tax_percentage,
                      tax_amounts: tax_amounts,
                      basic_shipping_amount: basic_shipping_amount,
                      extra_shipping_amount: extra_shipping_amount,
                      handling_amount: handling_amount,
                      insurance_amount: insurance_amount,
                      total_item_amount: total_item_amount,
                      invoice_number: invoice_number,
                      checkout_options: checkout_options)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} item_code: #{@item_code}, item_name: #{@item_name}, item_description:"\
      " #{@item_description}, item_options: #{@item_options}, item_quantity: #{@item_quantity},"\
      " item_unit_price: #{@item_unit_price}, item_amount: #{@item_amount}, discount_amount:"\
      " #{@discount_amount}, adjustment_amount: #{@adjustment_amount}, gift_wrap_amount:"\
      " #{@gift_wrap_amount}, tax_percentage: #{@tax_percentage}, tax_amounts: #{@tax_amounts},"\
      " basic_shipping_amount: #{@basic_shipping_amount}, extra_shipping_amount:"\
      " #{@extra_shipping_amount}, handling_amount: #{@handling_amount}, insurance_amount:"\
      " #{@insurance_amount}, total_item_amount: #{@total_item_amount}, invoice_number:"\
      " #{@invoice_number}, checkout_options: #{@checkout_options}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} item_code: #{@item_code.inspect}, item_name: #{@item_name.inspect},"\
      " item_description: #{@item_description.inspect}, item_options: #{@item_options.inspect},"\
      " item_quantity: #{@item_quantity.inspect}, item_unit_price: #{@item_unit_price.inspect},"\
      " item_amount: #{@item_amount.inspect}, discount_amount: #{@discount_amount.inspect},"\
      " adjustment_amount: #{@adjustment_amount.inspect}, gift_wrap_amount:"\
      " #{@gift_wrap_amount.inspect}, tax_percentage: #{@tax_percentage.inspect}, tax_amounts:"\
      " #{@tax_amounts.inspect}, basic_shipping_amount: #{@basic_shipping_amount.inspect},"\
      " extra_shipping_amount: #{@extra_shipping_amount.inspect}, handling_amount:"\
      " #{@handling_amount.inspect}, insurance_amount: #{@insurance_amount.inspect},"\
      " total_item_amount: #{@total_item_amount.inspect}, invoice_number:"\
      " #{@invoice_number.inspect}, checkout_options: #{@checkout_options.inspect}>"
    end
  end
end
