# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The HTTP method required to make the related call.
  class LinkHttpMethod
    LINK_HTTP_METHOD = [
      # The HTTP GET method.
      GET = 'GET'.freeze,

      # The HTTP POST method.
      POST = 'POST'.freeze,

      # The HTTP PUT method.
      PUT = 'PUT'.freeze,

      # The HTTP DELETE method.
      DELETE = 'DELETE'.freeze,

      # The HTTP HEAD method.
      HEAD = 'HEAD'.freeze,

      # The HTTP CONNECT method.
      CONNECT = 'CONNECT'.freeze,

      # The HTTP OPTIONS method.
      OPTIONS = 'OPTIONS'.freeze,

      # The HTTP PATCH method.
      PATCH = 'PATCH'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = GET)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'get' then GET
      when 'post' then POST
      when 'put' then PUT
      when 'delete' then DELETE
      when 'head' then HEAD
      when 'connect' then CONNECT
      when 'options' then OPTIONS
      when 'patch' then PATCH
      else
        default_value
      end
    end
  end
end
