# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Buyer's mobile web browser context to app switch to the PayPal consumer app.
  class MobileWebContext < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Merchant preference on how the buyer can navigate back to merchant website
    # post approving the transaction on the PayPal App.
    # @return [MobileReturnFlow]
    attr_accessor :return_flow

    # User agent from the request originating from the buyer's device. This will
    # be used to identify the buyer's operating system and browser versions.
    # NOTE: Merchants must not alter or modify the buyer's device user agent.
    # @return [String]
    attr_accessor :buyer_user_agent

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['return_flow'] = 'return_flow'
      @_hash['buyer_user_agent'] = 'buyer_user_agent'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        return_flow
        buyer_user_agent
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(return_flow: MobileReturnFlow::AUTO, buyer_user_agent: SKIP)
      @return_flow = return_flow unless return_flow == SKIP
      @buyer_user_agent = buyer_user_agent unless buyer_user_agent == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      return_flow = hash['return_flow'] ||= MobileReturnFlow::AUTO
      buyer_user_agent =
        hash.key?('buyer_user_agent') ? hash['buyer_user_agent'] : SKIP

      # Create object from extracted values.
      MobileWebContext.new(return_flow: return_flow,
                           buyer_user_agent: buyer_user_agent)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} return_flow: #{@return_flow}, buyer_user_agent: #{@buyer_user_agent}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} return_flow: #{@return_flow.inspect}, buyer_user_agent:"\
      " #{@buyer_user_agent.inspect}>"
    end
  end
end
