# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The response to a request to update the quantity of the product or service
  # in a subscription. You can also use this method to switch the plan and
  # update the `shipping_amount` and `shipping_address` values for the
  # subscription. This type of update requires the buyer's consent.
  class ModifySubscriptionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique PayPal-generated ID for the plan.
    # @return [String]
    attr_accessor :plan_id

    # The quantity of the product or service in the subscription.
    # @return [String]
    attr_accessor :quantity

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :shipping_amount

    # The shipping details.
    # @return [ShippingDetails]
    attr_accessor :shipping_address

    # An inline plan object to customise the subscription. You can override plan
    # level default attributes by providing customised values for the
    # subscription in this object.
    # @return [PlanOverride]
    attr_accessor :plan

    # Indicates whether the subscription has overridden any plan attributes.
    # @return [TrueClass | FalseClass]
    attr_accessor :plan_overridden

    # An array of request-related [HATEOAS
    # links](/docs/api/reference/api-responses/#hateoas-links).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['plan_id'] = 'plan_id'
      @_hash['quantity'] = 'quantity'
      @_hash['shipping_amount'] = 'shipping_amount'
      @_hash['shipping_address'] = 'shipping_address'
      @_hash['plan'] = 'plan'
      @_hash['plan_overridden'] = 'plan_overridden'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        plan_id
        quantity
        shipping_amount
        shipping_address
        plan
        plan_overridden
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(plan_id: SKIP, quantity: SKIP, shipping_amount: SKIP,
                   shipping_address: SKIP, plan: SKIP, plan_overridden: SKIP,
                   links: SKIP)
      @plan_id = plan_id unless plan_id == SKIP
      @quantity = quantity unless quantity == SKIP
      @shipping_amount = shipping_amount unless shipping_amount == SKIP
      @shipping_address = shipping_address unless shipping_address == SKIP
      @plan = plan unless plan == SKIP
      @plan_overridden = plan_overridden unless plan_overridden == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      plan_id = hash.key?('plan_id') ? hash['plan_id'] : SKIP
      quantity = hash.key?('quantity') ? hash['quantity'] : SKIP
      shipping_amount = Money.from_hash(hash['shipping_amount']) if hash['shipping_amount']
      shipping_address = ShippingDetails.from_hash(hash['shipping_address']) if
        hash['shipping_address']
      plan = PlanOverride.from_hash(hash['plan']) if hash['plan']
      plan_overridden =
        hash.key?('plan_overridden') ? hash['plan_overridden'] : SKIP
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      ModifySubscriptionResponse.new(plan_id: plan_id,
                                     quantity: quantity,
                                     shipping_amount: shipping_amount,
                                     shipping_address: shipping_address,
                                     plan: plan,
                                     plan_overridden: plan_overridden,
                                     links: links)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} plan_id: #{@plan_id}, quantity: #{@quantity}, shipping_amount:"\
      " #{@shipping_amount}, shipping_address: #{@shipping_address}, plan: #{@plan},"\
      " plan_overridden: #{@plan_overridden}, links: #{@links}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} plan_id: #{@plan_id.inspect}, quantity: #{@quantity.inspect},"\
      " shipping_amount: #{@shipping_amount.inspect}, shipping_address:"\
      " #{@shipping_address.inspect}, plan: #{@plan.inspect}, plan_overridden:"\
      " #{@plan_overridden.inspect}, links: #{@links.inspect}>"
    end
  end
end
