# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Merchant provided, buyer's native app preferences to app switch to the
  # PayPal consumer app.
  class NativeAppContext < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Operating System type of the device that the buyer is using.
    # @return [OsType]
    attr_accessor :os_type

    # Operating System version of the device that the buyer is using.
    # @return [String]
    attr_accessor :os_version

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['os_type'] = 'os_type'
      @_hash['os_version'] = 'os_version'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        os_type
        os_version
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(os_type: SKIP, os_version: SKIP)
      @os_type = os_type unless os_type == SKIP
      @os_version = os_version unless os_version == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      os_type = hash.key?('os_type') ? hash['os_type'] : SKIP
      os_version = hash.key?('os_version') ? hash['os_version'] : SKIP

      # Create object from extracted values.
      NativeAppContext.new(os_type: os_type,
                           os_version: os_version)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} os_type: #{@os_type}, os_version: #{@os_version}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} os_type: #{@os_type.inspect}, os_version: #{@os_version.inspect}>"
    end
  end
end
