# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Metadata for merchant-managed recurring billing plans. Valid only during the
  # saved payment method token or billing agreement creation.
  class OrderBillingPlan < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of billing cycles for trial billing and regular billing. A plan
    # can have at most two trial cycles and only one regular cycle.
    # @return [Array[BillingCycle]]
    attr_accessor :billing_cycles

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :setup_fee

    # Name of the recurring plan.
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['billing_cycles'] = 'billing_cycles'
      @_hash['setup_fee'] = 'setup_fee'
      @_hash['name'] = 'name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        setup_fee
        name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(billing_cycles:, setup_fee: SKIP, name: SKIP)
      @billing_cycles = billing_cycles
      @setup_fee = setup_fee unless setup_fee == SKIP
      @name = name unless name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      billing_cycles = nil
      unless hash['billing_cycles'].nil?
        billing_cycles = []
        hash['billing_cycles'].each do |structure|
          billing_cycles << (BillingCycle.from_hash(structure) if structure)
        end
      end

      billing_cycles = nil unless hash.key?('billing_cycles')
      setup_fee = Money.from_hash(hash['setup_fee']) if hash['setup_fee']
      name = hash.key?('name') ? hash['name'] : SKIP

      # Create object from extracted values.
      OrderBillingPlan.new(billing_cycles: billing_cycles,
                           setup_fee: setup_fee,
                           name: name)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_cycles: #{@billing_cycles}, setup_fee: #{@setup_fee}, name:"\
      " #{@name}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_cycles: #{@billing_cycles.inspect}, setup_fee:"\
      " #{@setup_fee.inspect}, name: #{@name.inspect}>"
    end
  end
end
