# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Operating System type of the device that the buyer is using.
  class OsType
    OS_TYPE = [
      # Google Android OS.
      ANDROID = 'ANDROID'.freeze,

      # Apple OS typically found in Apple mobile devices.
      IOS = 'IOS'.freeze,

      # Any other OS type.
      OTHER = 'OTHER'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ANDROID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'android' then ANDROID
      when 'ios' then IOS
      when 'other' then OTHER
      else
        default_value
      end
    end
  end
end
