# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The merchant-preferred payment methods.
  class PayeePaymentMethodPreference
    PAYEE_PAYMENT_METHOD_PREFERENCE = [
      # Accepts any type of payment from the customer.
      UNRESTRICTED = 'UNRESTRICTED'.freeze,

      # Accepts only immediate payment from the customer. For example, credit
      # card, PayPal balance, or instant ACH. Ensures that at the time of
      # capture, the payment does not have the `pending` status.
      IMMEDIATE_PAYMENT_REQUIRED = 'IMMEDIATE_PAYMENT_REQUIRED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
