# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The customer and merchant payment preferences.
  class PaymentMethod < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The merchant-preferred payment methods.
    # @return [PayeePaymentMethodPreference]
    attr_accessor :payee_preferred

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payee_preferred'] = 'payee_preferred'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payee_preferred
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payee_preferred: PayeePaymentMethodPreference::UNRESTRICTED)
      @payee_preferred = payee_preferred unless payee_preferred == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payee_preferred =
        hash['payee_preferred'] ||= PayeePaymentMethodPreference::UNRESTRICTED

      # Create object from extracted values.
      PaymentMethod.new(payee_preferred: payee_preferred)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} payee_preferred: #{@payee_preferred}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} payee_preferred: #{@payee_preferred.inspect}>"
    end
  end
end
