# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The declined payment transactions might have payment advice codes. The card
  # networks, like Visa and Mastercard, return payment advice codes.
  class PaymentsPaymentAdviceCode
    PAYMENTS_PAYMENT_ADVICE_CODE = [
      # For Mastercard, expired card account upgrade or portfolio sale
      # conversion. Obtain new account information before next billing cycle.
      PAYMENTADVICE_01 = '01'.freeze,

      # For Mastercard, over credit limit or insufficient funds. Retry the
      # transaction 72 hours later. For Visa, the card holder wants to stop only
      # one specific payment in the recurring payment relationship. The merchant
      # must NOT resubmit the same transaction. The merchant can continue the
      # billing process in the subsequent billing period.
      PAYMENTADVICE_02 = '02'.freeze,

      # For Mastercard, account closed as fraudulent. Obtain another type of
      # payment from customer due to account being closed or fraud. Possible
      # reason: Account closed as fraudulent. For Visa, the card holder wants to
      # stop all recurring payment transactions for a specific merchant. Stop
      # recurring payment requests.
      PAYMENTADVICE_03 = '03'.freeze,

      # For Mastercard, the card holder has been unsuccessful at canceling
      # recurring payment through merchant. Stop recurring payment requests. For
      # Visa, all recurring payments were canceled for the card number
      # requested. Stop recurring payment requests.
      PAYMENTADVICE_21 = '21'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
