# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The customer type associated with the PayPal payment token. This is to
  # indicate whether the customer acting on the merchant / platform is either a
  # business or a consumer., The customer type associated with a digital wallet
  # payment token. This is to indicate whether the customer acting on the
  # merchant / platform is either a business or a consumer.
  class PaypalPaymentTokenCustomerType
    PAYPAL_PAYMENT_TOKEN_CUSTOMER_TYPE = [
      # The customer vaulting the PayPal payment token is a consumer on the
      # merchant / platform.
      CONSUMER = 'CONSUMER'.freeze,

      # The customer vaulting the PayPal payment token is a business on merchant
      # / platform.
      BUSINESS = 'BUSINESS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
