# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The account status indicates whether the buyer has verified the financial
  # details associated with their PayPal account.
  class PaypalWalletAccountVerificationStatus
    PAYPAL_WALLET_ACCOUNT_VERIFICATION_STATUS = [
      # The buyer has completed the verification of the financial details
      # associated with this PayPal account. For example: confirming their bank
      # account.
      VERIFIED = 'VERIFIED'.freeze,

      # The buyer has not completed the verification of the financial details
      # associated with this PayPal account. For example: confirming their bank
      # account.
      UNVERIFIED = 'UNVERIFIED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = VERIFIED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'verified' then VERIFIED
      when 'unverified' then UNVERIFIED
      else
        default_value
      end
    end
  end
end
