# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The PayPal reference ID type.
  class PaypalReferenceIdType
    PAYPAL_REFERENCE_ID_TYPE = [
      # An order ID.
      ODR = 'ODR'.freeze,

      # A transaction ID.
      TXN = 'TXN'.freeze,

      # A subscription ID.
      SUB = 'SUB'.freeze,

      # A pre-approved payment ID.
      PAP = 'PAP'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
