# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The type of landing page to show on the PayPal site for customer checkout.
  class PaypalExperienceLandingPage
    PAYPAL_EXPERIENCE_LANDING_PAGE = [
      # When the customer clicks PayPal Checkout, the customer is redirected to
      # a page to log in to PayPal and approve the payment.
      LOGIN = 'LOGIN'.freeze,

      # When the customer clicks PayPal Checkout, the customer is redirected to
      # a page to enter credit or debit card and other relevant billing
      # information required to complete the purchase. This option has
      # previously been also called as 'BILLING'
      GUEST_CHECKOUT = 'GUEST_CHECKOUT'.freeze,

      # When the customer clicks PayPal Checkout, the customer is redirected to
      # either a page to log in to PayPal and approve the payment or to a page
      # to enter credit or debit card and other relevant billing information
      # required to complete the purchase, depending on their previous
      # interaction with PayPal.
      NO_PREFERENCE = 'NO_PREFERENCE'.freeze,

      # DEPRECATED - please use GUEST_CHECKOUT. All implementations of 'BILLING'
      # will be routed to 'GUEST_CHECKOUT'. When the customer clicks PayPal
      # Checkout, the customer is redirected to a page to enter credit or debit
      # card and other relevant billing information required to complete the
      # purchase.
      BILLING = 'BILLING'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
