# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The location from which the shipping address is derived.
  class PaypalWalletContextShippingPreference
    PAYPAL_WALLET_CONTEXT_SHIPPING_PREFERENCE = [
      # Get the customer-provided shipping address on the PayPal site.
      GET_FROM_FILE = 'GET_FROM_FILE'.freeze,

      # Removes the shipping address information from the API response and the
      # Paypal site. However, the shipping.phone_number and
      # shipping.email_address fields will still be returned to allow for
      # digital goods delivery.
      NO_SHIPPING = 'NO_SHIPPING'.freeze,

      # Get the merchant-provided address. The customer cannot change this
      # address on the PayPal site. If merchant does not pass an address,
      # customer can choose the address on PayPal pages.
      SET_PROVIDED_ADDRESS = 'SET_PROVIDED_ADDRESS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
