# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The phone type.
  class PhoneType
    PHONE_TYPE = [
      # Fax number.
      FAX = 'FAX'.freeze,

      # Home phone number.
      HOME = 'HOME'.freeze,

      # Mobile phone number.
      MOBILE = 'MOBILE'.freeze,

      # Other phone number.
      OTHER = 'OTHER'.freeze,

      # Pager number.
      PAGER = 'PAGER'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
