# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The list of plans with details.
  class PlanCollection < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of plans.
    # @return [Array[BillingPlan]]
    attr_accessor :plans

    # The total number of items.
    # @return [Integer]
    attr_accessor :total_items

    # The total number of pages.
    # @return [Integer]
    attr_accessor :total_pages

    # An array of request-related [HATEOAS
    # links](/docs/api/reference/api-responses/#hateoas-links).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['plans'] = 'plans'
      @_hash['total_items'] = 'total_items'
      @_hash['total_pages'] = 'total_pages'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        plans
        total_items
        total_pages
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(plans: SKIP, total_items: SKIP, total_pages: SKIP,
                   links: SKIP)
      @plans = plans unless plans == SKIP
      @total_items = total_items unless total_items == SKIP
      @total_pages = total_pages unless total_pages == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      plans = nil
      unless hash['plans'].nil?
        plans = []
        hash['plans'].each do |structure|
          plans << (BillingPlan.from_hash(structure) if structure)
        end
      end

      plans = SKIP unless hash.key?('plans')
      total_items = hash.key?('total_items') ? hash['total_items'] : SKIP
      total_pages = hash.key?('total_pages') ? hash['total_pages'] : SKIP
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      PlanCollection.new(plans: plans,
                         total_items: total_items,
                         total_pages: total_pages,
                         links: links)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} plans: #{@plans}, total_items: #{@total_items}, total_pages:"\
      " #{@total_pages}, links: #{@links}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} plans: #{@plans.inspect}, total_items: #{@total_items.inspect},"\
      " total_pages: #{@total_pages.inspect}, links: #{@links.inspect}>"
    end
  end
end
