# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The plan details.
  class PlanDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ID for the product.
    # @return [String]
    attr_accessor :product_id

    # The plan name.
    # @return [String]
    attr_accessor :name

    # The detailed description of the plan.
    # @return [String]
    attr_accessor :description

    # An array of billing cycles for trial billing and regular billing. A plan
    # can have at most two trial cycles and only one regular cycle.
    # @return [Array[SubscriptionBillingCycle]]
    attr_accessor :billing_cycles

    # The payment preferences for a subscription.
    # @return [PaymentPreferences]
    attr_accessor :payment_preferences

    # The merchant preferences for a subscription.
    # @return [MerchantPreferences]
    attr_accessor :merchant_preferences

    # The tax details.
    # @return [Taxes]
    attr_accessor :taxes

    # Indicates whether you can subscribe to this plan by providing a quantity
    # for the goods or service.
    # @return [TrueClass | FalseClass]
    attr_accessor :quantity_supported

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_id'] = 'product_id'
      @_hash['name'] = 'name'
      @_hash['description'] = 'description'
      @_hash['billing_cycles'] = 'billing_cycles'
      @_hash['payment_preferences'] = 'payment_preferences'
      @_hash['merchant_preferences'] = 'merchant_preferences'
      @_hash['taxes'] = 'taxes'
      @_hash['quantity_supported'] = 'quantity_supported'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        product_id
        name
        description
        billing_cycles
        payment_preferences
        merchant_preferences
        taxes
        quantity_supported
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(product_id: SKIP, name: SKIP, description: SKIP,
                   billing_cycles: SKIP, payment_preferences: SKIP,
                   merchant_preferences: SKIP, taxes: SKIP,
                   quantity_supported: false)
      @product_id = product_id unless product_id == SKIP
      @name = name unless name == SKIP
      @description = description unless description == SKIP
      @billing_cycles = billing_cycles unless billing_cycles == SKIP
      @payment_preferences = payment_preferences unless payment_preferences == SKIP
      @merchant_preferences = merchant_preferences unless merchant_preferences == SKIP
      @taxes = taxes unless taxes == SKIP
      @quantity_supported = quantity_supported unless quantity_supported == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_id = hash.key?('product_id') ? hash['product_id'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      # Parameter is an array, so we need to iterate through it
      billing_cycles = nil
      unless hash['billing_cycles'].nil?
        billing_cycles = []
        hash['billing_cycles'].each do |structure|
          billing_cycles << (SubscriptionBillingCycle.from_hash(structure) if structure)
        end
      end

      billing_cycles = SKIP unless hash.key?('billing_cycles')
      payment_preferences = PaymentPreferences.from_hash(hash['payment_preferences']) if
        hash['payment_preferences']
      merchant_preferences = MerchantPreferences.from_hash(hash['merchant_preferences']) if
        hash['merchant_preferences']
      taxes = Taxes.from_hash(hash['taxes']) if hash['taxes']
      quantity_supported = hash['quantity_supported'] ||= false

      # Create object from extracted values.
      PlanDetails.new(product_id: product_id,
                      name: name,
                      description: description,
                      billing_cycles: billing_cycles,
                      payment_preferences: payment_preferences,
                      merchant_preferences: merchant_preferences,
                      taxes: taxes,
                      quantity_supported: quantity_supported)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} product_id: #{@product_id}, name: #{@name}, description: #{@description},"\
      " billing_cycles: #{@billing_cycles}, payment_preferences: #{@payment_preferences},"\
      " merchant_preferences: #{@merchant_preferences}, taxes: #{@taxes}, quantity_supported:"\
      " #{@quantity_supported}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} product_id: #{@product_id.inspect}, name: #{@name.inspect}, description:"\
      " #{@description.inspect}, billing_cycles: #{@billing_cycles.inspect}, payment_preferences:"\
      " #{@payment_preferences.inspect}, merchant_preferences: #{@merchant_preferences.inspect},"\
      " taxes: #{@taxes.inspect}, quantity_supported: #{@quantity_supported.inspect}>"
    end
  end
end
