# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The initial state of the plan. Allowed input values are CREATED and ACTIVE.
  class PlanRequestStatus
    PLAN_REQUEST_STATUS = [
      # The plan was created. You cannot create subscriptions for a plan in this
      # state.
      CREATED = 'CREATED'.freeze,

      # The plan is inactive.
      INACTIVE = 'INACTIVE'.freeze,

      # The plan is active. You can only create subscriptions for a plan in this
      # state.
      ACTIVE = 'ACTIVE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
