# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The pricing tier details.
  class PricingTier < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The starting quantity for the tier.
    # @return [String]
    attr_accessor :starting_quantity

    # The ending quantity for the tier. Optional for the last tier.
    # @return [String]
    attr_accessor :ending_quantity

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['starting_quantity'] = 'starting_quantity'
      @_hash['ending_quantity'] = 'ending_quantity'
      @_hash['amount'] = 'amount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ending_quantity
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(starting_quantity:, amount:, ending_quantity: SKIP)
      @starting_quantity = starting_quantity
      @ending_quantity = ending_quantity unless ending_quantity == SKIP
      @amount = amount
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      starting_quantity =
        hash.key?('starting_quantity') ? hash['starting_quantity'] : nil
      amount = Money.from_hash(hash['amount']) if hash['amount']
      ending_quantity =
        hash.key?('ending_quantity') ? hash['ending_quantity'] : SKIP

      # Create object from extracted values.
      PricingTier.new(starting_quantity: starting_quantity,
                      amount: amount,
                      ending_quantity: ending_quantity)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} starting_quantity: #{@starting_quantity}, ending_quantity:"\
      " #{@ending_quantity}, amount: #{@amount}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} starting_quantity: #{@starting_quantity.inspect}, ending_quantity:"\
      " #{@ending_quantity.inspect}, amount: #{@amount.inspect}>"
    end
  end
end
