# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The pricing model for the billing cycle.
  class PricingModel
    PRICING_MODEL = [
      # A fixed pricing scheme where the customer is charged a fixed amount.
      FIXED = 'FIXED'.freeze,

      # A variable pricing scheme where the customer is charged a variable
      # amount.
      VARIABLE = 'VARIABLE'.freeze,

      # A auto-reload pricing scheme where the customer is charged a fixed
      # amount for reload.
      AUTO_RELOAD = 'AUTO_RELOAD'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = FIXED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'fixed' then FIXED
      when 'variable' then VARIABLE
      when 'auto_reload' then AUTO_RELOAD
      else
        default_value
      end
    end
  end
end
