# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Processor response code for the non-PayPal payment processor errors.
  class ProcessorResponseCode
    PROCESSOR_RESPONSE_CODE = [
      # APPROVED.
      RESPONSE_0000 = '0000'.freeze,

      # CVV2_FAILURE_POSSIBLE_RETRY_WITH_CVV.
      RESPONSE_00N7 = '00N7'.freeze,

      # REFERRAL.
      RESPONSE_0100 = '0100'.freeze,

      # ACCOUNT_NOT_FOUND.
      RESPONSE_0390 = '0390'.freeze,

      # DO_NOT_HONOR.
      RESPONSE_0500 = '0500'.freeze,

      # UNAUTHORIZED_TRANSACTION.
      RESPONSE_0580 = '0580'.freeze,

      # BAD_RESPONSE_REVERSAL_REQUIRED.
      RESPONSE_0800 = '0800'.freeze,

      # CRYPTOGRAPHIC_FAILURE.
      RESPONSE_0880 = '0880'.freeze,

      # UNACCEPTABLE_PIN.
      RESPONSE_0890 = '0890'.freeze,

      # SYSTEM_MALFUNCTION.
      RESPONSE_0960 = '0960'.freeze,

      # CANCELLED_PAYMENT.
      RESPONSE_0R00 = '0R00'.freeze,

      # PARTIAL_AUTHORIZATION.
      RESPONSE_1000 = '1000'.freeze,

      # ISSUER_REJECTED.
      RESPONSE_10BR = '10BR'.freeze,

      # INVALID_DATA_FORMAT.
      RESPONSE_1300 = '1300'.freeze,

      # INVALID_AMOUNT.
      RESPONSE_1310 = '1310'.freeze,

      # INVALID_TRANSACTION_CARD_ISSUER_ACQUIRER.
      RESPONSE_1312 = '1312'.freeze,

      # INVALID_CAPTURE_DATE.
      RESPONSE_1317 = '1317'.freeze,

      # INVALID_CURRENCY_CODE.
      RESPONSE_1320 = '1320'.freeze,

      # INVALID_ACCOUNT.
      RESPONSE_1330 = '1330'.freeze,

      # INVALID_ACCOUNT_RECURRING.
      RESPONSE_1335 = '1335'.freeze,

      # INVALID_TERMINAL.
      RESPONSE_1340 = '1340'.freeze,

      # INVALID_MERCHANT.
      RESPONSE_1350 = '1350'.freeze,

      # RESTRICTED_OR_INACTIVE_ACCOUNT.
      RESPONSE_1352 = '1352'.freeze,

      # BAD_PROCESSING_CODE.
      RESPONSE_1360 = '1360'.freeze,

      # INVALID_MCC.
      RESPONSE_1370 = '1370'.freeze,

      # INVALID_EXPIRATION.
      RESPONSE_1380 = '1380'.freeze,

      # INVALID_CARD_VERIFICATION_VALUE.
      RESPONSE_1382 = '1382'.freeze,

      # INVALID_LIFE_CYCLE_OF_TRANSACTION.
      RESPONSE_1384 = '1384'.freeze,

      # INVALID_ORDER.
      RESPONSE_1390 = '1390'.freeze,

      # TRANSACTION_CANNOT_BE_COMPLETED.
      RESPONSE_1393 = '1393'.freeze,

      # GENERIC_DECLINE.
      RESPONSE_5100 = '5100'.freeze,

      # CVV2_FAILURE.
      RESPONSE_5110 = '5110'.freeze,

      # INSUFFICIENT_FUNDS.
      RESPONSE_5120 = '5120'.freeze,

      # INVALID_PIN.
      RESPONSE_5130 = '5130'.freeze,

      # DECLINED_PIN_TRY_EXCEEDED.
      RESPONSE_5135 = '5135'.freeze,

      # CARD_CLOSED.
      RESPONSE_5140 = '5140'.freeze,

      # PICKUP_CARD_SPECIAL_CONDITIONS. Try using another card. Do not retry the
      # same card.
      RESPONSE_5150 = '5150'.freeze,

      # UNAUTHORIZED_USER.
      RESPONSE_5160 = '5160'.freeze,

      # AVS_FAILURE.
      RESPONSE_5170 = '5170'.freeze,

      # INVALID_OR_RESTRICTED_CARD. Try using another card. Do not retry the
      # same card.
      RESPONSE_5180 = '5180'.freeze,

      # SOFT_AVS.
      RESPONSE_5190 = '5190'.freeze,

      # DUPLICATE_TRANSACTION.
      RESPONSE_5200 = '5200'.freeze,

      # INVALID_TRANSACTION.
      RESPONSE_5210 = '5210'.freeze,

      # EXPIRED_CARD.
      RESPONSE_5400 = '5400'.freeze,

      # INCORRECT_PIN_REENTER.
      RESPONSE_5500 = '5500'.freeze,

      # DECLINED_SCA_REQUIRED.
      RESPONSE_5650 = '5650'.freeze,

      # TRANSACTION_NOT_PERMITTED. Outside of scope of accepted business.
      RESPONSE_5700 = '5700'.freeze,

      # TX_ATTEMPTS_EXCEED_LIMIT.
      RESPONSE_5710 = '5710'.freeze,

      # REVERSAL_REJECTED.
      RESPONSE_5800 = '5800'.freeze,

      # INVALID_ISSUE.
      RESPONSE_5900 = '5900'.freeze,

      # ISSUER_NOT_AVAILABLE_NOT_RETRIABLE.
      RESPONSE_5910 = '5910'.freeze,

      # ISSUER_NOT_AVAILABLE_RETRIABLE.
      RESPONSE_5920 = '5920'.freeze,

      # CARD_NOT_ACTIVATED.
      RESPONSE_5930 = '5930'.freeze,

      # DECLINED_DUE_TO_UPDATED_ACCOUNT. External decline as an updated card has
      # been issued.
      RESPONSE_5950 = '5950'.freeze,

      # ACCOUNT_NOT_ON_FILE.
      RESPONSE_6300 = '6300'.freeze,

      # APPROVED_NON_CAPTURE.
      RESPONSE_7600 = '7600'.freeze,

      # ERROR_3DS.
      RESPONSE_7700 = '7700'.freeze,

      # AUTHENTICATION_FAILED.
      RESPONSE_7710 = '7710'.freeze,

      # BIN_ERROR.
      RESPONSE_7800 = '7800'.freeze,

      # PIN_ERROR.
      RESPONSE_7900 = '7900'.freeze,

      # PROCESSOR_SYSTEM_ERROR.
      RESPONSE_8000 = '8000'.freeze,

      # HOST_KEY_ERROR.
      RESPONSE_8010 = '8010'.freeze,

      # CONFIGURATION_ERROR.
      RESPONSE_8020 = '8020'.freeze,

      # UNSUPPORTED_OPERATION.
      RESPONSE_8030 = '8030'.freeze,

      # FATAL_COMMUNICATION_ERROR.
      RESPONSE_8100 = '8100'.freeze,

      # RETRIABLE_COMMUNICATION_ERROR.
      RESPONSE_8110 = '8110'.freeze,

      # SYSTEM_UNAVAILABLE.
      RESPONSE_8220 = '8220'.freeze,

      # DECLINED_PLEASE_RETRY. Retry.
      RESPONSE_9100 = '9100'.freeze,

      # SUSPECTED_FRAUD. Try using another card. Do not retry the same card.
      RESPONSE_9500 = '9500'.freeze,

      # SECURITY_VIOLATION.
      RESPONSE_9510 = '9510'.freeze,

      # LOST_OR_STOLEN. Try using another card. Do not retry the same card.
      RESPONSE_9520 = '9520'.freeze,

      # HOLD_CALL_CENTER. The merchant must call the number on the back of the
      # card. POS scenario.
      RESPONSE_9530 = '9530'.freeze,

      # REFUSED_CARD.
      RESPONSE_9540 = '9540'.freeze,

      # UNRECOGNIZED_RESPONSE_CODE.
      RESPONSE_9600 = '9600'.freeze,

      # CONTINGENCIES_NOT_RESOLVED.
      RESPONSE_PCNR = 'PCNR'.freeze,

      # CVV_FAILURE.
      RESPONSE_PCVV = 'PCVV'.freeze,

      # ACCOUNT_CLOSED. A previously open account is now closed
      RESPONSE_PP06 = 'PP06'.freeze,

      # REATTEMPT_NOT_PERMITTED.
      RESPONSE_PPRN = 'PPRN'.freeze,

      # BILLING_ADDRESS.
      RESPONSE_PPAD = 'PPAD'.freeze,

      # ACCOUNT_BLOCKED_BY_ISSUER.
      RESPONSE_PPAB = 'PPAB'.freeze,

      # AMEX_DISABLED.
      RESPONSE_PPAE = 'PPAE'.freeze,

      # ADULT_GAMING_UNSUPPORTED.
      RESPONSE_PPAG = 'PPAG'.freeze,

      # AMOUNT_INCOMPATIBLE.
      RESPONSE_PPAI = 'PPAI'.freeze,

      # AUTH_RESULT.
      RESPONSE_PPAR = 'PPAR'.freeze,

      # MCC_CODE.
      RESPONSE_PPAU = 'PPAU'.freeze,

      # ARC_AVS.
      RESPONSE_PPAV = 'PPAV'.freeze,

      # AMOUNT_EXCEEDED.
      RESPONSE_PPAX = 'PPAX'.freeze,

      # BAD_GAMING.
      RESPONSE_PPBG = 'PPBG'.freeze,

      # ARC_CVV.
      RESPONSE_PPC2 = 'PPC2'.freeze,

      # CE_REGISTRATION_INCOMPLETE.
      RESPONSE_PPCE = 'PPCE'.freeze,

      # COUNTRY.
      RESPONSE_PPCO = 'PPCO'.freeze,

      # CREDIT_ERROR.
      RESPONSE_PPCR = 'PPCR'.freeze,

      # CARD_TYPE_UNSUPPORTED.
      RESPONSE_PPCT = 'PPCT'.freeze,

      # CURRENCY_USED_INVALID.
      RESPONSE_PPCU = 'PPCU'.freeze,

      # SECURE_ERROR_3DS.
      RESPONSE_PPD3 = 'PPD3'.freeze,

      # DCC_UNSUPPORTED.
      RESPONSE_PPDC = 'PPDC'.freeze,

      # DINERS_REJECT.
      RESPONSE_PPDI = 'PPDI'.freeze,

      # AUTH_MESSAGE.
      RESPONSE_PPDV = 'PPDV'.freeze,

      # DECLINE_THRESHOLD_BREACH.
      RESPONSE_PPDT = 'PPDT'.freeze,

      # EXPIRED_FUNDING_INSTRUMENT.
      RESPONSE_PPEF = 'PPEF'.freeze,

      # EXCEEDS_FREQUENCY_LIMIT.
      RESPONSE_PPEL = 'PPEL'.freeze,

      # INTERNAL_SYSTEM_ERROR.
      RESPONSE_PPER = 'PPER'.freeze,

      # EXPIRY_DATE.
      RESPONSE_PPEX = 'PPEX'.freeze,

      # FUNDING_SOURCE_ALREADY_EXISTS.
      RESPONSE_PPFE = 'PPFE'.freeze,

      # INVALID_FUNDING_INSTRUMENT.
      RESPONSE_PPFI = 'PPFI'.freeze,

      # RESTRICTED_FUNDING_INSTRUMENT.
      RESPONSE_PPFR = 'PPFR'.freeze,

      # FIELD_VALIDATION_FAILED.
      RESPONSE_PPFV = 'PPFV'.freeze,

      # GAMING_REFUND_ERROR.
      RESPONSE_PPGR = 'PPGR'.freeze,

      # H1_ERROR.
      RESPONSE_PPH1 = 'PPH1'.freeze,

      # IDEMPOTENCY_FAILURE.
      RESPONSE_PPIF = 'PPIF'.freeze,

      # INVALID_INPUT_FAILURE.
      RESPONSE_PPII = 'PPII'.freeze,

      # ID_MISMATCH.
      RESPONSE_PPIM = 'PPIM'.freeze,

      # INVALID_TRACE_ID.
      RESPONSE_PPIT = 'PPIT'.freeze,

      # LATE_REVERSAL.
      RESPONSE_PPLR = 'PPLR'.freeze,

      # LARGE_STATUS_CODE.
      RESPONSE_PPLS = 'PPLS'.freeze,

      # MISSING_BUSINESS_RULE_OR_DATA.
      RESPONSE_PPMB = 'PPMB'.freeze,

      # BLOCKED_Mastercard.
      RESPONSE_PPMC = 'PPMC'.freeze,

      # DEPRECATED The PPMD value has been deprecated.
      RESPONSE_PPMD = 'PPMD'.freeze,

      # NOT_SUPPORTED_NRC.
      RESPONSE_PPNC = 'PPNC'.freeze,

      # EXCEEDS_NETWORK_FREQUENCY_LIMIT.
      RESPONSE_PPNL = 'PPNL'.freeze,

      # NO_MID_FOUND.
      RESPONSE_PPNM = 'PPNM'.freeze,

      # NETWORK_ERROR.
      RESPONSE_PPNT = 'PPNT'.freeze,

      # NO_PHONE_FOR_DCC_TRANSACTION.
      RESPONSE_PPPH = 'PPPH'.freeze,

      # INVALID_PRODUCT.
      RESPONSE_PPPI = 'PPPI'.freeze,

      # INVALID_PAYMENT_METHOD.
      RESPONSE_PPPM = 'PPPM'.freeze,

      # QUASI_CASH_UNSUPPORTED.
      RESPONSE_PPQC = 'PPQC'.freeze,

      # UNSUPPORT_REFUND_ON_PENDING_BC.
      RESPONSE_PPRE = 'PPRE'.freeze,

      # INVALID_PARENT_TRANSACTION_STATUS.
      RESPONSE_PPRF = 'PPRF'.freeze,

      # MERCHANT_NOT_REGISTERED.
      RESPONSE_PPRR = 'PPRR'.freeze,

      # BANKAUTH_ROW_MISMATCH.
      RESPONSE_PPS0 = 'PPS0'.freeze,

      # BANKAUTH_ROW_SETTLED.
      RESPONSE_PPS1 = 'PPS1'.freeze,

      # BANKAUTH_ROW_VOIDED.
      RESPONSE_PPS2 = 'PPS2'.freeze,

      # BANKAUTH_EXPIRED.
      RESPONSE_PPS3 = 'PPS3'.freeze,

      # CURRENCY_MISMATCH.
      RESPONSE_PPS4 = 'PPS4'.freeze,

      # CREDITCARD_MISMATCH.
      RESPONSE_PPS5 = 'PPS5'.freeze,

      # AMOUNT_MISMATCH.
      RESPONSE_PPS6 = 'PPS6'.freeze,

      # ARC_SCORE.
      RESPONSE_PPSC = 'PPSC'.freeze,

      # STATUS_DESCRIPTION.
      RESPONSE_PPSD = 'PPSD'.freeze,

      # AMEX_DENIED.
      RESPONSE_PPSE = 'PPSE'.freeze,

      # VERIFICATION_TOKEN_EXPIRED.
      RESPONSE_PPTE = 'PPTE'.freeze,

      # INVALID_TRACE_REFERENCE.
      RESPONSE_PPTF = 'PPTF'.freeze,

      # INVALID_TRANSACTION_ID.
      RESPONSE_PPTI = 'PPTI'.freeze,

      # VERIFICATION_TOKEN_REVOKED.
      RESPONSE_PPTR = 'PPTR'.freeze,

      # TRANSACTION_TYPE_UNSUPPORTED.
      RESPONSE_PPTT = 'PPTT'.freeze,

      # INVALID_VERIFICATION_TOKEN.
      RESPONSE_PPTV = 'PPTV'.freeze,

      # USER_NOT_AUTHORIZED.
      RESPONSE_PPUA = 'PPUA'.freeze,

      # CURRENCY_CODE_UNSUPPORTED.
      RESPONSE_PPUC = 'PPUC'.freeze,

      # UNSUPPORT_ENTITY.
      RESPONSE_PPUE = 'PPUE'.freeze,

      # UNSUPPORT_INSTALLMENT.
      RESPONSE_PPUI = 'PPUI'.freeze,

      # UNSUPPORT_POS_FLAG.
      RESPONSE_PPUP = 'PPUP'.freeze,

      # UNSUPPORTED_REVERSAL.
      RESPONSE_PPUR = 'PPUR'.freeze,

      # VALIDATE_CURRENCY.
      RESPONSE_PPVC = 'PPVC'.freeze,

      # VALIDATION_ERROR.
      RESPONSE_PPVE = 'PPVE'.freeze,

      # VIRTUAL_TERMINAL_UNSUPPORTED.
      RESPONSE_PPVT = 'PPVT'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = RESPONSE_0000)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'response_0000' then RESPONSE_0000
      when 'response_00n7' then RESPONSE_00N7
      when 'response_0100' then RESPONSE_0100
      when 'response_0390' then RESPONSE_0390
      when 'response_0500' then RESPONSE_0500
      when 'response_0580' then RESPONSE_0580
      when 'response_0800' then RESPONSE_0800
      when 'response_0880' then RESPONSE_0880
      when 'response_0890' then RESPONSE_0890
      when 'response_0960' then RESPONSE_0960
      when 'response_0r00' then RESPONSE_0R00
      when 'response_1000' then RESPONSE_1000
      when 'response_10br' then RESPONSE_10BR
      when 'response_1300' then RESPONSE_1300
      when 'response_1310' then RESPONSE_1310
      when 'response_1312' then RESPONSE_1312
      when 'response_1317' then RESPONSE_1317
      when 'response_1320' then RESPONSE_1320
      when 'response_1330' then RESPONSE_1330
      when 'response_1335' then RESPONSE_1335
      when 'response_1340' then RESPONSE_1340
      when 'response_1350' then RESPONSE_1350
      when 'response_1352' then RESPONSE_1352
      when 'response_1360' then RESPONSE_1360
      when 'response_1370' then RESPONSE_1370
      when 'response_1380' then RESPONSE_1380
      when 'response_1382' then RESPONSE_1382
      when 'response_1384' then RESPONSE_1384
      when 'response_1390' then RESPONSE_1390
      when 'response_1393' then RESPONSE_1393
      when 'response_5100' then RESPONSE_5100
      when 'response_5110' then RESPONSE_5110
      when 'response_5120' then RESPONSE_5120
      when 'response_5130' then RESPONSE_5130
      when 'response_5135' then RESPONSE_5135
      when 'response_5140' then RESPONSE_5140
      when 'response_5150' then RESPONSE_5150
      when 'response_5160' then RESPONSE_5160
      when 'response_5170' then RESPONSE_5170
      when 'response_5180' then RESPONSE_5180
      when 'response_5190' then RESPONSE_5190
      when 'response_5200' then RESPONSE_5200
      when 'response_5210' then RESPONSE_5210
      when 'response_5400' then RESPONSE_5400
      when 'response_5500' then RESPONSE_5500
      when 'response_5650' then RESPONSE_5650
      when 'response_5700' then RESPONSE_5700
      when 'response_5710' then RESPONSE_5710
      when 'response_5800' then RESPONSE_5800
      when 'response_5900' then RESPONSE_5900
      when 'response_5910' then RESPONSE_5910
      when 'response_5920' then RESPONSE_5920
      when 'response_5930' then RESPONSE_5930
      when 'response_5950' then RESPONSE_5950
      when 'response_6300' then RESPONSE_6300
      when 'response_7600' then RESPONSE_7600
      when 'response_7700' then RESPONSE_7700
      when 'response_7710' then RESPONSE_7710
      when 'response_7800' then RESPONSE_7800
      when 'response_7900' then RESPONSE_7900
      when 'response_8000' then RESPONSE_8000
      when 'response_8010' then RESPONSE_8010
      when 'response_8020' then RESPONSE_8020
      when 'response_8030' then RESPONSE_8030
      when 'response_8100' then RESPONSE_8100
      when 'response_8110' then RESPONSE_8110
      when 'response_8220' then RESPONSE_8220
      when 'response_9100' then RESPONSE_9100
      when 'response_9500' then RESPONSE_9500
      when 'response_9510' then RESPONSE_9510
      when 'response_9520' then RESPONSE_9520
      when 'response_9530' then RESPONSE_9530
      when 'response_9540' then RESPONSE_9540
      when 'response_9600' then RESPONSE_9600
      when 'response_pcnr' then RESPONSE_PCNR
      when 'response_pcvv' then RESPONSE_PCVV
      when 'response_pp06' then RESPONSE_PP06
      when 'response_pprn' then RESPONSE_PPRN
      when 'response_ppad' then RESPONSE_PPAD
      when 'response_ppab' then RESPONSE_PPAB
      when 'response_ppae' then RESPONSE_PPAE
      when 'response_ppag' then RESPONSE_PPAG
      when 'response_ppai' then RESPONSE_PPAI
      when 'response_ppar' then RESPONSE_PPAR
      when 'response_ppau' then RESPONSE_PPAU
      when 'response_ppav' then RESPONSE_PPAV
      when 'response_ppax' then RESPONSE_PPAX
      when 'response_ppbg' then RESPONSE_PPBG
      when 'response_ppc2' then RESPONSE_PPC2
      when 'response_ppce' then RESPONSE_PPCE
      when 'response_ppco' then RESPONSE_PPCO
      when 'response_ppcr' then RESPONSE_PPCR
      when 'response_ppct' then RESPONSE_PPCT
      when 'response_ppcu' then RESPONSE_PPCU
      when 'response_ppd3' then RESPONSE_PPD3
      when 'response_ppdc' then RESPONSE_PPDC
      when 'response_ppdi' then RESPONSE_PPDI
      when 'response_ppdv' then RESPONSE_PPDV
      when 'response_ppdt' then RESPONSE_PPDT
      when 'response_ppef' then RESPONSE_PPEF
      when 'response_ppel' then RESPONSE_PPEL
      when 'response_pper' then RESPONSE_PPER
      when 'response_ppex' then RESPONSE_PPEX
      when 'response_ppfe' then RESPONSE_PPFE
      when 'response_ppfi' then RESPONSE_PPFI
      when 'response_ppfr' then RESPONSE_PPFR
      when 'response_ppfv' then RESPONSE_PPFV
      when 'response_ppgr' then RESPONSE_PPGR
      when 'response_pph1' then RESPONSE_PPH1
      when 'response_ppif' then RESPONSE_PPIF
      when 'response_ppii' then RESPONSE_PPII
      when 'response_ppim' then RESPONSE_PPIM
      when 'response_ppit' then RESPONSE_PPIT
      when 'response_pplr' then RESPONSE_PPLR
      when 'response_ppls' then RESPONSE_PPLS
      when 'response_ppmb' then RESPONSE_PPMB
      when 'response_ppmc' then RESPONSE_PPMC
      when 'response_ppmd' then RESPONSE_PPMD
      when 'response_ppnc' then RESPONSE_PPNC
      when 'response_ppnl' then RESPONSE_PPNL
      when 'response_ppnm' then RESPONSE_PPNM
      when 'response_ppnt' then RESPONSE_PPNT
      when 'response_ppph' then RESPONSE_PPPH
      when 'response_pppi' then RESPONSE_PPPI
      when 'response_pppm' then RESPONSE_PPPM
      when 'response_ppqc' then RESPONSE_PPQC
      when 'response_ppre' then RESPONSE_PPRE
      when 'response_pprf' then RESPONSE_PPRF
      when 'response_pprr' then RESPONSE_PPRR
      when 'response_pps0' then RESPONSE_PPS0
      when 'response_pps1' then RESPONSE_PPS1
      when 'response_pps2' then RESPONSE_PPS2
      when 'response_pps3' then RESPONSE_PPS3
      when 'response_pps4' then RESPONSE_PPS4
      when 'response_pps5' then RESPONSE_PPS5
      when 'response_pps6' then RESPONSE_PPS6
      when 'response_ppsc' then RESPONSE_PPSC
      when 'response_ppsd' then RESPONSE_PPSD
      when 'response_ppse' then RESPONSE_PPSE
      when 'response_ppte' then RESPONSE_PPTE
      when 'response_pptf' then RESPONSE_PPTF
      when 'response_ppti' then RESPONSE_PPTI
      when 'response_pptr' then RESPONSE_PPTR
      when 'response_pptt' then RESPONSE_PPTT
      when 'response_pptv' then RESPONSE_PPTV
      when 'response_ppua' then RESPONSE_PPUA
      when 'response_ppuc' then RESPONSE_PPUC
      when 'response_ppue' then RESPONSE_PPUE
      when 'response_ppui' then RESPONSE_PPUI
      when 'response_ppup' then RESPONSE_PPUP
      when 'response_ppur' then RESPONSE_PPUR
      when 'response_ppvc' then RESPONSE_PPVC
      when 'response_ppve' then RESPONSE_PPVE
      when 'response_ppvt' then RESPONSE_PPVT
      else
        default_value
      end
    end
  end
end
