# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The status of the refund.
  class RefundStatus
    REFUND_STATUS = [
      # The refund was cancelled.
      CANCELLED = 'CANCELLED'.freeze,

      # The refund could not be processed.
      FAILED = 'FAILED'.freeze,

      # The refund is pending. For more information, see status_details.reason.
      PENDING = 'PENDING'.freeze,

      # The funds for this transaction were debited to the customer's account.
      COMPLETED = 'COMPLETED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
