# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Merchant preference on how the buyer can navigate back to merchant website
  # post approving the transaction on the Venmo App.
  class ReturnFlow
    RETURN_FLOW = [
      # After payment approval in the PayPal App, buyer will automatically be
      # redirected to the merchant website.
      AUTO = 'AUTO'.freeze,

      # After payment approval in the PayPal App, buyer will be asked to
      # manually navigate back to the merchant website where they started the
      # transaction from. The buyer is shown a message like 'Return to Merchant'
      # to return to the source where the transaction actually started.
      MANUAL = 'MANUAL'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = AUTO)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'auto' then AUTO
      when 'manual' then MANUAL
      else
        default_value
      end
    end
  end
end
