# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The search response information.
  class SearchResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of transaction detail objects.
    # @return [Array[TransactionDetails]]
    attr_accessor :transaction_details

    # The merchant account number.
    # @return [String]
    attr_accessor :account_number

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :start_date

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :end_date

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :last_refreshed_datetime

    # A zero-relative index of transactions.
    # @return [Integer]
    attr_accessor :page

    # The total number of transactions as an integer beginning with the
    # specified `page` in the full result and not just in this response.
    # @return [Integer]
    attr_accessor :total_items

    # The total number of pages, as an `integer`, when the `total_items` is
    # divided into pages of the specified `page_size`.
    # @return [Integer]
    attr_accessor :total_pages

    # An array of request-related [HATEOAS
    # links](/api/rest/responses/#hateoas-links).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transaction_details'] = 'transaction_details'
      @_hash['account_number'] = 'account_number'
      @_hash['start_date'] = 'start_date'
      @_hash['end_date'] = 'end_date'
      @_hash['last_refreshed_datetime'] = 'last_refreshed_datetime'
      @_hash['page'] = 'page'
      @_hash['total_items'] = 'total_items'
      @_hash['total_pages'] = 'total_pages'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        transaction_details
        account_number
        start_date
        end_date
        last_refreshed_datetime
        page
        total_items
        total_pages
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transaction_details: SKIP, account_number: SKIP,
                   start_date: SKIP, end_date: SKIP,
                   last_refreshed_datetime: SKIP, page: SKIP, total_items: SKIP,
                   total_pages: SKIP, links: SKIP)
      @transaction_details = transaction_details unless transaction_details == SKIP
      @account_number = account_number unless account_number == SKIP
      @start_date = start_date unless start_date == SKIP
      @end_date = end_date unless end_date == SKIP
      @last_refreshed_datetime = last_refreshed_datetime unless last_refreshed_datetime == SKIP
      @page = page unless page == SKIP
      @total_items = total_items unless total_items == SKIP
      @total_pages = total_pages unless total_pages == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      transaction_details = nil
      unless hash['transaction_details'].nil?
        transaction_details = []
        hash['transaction_details'].each do |structure|
          transaction_details << (TransactionDetails.from_hash(structure) if structure)
        end
      end

      transaction_details = SKIP unless hash.key?('transaction_details')
      account_number =
        hash.key?('account_number') ? hash['account_number'] : SKIP
      start_date = hash.key?('start_date') ? hash['start_date'] : SKIP
      end_date = hash.key?('end_date') ? hash['end_date'] : SKIP
      last_refreshed_datetime =
        hash.key?('last_refreshed_datetime') ? hash['last_refreshed_datetime'] : SKIP
      page = hash.key?('page') ? hash['page'] : SKIP
      total_items = hash.key?('total_items') ? hash['total_items'] : SKIP
      total_pages = hash.key?('total_pages') ? hash['total_pages'] : SKIP
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      SearchResponse.new(transaction_details: transaction_details,
                         account_number: account_number,
                         start_date: start_date,
                         end_date: end_date,
                         last_refreshed_datetime: last_refreshed_datetime,
                         page: page,
                         total_items: total_items,
                         total_pages: total_pages,
                         links: links)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_details: #{@transaction_details}, account_number:"\
      " #{@account_number}, start_date: #{@start_date}, end_date: #{@end_date},"\
      " last_refreshed_datetime: #{@last_refreshed_datetime}, page: #{@page}, total_items:"\
      " #{@total_items}, total_pages: #{@total_pages}, links: #{@links}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_details: #{@transaction_details.inspect}, account_number:"\
      " #{@account_number.inspect}, start_date: #{@start_date.inspect}, end_date:"\
      " #{@end_date.inspect}, last_refreshed_datetime: #{@last_refreshed_datetime.inspect}, page:"\
      " #{@page.inspect}, total_items: #{@total_items.inspect}, total_pages:"\
      " #{@total_pages.inspect}, links: #{@links.inspect}>"
    end
  end
end
