# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The action to take on the subscription if the initial payment for the setup
  # fails.
  class SetupFeeFailureAction
    SETUP_FEE_FAILURE_ACTION = [
      # Continues the subscription if the initial payment for the setup fails.
      CONTINUE = 'CONTINUE'.freeze,

      # Cancels the subscription if the initial payment for the setup fails.
      CANCEL = 'CANCEL'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
