# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The carrier for the shipment. Some carriers have a global version as well as
  # local subsidiaries. The subsidiaries are repeated over many countries and
  # might also have an entry in the global list. Choose the carrier for your
  # country. If the carrier is not available for your country, choose the global
  # version of the carrier. If your carrier name is not in the list, set
  # `carrier` to `OTHER` and set carrier name in `carrier_name_other`. For
  # allowed values, see Carriers.
  class ShipmentCarrier
    SHIPMENT_CARRIER = [
      # DPD Russia.
      DPD_RU = 'DPD_RU'.freeze,

      # Bulgarian Posts.
      BG_BULGARIAN_POST = 'BG_BULGARIAN_POST'.freeze,

      # Koreapost (www.koreapost.go.kr).
      KR_KOREA_POST = 'KR_KOREA_POST'.freeze,

      # Courier IT.
      ZA_COURIERIT = 'ZA_COURIERIT'.freeze,

      # DPD France (formerly exapaq).
      FR_EXAPAQ = 'FR_EXAPAQ'.freeze,

      # Emirates Post.
      ARE_EMIRATES_POST = 'ARE_EMIRATES_POST'.freeze,

      # GAC.
      GAC = 'GAC'.freeze,

      # Geis CZ.
      GEIS = 'GEIS'.freeze,

      # SF Express.
      SF_EX = 'SF_EX'.freeze,

      # Pago Logistics.
      PAGO = 'PAGO'.freeze,

      # MyHermes UK.
      MYHERMES = 'MYHERMES'.freeze,

      # Diamond Eurogistics Limited.
      DIAMOND_EUROGISTICS = 'DIAMOND_EUROGISTICS'.freeze,

      # Corporate Couriers.
      CORPORATECOURIERS_WEBHOOK = 'CORPORATECOURIERS_WEBHOOK'.freeze,

      # Bond courier.
      BOND = 'BOND'.freeze,

      # Omni Parcel.
      OMNIPARCEL = 'OMNIPARCEL'.freeze,

      # Slovenska pošta.
      SK_POSTA = 'SK_POSTA'.freeze,

      # purolator.
      PUROLATOR = 'PUROLATOR'.freeze,

      # Mena 360 (Fetchr).
      FETCHR_WEBHOOK = 'FETCHR_WEBHOOK'.freeze,

      # TDG – The Delivery Group.
      THEDELIVERYGROUP = 'THEDELIVERYGROUP'.freeze,

      # Cello Square.
      CELLO_SQUARE = 'CELLO_SQUARE'.freeze,

      # TONDA GLOBAL.
      TARRIVE = 'TARRIVE'.freeze,

      # MDS Collivery Pty (Ltd).
      COLLIVERY = 'COLLIVERY'.freeze,

      # Mainfreight.
      MAINFREIGHT = 'MAINFREIGHT'.freeze,

      # First Flight Couriers.
      IND_FIRSTFLIGHT = 'IND_FIRSTFLIGHT'.freeze,

      # ACS Worldwide Express.
      ACSWORLDWIDE = 'ACSWORLDWIDE'.freeze,

      # Amstan Logistics.
      AMSTAN = 'AMSTAN'.freeze,

      # OkayParcel.
      OKAYPARCEL = 'OKAYPARCEL'.freeze,

      # Envialia Reference.
      ENVIALIA_REFERENCE = 'ENVIALIA_REFERENCE'.freeze,

      # Seur Spain.
      SEUR_ES = 'SEUR_ES'.freeze,

      # Continental.
      CONTINENTAL = 'CONTINENTAL'.freeze,

      # FDSEXPRESS.
      FDSEXPRESS = 'FDSEXPRESS'.freeze,

      # Swiship UK.
      AMAZON_FBA_SWISHIP = 'AMAZON_FBA_SWISHIP'.freeze,

      # Wyngs.
      WYNGS = 'WYNGS'.freeze,

      # DHL Active Tracing.
      DHL_ACTIVE_TRACING = 'DHL_ACTIVE_TRACING'.freeze,

      # Zyllem.
      ZYLLEM = 'ZYLLEM'.freeze,

      # Ruston.
      RUSTON = 'RUSTON'.freeze,

      # Xpost.ph.
      XPOST = 'XPOST'.freeze,

      # correos Express (www.correos.es).
      CORREOS_ES = 'CORREOS_ES'.freeze,

      # DHL France (www.dhl.com).
      DHL_FR = 'DHL_FR'.freeze,

      # Pan-Asia International.
      PAN_ASIA = 'PAN_ASIA'.freeze,

      # BRT couriers Italy (www.brt.it).
      BRT_IT = 'BRT_IT'.freeze,

      # SRE Korea (www.srekorea.co.kr).
      SRE_KOREA = 'SRE_KOREA'.freeze,

      # Spee-Dee Delivery.
      SPEEDEE = 'SPEEDEE'.freeze,

      # TNT UK Limited (www.tnt.com).
      TNT_UK = 'TNT_UK'.freeze,

      # Venipak.
      VENIPAK = 'VENIPAK'.freeze,

      # SHREE NANDAN COURIER.
      SHREENANDANCOURIER = 'SHREENANDANCOURIER'.freeze,

      # Croshot.
      CROSHOT = 'CROSHOT'.freeze,

      # NIpost (www.nipost.gov.ng).
      NIPOST_NG = 'NIPOST_NG'.freeze,

      # ePost Global.
      EPST_GLBL = 'EPST_GLBL'.freeze,

      # Newgistics.
      NEWGISTICS = 'NEWGISTICS'.freeze,

      # Post of Slovenia.
      POST_SLOVENIA = 'POST_SLOVENIA'.freeze,

      # Jersey Post.
      JERSEY_POST = 'JERSEY_POST'.freeze,

      # Bombino Express Pvt.
      BOMBINOEXP = 'BOMBINOEXP'.freeze,

      # WMG Delivery.
      WMG = 'WMG'.freeze,

      # XQ Express.
      XQ_EXPRESS = 'XQ_EXPRESS'.freeze,

      # Furdeco.
      FURDECO = 'FURDECO'.freeze,

      # LHT Express.
      LHT_EXPRESS = 'LHT_EXPRESS'.freeze,

      # South African Post Office.
      SOUTH_AFRICAN_POST_OFFICE = 'SOUTH_AFRICAN_POST_OFFICE'.freeze,

      # SPOTON Logistics Pvt Ltd.
      SPOTON = 'SPOTON'.freeze,

      # Dimerco Express Group.
      DIMERCO = 'DIMERCO'.freeze,

      # cyprus post.
      CYPRUS_POST_CYP = 'CYPRUS_POST_CYP'.freeze,

      # AB Custom Group.
      ABCUSTOM = 'ABCUSTOM'.freeze,

      # deliverE.
      IND_DELIVREE = 'IND_DELIVREE'.freeze,

      # Best Express.
      CN_BESTEXPRESS = 'CN_BESTEXPRESS'.freeze,

      # DX (SFTP).
      DX_SFTP = 'DX_SFTP'.freeze,

      # PICK UPP.
      PICKUPP_MYS = 'PICKUPP_MYS'.freeze,

      # FMX.
      FMX = 'FMX'.freeze,

      # Hellmann Worldwide Logistics.
      HELLMANN = 'HELLMANN'.freeze,

      # Ship It Asia.
      SHIP_IT_ASIA = 'SHIP_IT_ASIA'.freeze,

      # Kerry eCommerce.
      KERRY_ECOMMERCE = 'KERRY_ECOMMERCE'.freeze,

      # Frete Rapido.
      FRETERAPIDO = 'FRETERAPIDO'.freeze,

      # Pitney Bowes.
      PITNEY_BOWES = 'PITNEY_BOWES'.freeze,

      # Xpressen courier.
      XPRESSEN_DK = 'XPRESSEN_DK'.freeze,

      # Spanish Seur API.
      SEUR_SP_API = 'SEUR_SP_API'.freeze,

      # DELIVERYONTIME LOGISTICS PVT LTD.
      DELIVERYONTIME = 'DELIVERYONTIME'.freeze,

      # JINSUNG TRADING.
      JINSUNG = 'JINSUNG'.freeze,

      # Trans Kargo Internasional.
      TRANS_KARGO = 'TRANS_KARGO'.freeze,

      # Swiship DE.
      SWISHIP_DE = 'SWISHIP_DE'.freeze,

      # Ivoy courier.
      IVOY_WEBHOOK = 'IVOY_WEBHOOK'.freeze,

      # Airmee couriers.
      AIRMEE_WEBHOOK = 'AIRMEE_WEBHOOK'.freeze,

      # dhl benelux.
      DHL_BENELUX = 'DHL_BENELUX'.freeze,

      # FirstMile.
      FIRSTMILE = 'FIRSTMILE'.freeze,

      # Fastway Ireland.
      FASTWAY_IR = 'FASTWAY_IR'.freeze,

      # Hua Han Logistics.
      HH_EXP = 'HH_EXP'.freeze,

      # Mypostonline.
      MYS_MYPOST_ONLINE = 'MYS_MYPOST_ONLINE'.freeze,

      # THT Netherland.
      TNT_NL = 'TNT_NL'.freeze,

      # TIPSA courier.
      TIPSA = 'TIPSA'.freeze,

      # TAQBIN Malaysia.
      TAQBIN_MY = 'TAQBIN_MY'.freeze,

      # KGM Hub.
      KGMHUB = 'KGMHUB'.freeze,

      # Internet Express.
      INTEXPRESS = 'INTEXPRESS'.freeze,

      # Overseas Express.
      OVERSE_EXP = 'OVERSE_EXP'.freeze,

      # One click delivery services.
      ONECLICK = 'ONECLICK'.freeze,

      # Roadbull Logistics.
      ROADRUNNER_FREIGHT = 'ROADRUNNER_FREIGHT'.freeze,

      # GLS Croatia.
      GLS_CROTIA = 'GLS_CROTIA'.freeze,

      # MRW courier.
      MRW_FTP = 'MRW_FTP'.freeze,

      # Blue Express.
      BLUEX = 'BLUEX'.freeze,

      # Daylight Transport.
      DYLT = 'DYLT'.freeze,

      # DPD Ireland.
      DPD_IR = 'DPD_IR'.freeze,

      # Sin Global Express.
      SIN_GLBL = 'SIN_GLBL'.freeze,

      # Tuffnells Parcels Express- Reference.
      TUFFNELLS_REFERENCE = 'TUFFNELLS_REFERENCE'.freeze,

      # CJ Packet.
      CJPACKET = 'CJPACKET'.freeze,

      # Milkman courier.
      MILKMAN = 'MILKMAN'.freeze,

      # ASIGNA courier.
      ASIGNA = 'ASIGNA'.freeze,

      # One World Express.
      ONEWORLDEXPRESS = 'ONEWORLDEXPRESS'.freeze,

      # RoyalShipments.
      ROYAL_MAIL = 'ROYAL_MAIL'.freeze,

      # Viaxpress.
      VIA_EXPRESS = 'VIA_EXPRESS'.freeze,

      # TIG Freight.
      TIGFREIGHT = 'TIGFREIGHT'.freeze,

      # ZTO Express.
      ZTO_EXPRESS = 'ZTO_EXPRESS'.freeze,

      # 2GO Courier.
      TWO_GO = 'TWO_GO'.freeze,

      # IML courier.
      IML = 'IML'.freeze,

      # Intel-Valley Supply chain (ShenZhen) Co. Ltd.
      INTEL_VALLEY = 'INTEL_VALLEY'.freeze,

      # EFS (E-commerce Fulfillment Service).
      EFS = 'EFS'.freeze,

      # UK mail (ukmail.com).
      UK_UK_MAIL = 'UK_UK_MAIL'.freeze,

      # RAM courier.
      RAM = 'RAM'.freeze,

      # Allied Express.
      ALLIEDEXPRESS = 'ALLIEDEXPRESS'.freeze,

      # APC overnight (apc-overnight.com).
      APC_OVERNIGHT = 'APC_OVERNIGHT'.freeze,

      # Shippit.
      SHIPPIT = 'SHIPPIT'.freeze,

      # TFM Xpress.
      TFM = 'TFM'.freeze,

      # M Xpress Sdn Bhd.
      M_XPRESS = 'M_XPRESS'.freeze,

      # Haidaibao (BOX).
      HDB_BOX = 'HDB_BOX'.freeze,

      # Clevy Links.
      CLEVY_LINKS = 'CLEVY_LINKS'.freeze,

      # Beone Logistics.
      IBEONE = 'IBEONE'.freeze,

      # Fiege Netherlands.
      FIEGE_NL = 'FIEGE_NL'.freeze,

      # KWE Global.
      KWE_GLOBAL = 'KWE_GLOBAL'.freeze,

      # CTC Express.
      CTC_EXPRESS = 'CTC_EXPRESS'.freeze,

      # Amazon Shipping.
      AMAZON = 'AMAZON'.freeze,

      # Morelink.
      MORE_LINK = 'MORE_LINK'.freeze,

      # JX courier.
      JX = 'JX'.freeze,

      # Easy Mail.
      EASY_MAIL = 'EASY_MAIL'.freeze,

      # A Duie Pyle.
      ADUIEPYLE = 'ADUIEPYLE'.freeze,

      # Panther.
      GB_PANTHER = 'GB_PANTHER'.freeze,

      # Expresssale.
      EXPRESSSALE = 'EXPRESSSALE'.freeze,

      # Detrack.
      SG_DETRACK = 'SG_DETRACK'.freeze,

      # Trunkrs courier.
      TRUNKRS_WEBHOOK = 'TRUNKRS_WEBHOOK'.freeze,

      # Matdespatch.
      MATDESPATCH = 'MATDESPATCH'.freeze,

      # GLS Logistic Systems Canada Ltd./Dicom.
      DICOM = 'DICOM'.freeze,

      # MBW Courier Inc..
      MBW = 'MBW'.freeze,

      # Cambodia Post.
      KHM_CAMBODIA_POST = 'KHM_CAMBODIA_POST'.freeze,

      # Sinotrans.
      SINOTRANS = 'SINOTRANS'.freeze,

      # BRT Bartolini(Parcel ID).
      BRT_IT_PARCELID = 'BRT_IT_PARCELID'.freeze,

      # DHL Supply Chain APAC.
      DHL_SUPPLY_CHAIN = 'DHL_SUPPLY_CHAIN'.freeze,

      # DHL Poland.
      DHL_PL = 'DHL_PL'.freeze,

      # TopYou.
      TOPYOU = 'TOPYOU'.freeze,

      # PAL Express Limited.
      PALEXPRESS = 'PALEXPRESS'.freeze,

      # dhl Singapore.
      DHL_SG = 'DHL_SG'.freeze,

      # WeDo Logistics.
      CN_WEDO = 'CN_WEDO'.freeze,

      # Fulfillme.
      FULFILLME = 'FULFILLME'.freeze,

      # DPD delistrack.
      DPD_DELISTRACK = 'DPD_DELISTRACK'.freeze,

      # UPS Reference.
      UPS_REFERENCE = 'UPS_REFERENCE'.freeze,

      # Caribou.
      CARIBOU = 'CARIBOU'.freeze,

      # Locus courier.
      LOCUS_WEBHOOK = 'LOCUS_WEBHOOK'.freeze,

      # DSV courier.
      DSV = 'DSV'.freeze,

      # P2P TrakPak.
      P2P_TRC = 'P2P_TRC'.freeze,

      # Direct Parcels.
      DIRECTPARCELS = 'DIRECTPARCELS'.freeze,

      # Nova Poshta (International).
      NOVA_POSHTA_INT = 'NOVA_POSHTA_INT'.freeze,

      # FedEx® Poland Domestic.
      FEDEX_POLAND = 'FEDEX_POLAND'.freeze,

      # JCEX courier.
      CN_JCEX = 'CN_JCEX'.freeze,

      # FAR international.
      FAR_INTERNATIONAL = 'FAR_INTERNATIONAL'.freeze,

      # IDEX courier.
      IDEXPRESS = 'IDEXPRESS'.freeze,

      # GANGBAO Supplychain.
      GANGBAO = 'GANGBAO'.freeze,

      # Neway Transport.
      NEWAY = 'NEWAY'.freeze,

      # PostNL International.
      POSTNL_INT_3_S = 'POSTNL_INT_3_S'.freeze,

      # RPX Indonesia.
      RPX_ID = 'RPX_ID'.freeze,

      # Designer Transport.
      DESIGNERTRANSPORT_WEBHOOK = 'DESIGNERTRANSPORT_WEBHOOK'.freeze,

      # GLS Slovenia.
      GLS_SLOVEN = 'GLS_SLOVEN'.freeze,

      # Parcelled.in.
      PARCELLED_IN = 'PARCELLED_IN'.freeze,

      # GSI EXPRESS.
      GSI_EXPRESS = 'GSI_EXPRESS'.freeze,

      # Con-way Freight.
      CON_WAY = 'CON_WAY'.freeze,

      # Brouwer Transport en Logistiek.
      BROUWER_TRANSPORT = 'BROUWER_TRANSPORT'.freeze,

      # Captain Express International.
      CPEX = 'CPEX'.freeze,

      # Israel Post.
      ISRAEL_POST = 'ISRAEL_POST'.freeze,

      # DTDC India.
      DTDC_IN = 'DTDC_IN'.freeze,

      # PTT Post.
      PTT_POST = 'PTT_POST'.freeze,

      # Ximex Delivery Express.
      XDE_WEBHOOK = 'XDE_WEBHOOK'.freeze,

      # Tolos courier.
      TOLOS = 'TOLOS'.freeze,

      # Giao hàng nhanh.
      GIAO_HANG = 'GIAO_HANG'.freeze,

      # Geodis E-space.
      GEODIS_ESPACE = 'GEODIS_ESPACE'.freeze,

      # Magyar Post.
      MAGYAR_HU = 'MAGYAR_HU'.freeze,

      # DoorDash.
      DOORDASH_WEBHOOK = 'DOORDASH_WEBHOOK'.freeze,

      # Tiki shipment.
      TIKI_ID = 'TIKI_ID'.freeze,

      # CJ Logistics International(Hong Kong).
      CJ_HK_INTERNATIONAL = 'CJ_HK_INTERNATIONAL'.freeze,

      # Star Track Express.
      STAR_TRACK_EXPRESS = 'STAR_TRACK_EXPRESS'.freeze,

      # Helthjem.
      HELTHJEM = 'HELTHJEM'.freeze,

      # SF International.
      SFB2C = 'SFB2C'.freeze,

      # Freightquote by C.H. Robinson.
      FREIGHTQUOTE = 'FREIGHTQUOTE'.freeze,

      # Landmark Global Reference.
      LANDMARK_GLOBAL_REFERENCE = 'LANDMARK_GLOBAL_REFERENCE'.freeze,

      # Parcel2Go.
      PARCEL2GO = 'PARCEL2GO'.freeze,

      # Delnext.
      DELNEXT = 'DELNEXT'.freeze,

      # Red Carpet Logistics.
      RCL = 'RCL'.freeze,

      # CGS Express.
      CGS_EXPRESS = 'CGS_EXPRESS'.freeze,

      # Hongkong Post (www.hongkongpost.hk).
      HK_POST = 'HK_POST'.freeze,

      # SAP EXPRESS.
      SAP_EXPRESS = 'SAP_EXPRESS'.freeze,

      # Parcel Post Singapore.
      PARCELPOST_SG = 'PARCELPOST_SG'.freeze,

      # HermesWorld UK.
      HERMES = 'HERMES'.freeze,

      # Safexpress.
      IND_SAFEEXPRESS = 'IND_SAFEEXPRESS'.freeze,

      # Tophatter Express.
      TOPHATTEREXPRESS = 'TOPHATTEREXPRESS'.freeze,

      # PT MGLOBAL LOGISTICS INDONESIA.
      MGLOBAL = 'MGLOBAL'.freeze,

      # Averitt Express.
      AVERITT = 'AVERITT'.freeze,

      # leader.
      LEADER = 'LEADER'.freeze,

      # 2ebox courier.
      _2EBOX = '_2EBOX'.freeze,

      # Singapore Speedpost.
      SG_SPEEDPOST = 'SG_SPEEDPOST'.freeze,

      # DB Schenker (www.dbschenker.com).
      DBSCHENKER_SE = 'DBSCHENKER_SE'.freeze,

      # Israel Post Domestic.
      ISR_POST_DOMESTIC = 'ISR_POST_DOMESTIC'.freeze,

      # Best Way Parcel.
      BESTWAYPARCEL = 'BESTWAYPARCEL'.freeze,

      # asendia_de.
      ASENDIA_DE = 'ASENDIA_DE'.freeze,

      # nightline_uk.
      NIGHTLINE_UK = 'NIGHTLINE_UK'.freeze,

      # taqbin_sg.
      TAQBIN_SG = 'TAQBIN_SG'.freeze,

      # TCK Express.
      TCK_EXPRESS = 'TCK_EXPRESS'.freeze,

      # Endeavour Delivery.
      ENDEAVOUR_DELIVERY = 'ENDEAVOUR_DELIVERY'.freeze,

      # Nanjing Woyuan.
      NANJINGWOYUAN = 'NANJINGWOYUAN'.freeze,

      # Heppner France.
      HEPPNER_FR = 'HEPPNER_FR'.freeze,

      # EMPS Express.
      EMPS_CN = 'EMPS_CN'.freeze,

      # Fonsen Logistics.
      FONSEN = 'FONSEN'.freeze,

      # Pickrr.
      PICKRR = 'PICKRR'.freeze,

      # APC Overnight Consignment.
      APC_OVERNIGHT_CONNUM = 'APC_OVERNIGHT_CONNUM'.freeze,

      # Star Track Next Flight.
      STAR_TRACK_NEXT_FLIGHT = 'STAR_TRACK_NEXT_FLIGHT'.freeze,

      # Shanghai Aqrum Chemical Logistics Co.Ltd.
      DAJIN = 'DAJIN'.freeze,

      # UPS Freight.
      UPS_FREIGHT = 'UPS_FREIGHT'.freeze,

      # Posta Plus.
      POSTA_PLUS = 'POSTA_PLUS'.freeze,

      # CEVA LOGISTICS.
      CEVA = 'CEVA'.freeze,

      # ANSERX courier.
      ANSERX = 'ANSERX'.freeze,

      # JS EXPRESS.
      JS_EXPRESS = 'JS_EXPRESS'.freeze,

      # padtf.com.
      PADTF = 'PADTF'.freeze,

      # UPS Mail Innovations.
      UPS_MAIL_INNOVATIONS = 'UPS_MAIL_INNOVATIONS'.freeze,

      # Sunyou Post.
      SYPOST = 'SYPOST'.freeze,

      # Amazon Shipping + Amazon MCF.
      AMAZON_SHIP_MCF = 'AMAZON_SHIP_MCF'.freeze,

      # Yusen Logistics.
      YUSEN = 'YUSEN'.freeze,

      # Bring.
      BRING = 'BRING'.freeze,

      # SDA Italy.
      SDA_IT = 'SDA_IT'.freeze,

      # GBA Services Ltd.
      GBA = 'GBA'.freeze,

      # Newegg Express.
      NEWEGGEXPRESS = 'NEWEGGEXPRESS'.freeze,

      # Speed Couriers.
      SPEEDCOURIERS_GR = 'SPEEDCOURIERS_GR'.freeze,

      # forrun Pvt Ltd (Arpatech Venture).
      FORRUN = 'FORRUN'.freeze,

      # Pickupp.
      PICKUP = 'PICKUP'.freeze,

      # ECMS International Logistics Co..
      ECMS = 'ECMS'.freeze,

      # Intelipost (TMS for LATAM).
      INTELIPOST = 'INTELIPOST'.freeze,

      # Flash Express.
      FLASHEXPRESS = 'FLASHEXPRESS'.freeze,

      # STO Express.
      CN_STO = 'CN_STO'.freeze,

      # SEKO Worldwide.
      SEKO_SFTP = 'SEKO_SFTP'.freeze,

      # Home Delivery Solutions Ltd.
      HOME_DELIVERY_SOLUTIONS = 'HOME_DELIVERY_SOLUTIONS'.freeze,

      # DPD Hungary.
      DPD_HGRY = 'DPD_HGRY'.freeze,

      # Kerry Express (Vietnam) Co Ltd.
      KERRYTTC_VN = 'KERRYTTC_VN'.freeze,

      # Joying Box.
      JOYING_BOX = 'JOYING_BOX'.freeze,

      # Total Express.
      TOTAL_EXPRESS = 'TOTAL_EXPRESS'.freeze,

      # ZJS International.
      ZJS_EXPRESS = 'ZJS_EXPRESS'.freeze,

      # STARKEN couriers.
      STARKEN = 'STARKEN'.freeze,

      # DemandShip.
      DEMANDSHIP = 'DEMANDSHIP'.freeze,

      # DPEX.
      CN_DPEX = 'CN_DPEX'.freeze,

      # AuPost China.
      AUPOST_CN = 'AUPOST_CN'.freeze,

      # Logisters.
      LOGISTERS = 'LOGISTERS'.freeze,

      # Global Post.
      GOGLOBALPOST = 'GOGLOBALPOST'.freeze,

      # GLS Czech Republic.
      GLS_CZ = 'GLS_CZ'.freeze,

      # Paack courier.
      PAACK_WEBHOOK = 'PAACK_WEBHOOK'.freeze,

      # Grab courier.
      GRAB_WEBHOOK = 'GRAB_WEBHOOK'.freeze,

      # Parcelpoint.
      PARCELPOINT = 'PARCELPOINT'.freeze,

      # iCumulus.
      ICUMULUS = 'ICUMULUS'.freeze,

      # DAI Post.
      DAIGLOBALTRACK = 'DAIGLOBALTRACK'.freeze,

      # i-parcel.
      GLOBAL_IPARCEL = 'GLOBAL_IPARCEL'.freeze,

      # Yurtici Kargo.
      YURTICI_KARGO = 'YURTICI_KARGO'.freeze,

      # PayPal Package.
      CN_PAYPAL_PACKAGE = 'CN_PAYPAL_PACKAGE'.freeze,

      # Parcel To Post.
      PARCEL_2_POST = 'PARCEL_2_POST'.freeze,

      # GLS Italy.
      GLS_IT = 'GLS_IT'.freeze,

      # PIL Logistics (China) Co..
      PIL_LOGISTICS = 'PIL_LOGISTICS'.freeze,

      # Heppner Internationale Spedition GmbH & Co..
      HEPPNER = 'HEPPNER'.freeze,

      # Go!Express and logistics.
      GENERAL_OVERNIGHT = 'GENERAL_OVERNIGHT'.freeze,

      # Happy 2ThePoint.
      HAPPY2POINT = 'HAPPY2POINT'.freeze,

      # Chit Chats.
      CHITCHATS = 'CHITCHATS'.freeze,

      # Smooth Couriers.
      SMOOTH = 'SMOOTH'.freeze,

      # CL E-Logistics Solutions Limited.
      CLE_LOGISTICS = 'CLE_LOGISTICS'.freeze,

      # Fiege Logistics.
      FIEGE = 'FIEGE'.freeze,

      # M&X cargo.
      MX_CARGO = 'MX_CARGO'.freeze,

      # Ziing Final Mile Inc.
      ZIINGFINALMILE = 'ZIINGFINALMILE'.freeze,

      # Dayton Freight.
      DAYTON_FREIGHT = 'DAYTON_FREIGHT'.freeze,

      # TCS courier.
      TCS = 'TCS'.freeze,

      # AEX Group.
      AEX = 'AEX'.freeze,

      # Hermes Germany.
      HERMES_DE = 'HERMES_DE'.freeze,

      # Routific.
      ROUTIFIC_WEBHOOK = 'ROUTIFIC_WEBHOOK'.freeze,

      # Globavend.
      GLOBAVEND = 'GLOBAVEND'.freeze,

      # CJ Logistics International.
      CJ_LOGISTICS = 'CJ_LOGISTICS'.freeze,

      # The Pallet Network.
      PALLET_NETWORK = 'PALLET_NETWORK'.freeze,

      # RAF Philippines.
      RAF_PH = 'RAF_PH'.freeze,

      # XDP Express.
      UK_XDP = 'UK_XDP'.freeze,

      # Paper Express.
      PAPER_EXPRESS = 'PAPER_EXPRESS'.freeze,

      # La Poste.
      LA_POSTE_SUIVI = 'LA_POSTE_SUIVI'.freeze,

      # Paquetexpress.
      PAQUETEXPRESS = 'PAQUETEXPRESS'.freeze,

      # liefery.
      LIEFERY = 'LIEFERY'.freeze,

      # Streck Transport.
      STRECK_TRANSPORT = 'STRECK_TRANSPORT'.freeze,

      # Pony express.
      PONY_EXPRESS = 'PONY_EXPRESS'.freeze,

      # Always Express.
      ALWAYS_EXPRESS = 'ALWAYS_EXPRESS'.freeze,

      # GBS-Broker.
      GBS_BROKER = 'GBS_BROKER'.freeze,

      # City-Link Express.
      CITYLINK_MY = 'CITYLINK_MY'.freeze,

      # ALLJOY SUPPLY CHAIN.
      ALLJOY = 'ALLJOY'.freeze,

      # yodel.
      YODEL = 'YODEL'.freeze,

      # Yodel Direct.
      YODEL_DIR = 'YODEL_DIR'.freeze,

      # STONE3PL.
      STONE3PL = 'STONE3PL'.freeze,

      # ParcelPal.
      PARCELPAL_WEBHOOK = 'PARCELPAL_WEBHOOK'.freeze,

      # DHL eCommerce Asia (API).
      DHL_ECOMERCE_ASA = 'DHL_ECOMERCE_ASA'.freeze,

      # J&T Express Singapore.
      SIMPLYPOST = 'SIMPLYPOST'.freeze,

      # Kua Yue Express.
      KY_EXPRESS = 'KY_EXPRESS'.freeze,

      # shenzhen 1st International Logistics(Group)Co.
      SHENZHEN = 'SHENZHEN'.freeze,

      # LaserShip.
      US_LASERSHIP = 'US_LASERSHIP'.freeze,

      # ucexpress.
      UC_EXPRE = 'UC_EXPRE'.freeze,

      # DIDADI Logistics tech.
      DIDADI = 'DIDADI'.freeze,

      # CJ Korea Express.
      CJ_KR = 'CJ_KR'.freeze,

      # DB Schenker B2B.
      DBSCHENKER_B2B = 'DBSCHENKER_B2B'.freeze,

      # MXE Express.
      MXE = 'MXE'.freeze,

      # CAE Delivers.
      CAE_DELIVERS = 'CAE_DELIVERS'.freeze,

      # PFC Express.
      PFCEXPRESS = 'PFCEXPRESS'.freeze,

      # Whistl.
      WHISTL = 'WHISTL'.freeze,

      # WePost Sdn Bhd.
      WEPOST = 'WEPOST'.freeze,

      # DHL parcel Spain(www.dhl.com).
      DHL_PARCEL_ES = 'DHL_PARCEL_ES'.freeze,

      # DD Express Courier.
      DDEXPRESS = 'DDEXPRESS'.freeze,

      # Aramex Australia (formerly Fastway AU).
      ARAMEX_AU = 'ARAMEX_AU'.freeze,

      # Bneed courier.
      BNEED = 'BNEED'.freeze,

      # Kerry Express Hong Kong.
      HK_TGX = 'HK_TGX'.freeze,

      # Latvijas Pasts.
      LATVIJAS_PASTS = 'LATVIJAS_PASTS'.freeze,

      # ViaEurope.
      VIAEUROPE = 'VIAEUROPE'.freeze,

      # Correo Uruguayo.
      CORREO_UY = 'CORREO_UY'.freeze,

      # Chronopost france (www.chronopost.fr).
      CHRONOPOST_FR = 'CHRONOPOST_FR'.freeze,

      # J-Net.
      J_NET = 'J_NET'.freeze,

      # 6ls.com.
      _6LS = '_6LS'.freeze,

      # Belpost.
      BLR_BELPOST = 'BLR_BELPOST'.freeze,

      # BirdSystem.
      BIRDSYSTEM = 'BIRDSYSTEM'.freeze,

      # DobroPost.
      DOBROPOST = 'DOBROPOST'.freeze,

      # Wahana express (www.wahana.com).
      WAHANA_ID = 'WAHANA_ID'.freeze,

      # Weaship.
      WEASHIP = 'WEASHIP'.freeze,

      # Sonic Transportation & Logistics.
      SONICTL = 'SONICTL'.freeze,

      # Shenzhen Jinghuada Logistics Co..
      KWT = 'KWT'.freeze,

      # AFL LOGISTICS.
      AFLLOG_FTP = 'AFLLOG_FTP'.freeze,

      # SkyNet Worldwide Express.
      SKYNET_WORLDWIDE = 'SKYNET_WORLDWIDE'.freeze,

      # Nova Poshta (novaposhta.ua).
      NOVA_POSHTA = 'NOVA_POSHTA'.freeze,

      # Seino.
      SEINO = 'SEINO'.freeze,

      # SZENDEX.
      SZENDEX = 'SZENDEX'.freeze,

      # Bpost international.
      BPOST_INT = 'BPOST_INT'.freeze,

      # DB Schenker Sweden.
      DBSCHENKER_SV = 'DBSCHENKER_SV'.freeze,

      # AO Deutschland.
      AO_DEUTSCHLAND = 'AO_DEUTSCHLAND'.freeze,

      # EU Fleet Solutions.
      EU_FLEET_SOLUTIONS = 'EU_FLEET_SOLUTIONS'.freeze,

      # PCF Final Mile.
      PCFCORP = 'PCFCORP'.freeze,

      # Link Bridge(BeiJing)international logistics co..
      LINKBRIDGE = 'LINKBRIDGE'.freeze,

      # PT Prima Multi Cipta.
      PRIMAMULTICIPTA = 'PRIMAMULTICIPTA'.freeze,

      # Urbanfox.
      COUREX = 'COUREX'.freeze,

      # Zajil Express Company.
      ZAJIL_EXPRESS = 'ZAJIL_EXPRESS'.freeze,

      # CollectCo.
      COLLECTCO = 'COLLECTCO'.freeze,

      # J&T EXPRESS MALAYSIA.
      JTEXPRESS = 'JTEXPRESS'.freeze,

      # FedEx® UK.
      FEDEX_UK = 'FEDEX_UK'.freeze,

      # uShip courier.
      USHIP = 'USHIP'.freeze,

      # PIXSELL LOGISTICS.
      PIXSELL = 'PIXSELL'.freeze,

      # Shiptor.
      SHIPTOR = 'SHIPTOR'.freeze,

      # CDEK courier.
      CDEK = 'CDEK'.freeze,

      # ViettelPost.
      VNM_VIETTELPOST = 'VNM_VIETTELPOST'.freeze,

      # CJ Century.
      CJ_CENTURY = 'CJ_CENTURY'.freeze,

      # GSO(GLS-USA).
      GSO = 'GSO'.freeze,

      # VIWO IoT.
      VIWO = 'VIWO'.freeze,

      # SKYBOX.
      SKYBOX = 'SKYBOX'.freeze,

      # Kerry TJ Logistics.
      KERRYTJ = 'KERRYTJ'.freeze,

      # Nhat Tin Logistics.
      NTLOGISTICS_VN = 'NTLOGISTICS_VN'.freeze,

      # lightning monkey.
      SDH_SCM = 'SDH_SCM'.freeze,

      # Zinc courier.
      ZINC = 'ZINC'.freeze,

      # DPE South Africa.
      DPE_SOUTH_AFRC = 'DPE_SOUTH_AFRC'.freeze,

      # Czech Post.
      CESKA_CZ = 'CESKA_CZ'.freeze,

      # ACS Courier.
      ACS_GR = 'ACS_GR'.freeze,

      # DealerSend.
      DEALERSEND = 'DEALERSEND'.freeze,

      # Jocom.
      JOCOM = 'JOCOM'.freeze,

      # CSE courier.
      CSE = 'CSE'.freeze,

      # TForce Final Mile.
      TFORCE_FINALMILE = 'TFORCE_FINALMILE'.freeze,

      # ShipGate.
      SHIP_GATE = 'SHIP_GATE'.freeze,

      # SHIPTER.
      SHIPTER = 'SHIPTER'.freeze,

      # National Sameday.
      NATIONAL_SAMEDAY = 'NATIONAL_SAMEDAY'.freeze,

      # YunExpress.
      YUNEXPRESS = 'YUNEXPRESS'.freeze,

      # AliExpress Standard Shipping.
      CAINIAO = 'CAINIAO'.freeze,

      # DMSMatrix.
      DMS_MATRIX = 'DMS_MATRIX'.freeze,

      # Directlog (www.directlog.com.br).
      DIRECTLOG = 'DIRECTLOG'.freeze,

      # Asendia USA.
      ASENDIA_US = 'ASENDIA_US'.freeze,

      # 3JMS Logistics.
      _3JMSLOGISTICS = '_3JMSLOGISTICS'.freeze,

      # LICCARDI EXPRESS COURIER.
      LICCARDI_EXPRESS = 'LICCARDI_EXPRESS'.freeze,

      # SkyPostal.
      SKY_POSTAL = 'SKY_POSTAL'.freeze,

      # cnwangtong.
      CNWANGTONG = 'CNWANGTONG'.freeze,

      # ostnord denmark.
      POSTNORD_LOGISTICS_DK = 'POSTNORD_LOGISTICS_DK'.freeze,

      # Logistika.
      LOGISTIKA = 'LOGISTIKA'.freeze,

      # Celeritas Transporte.
      CELERITAS = 'CELERITAS'.freeze,

      # Pressio.
      PRESSIODE = 'PRESSIODE'.freeze,

      # Shree Maruti Courier Services Pvt Ltd.
      SHREE_MARUTI = 'SHREE_MARUTI'.freeze,

      # Logistic Worldwide Express (LWE Honkong).
      LOGISTICSWORLDWIDE_HK = 'LOGISTICSWORLDWIDE_HK'.freeze,

      # eFEx (E-Commerce Fulfillment & Express).
      EFEX = 'EFEX'.freeze,

      # Lotte Global Logistics.
      LOTTE = 'LOTTE'.freeze,

      # Lone Star Overnight.
      LONESTAR = 'LONESTAR'.freeze,

      # Aprisa Express.
      APRISAEXPRESS = 'APRISAEXPRESS'.freeze,

      # BEL North Russia.
      BEL_RS = 'BEL_RS'.freeze,

      # OSM Worldwide.
      OSM_WORLDWIDE = 'OSM_WORLDWIDE'.freeze,

      # Westgate Global.
      WESTGATE_GL = 'WESTGATE_GL'.freeze,

      # Fasttrack.
      FASTRACK = 'FASTRACK'.freeze,

      # DTD Express.
      DTD_EXPR = 'DTD_EXPR'.freeze,

      # AlfaTrex.
      ALFATREX = 'ALFATREX'.freeze,

      # ProMed Delivery.
      PROMEDDELIVERY = 'PROMEDDELIVERY'.freeze,

      # Thabit Logistics.
      THABIT_LOGISTICS = 'THABIT_LOGISTICS'.freeze,

      # HCT LOGISTICS CO.LTD..
      HCT_LOGISTICS = 'HCT_LOGISTICS'.freeze,

      # Carry-Flap Co..
      CARRY_FLAP = 'CARRY_FLAP'.freeze,

      # Old Dominion Freight Line.
      US_OLD_DOMINION = 'US_OLD_DOMINION'.freeze,

      # ANICAM BOX EXPRESS.
      ANICAM_BOX = 'ANICAM_BOX'.freeze,

      # WanbExpress.
      WANBEXPRESS = 'WANBEXPRESS'.freeze,

      # An Post.
      AN_POST = 'AN_POST'.freeze,

      # DPD Local.
      DPD_LOCAL = 'DPD_LOCAL'.freeze,

      # Stallion Express.
      STALLIONEXPRESS = 'STALLIONEXPRESS'.freeze,

      # RaidereX.
      RAIDEREX = 'RAIDEREX'.freeze,

      # ShopfansRU LLC.
      SHOPFANS = 'SHOPFANS'.freeze,

      # Kyungdong Parcel.
      KYUNGDONG_PARCEL = 'KYUNGDONG_PARCEL'.freeze,

      # Champion Logistics.
      CHAMPION_LOGISTICS = 'CHAMPION_LOGISTICS'.freeze,

      # PICK UPP (Singapore).
      PICKUPP_SGP = 'PICKUPP_SGP'.freeze,

      # Morning Express.
      MORNING_EXPRESS = 'MORNING_EXPRESS'.freeze,

      # NACEX.
      NACEX = 'NACEX'.freeze,

      # SortHub courier.
      THENILE_WEBHOOK = 'THENILE_WEBHOOK'.freeze,

      # Holisol.
      HOLISOL = 'HOLISOL'.freeze,

      # LBC EXPRESS INC..
      LBCEXPRESS_FTP = 'LBCEXPRESS_FTP'.freeze,

      # KURASI.
      KURASI = 'KURASI'.freeze,

      # USF Reddaway.
      USF_REDDAWAY = 'USF_REDDAWAY'.freeze,

      # APG eCommerce Solutions.
      APG = 'APG'.freeze,

      # BoxC courier.
      CN_BOXC = 'CN_BOXC'.freeze,

      # ECOSCOOTING.
      ECOSCOOTING = 'ECOSCOOTING'.freeze,

      # Mainway.
      MAINWAY = 'MAINWAY'.freeze,

      # Paperfly Private Limited.
      PAPERFLY = 'PAPERFLY'.freeze,

      # Hound Express.
      HOUNDEXPRESS = 'HOUNDEXPRESS'.freeze,

      # Boxberry courier.
      BOX_BERRY = 'BOX_BERRY'.freeze,

      # EP-Box courier.
      EP_BOX = 'EP_BOX'.freeze,

      # Plus UK Logistics.
      PLUS_LOG_UK = 'PLUS_LOG_UK'.freeze,

      # Fulfilla.
      FULFILLA = 'FULFILLA'.freeze,

      # ASE KARGO.
      ASE = 'ASE'.freeze,

      # MailPlus.
      MAIL_PLUS = 'MAIL_PLUS'.freeze,

      # XPO logistics.
      XPO_LOGISTICS = 'XPO_LOGISTICS'.freeze,

      # wnDirect.
      WNDIRECT = 'WNDIRECT'.freeze,

      # Cloudwish Asia.
      CLOUDWISH_ASIA = 'CLOUDWISH_ASIA'.freeze,

      # Zeleris.
      ZELERIS = 'ZELERIS'.freeze,

      # Gio Express.
      GIO_EXPRESS = 'GIO_EXPRESS'.freeze,

      # OCS WORLDWIDE.
      OCS_WORLDWIDE = 'OCS_WORLDWIDE'.freeze,

      # ARK Logistics.
      ARK_LOGISTICS = 'ARK_LOGISTICS'.freeze,

      # Aquiline.
      AQUILINE = 'AQUILINE'.freeze,

      # Pilot Freight Services.
      PILOT_FREIGHT = 'PILOT_FREIGHT'.freeze,

      # Qwintry Logistics.
      QWINTRY = 'QWINTRY'.freeze,

      # Danske Fragtaend.
      DANSKE_FRAGT = 'DANSKE_FRAGT'.freeze,

      # Carriers courier.
      CARRIERS = 'CARRIERS'.freeze,

      # Rivo (Air canada).
      AIR_CANADA_GLOBAL = 'AIR_CANADA_GLOBAL'.freeze,

      # PRESIDENT TRANSNET CORP.
      PRESIDENT_TRANS = 'PRESIDENT_TRANS'.freeze,

      # STEP FORWARD FREIGHT SERVICE CO LTD.
      STEPFORWARDFS = 'STEPFORWARDFS'.freeze,

      # Skynet UK.
      SKYNET_UK = 'SKYNET_UK'.freeze,

      # PITT OHIO.
      PITTOHIO = 'PITTOHIO'.freeze,

      # Correos Express.
      CORREOS_EXPRESS = 'CORREOS_EXPRESS'.freeze,

      # RL Carriers.
      RL_US = 'RL_US'.freeze,

      # Destiny Transportation.
      DESTINY = 'DESTINY'.freeze,

      # Yodel (www.yodel.co.uk).
      UK_YODEL = 'UK_YODEL'.freeze,

      # CometTech.
      COMET_TECH = 'COMET_TECH'.freeze,

      # DHL Parcel Russia.
      DHL_PARCEL_RU = 'DHL_PARCEL_RU'.freeze,

      # TNT Reference.
      TNT_REFR = 'TNT_REFR'.freeze,

      # Shree Anjani Courier.
      SHREE_ANJANI_COURIER = 'SHREE_ANJANI_COURIER'.freeze,

      # Mikropakket Belgium.
      MIKROPAKKET_BE = 'MIKROPAKKET_BE'.freeze,

      # RETS express.
      ETS_EXPRESS = 'ETS_EXPRESS'.freeze,

      # Colis Privé.
      COLIS_PRIVE = 'COLIS_PRIVE'.freeze,

      # Yunda Express.
      CN_YUNDA = 'CN_YUNDA'.freeze,

      # AAA Cooper.
      AAA_COOPER = 'AAA_COOPER'.freeze,

      # Rocket Parcel International.
      ROCKET_PARCEL = 'ROCKET_PARCEL'.freeze,

      # 360 Lion Express.
      _360LION = '_360LION'.freeze,

      # PANDU.
      PANDU = 'PANDU'.freeze,

      # PROFESSIONAL COURIERS.
      PROFESSIONAL_COURIERS = 'PROFESSIONAL_COURIERS'.freeze,

      # FLYTEXPRESS.
      FLYTEXPRESS = 'FLYTEXPRESS'.freeze,

      # LOGISTICSWORLDWIDE MY.
      LOGISTICSWORLDWIDE_MY = 'LOGISTICSWORLDWIDE_MY'.freeze,

      # CORREOS DE ESPANA.
      CORREOS_DE_ESPANA = 'CORREOS_DE_ESPANA'.freeze,

      # IMX.
      IMX = 'IMX'.freeze,

      # FOUR PX EXPRESS.
      FOUR_PX_EXPRESS = 'FOUR_PX_EXPRESS'.freeze,

      # XPRESSBEES.
      XPRESSBEES = 'XPRESSBEES'.freeze,

      # pickupp_vnm.
      PICKUPP_VNM = 'PICKUPP_VNM'.freeze,

      # startrack_express.
      STARTRACK_EXPRESS1 = 'STARTRACK_EXPRESS'.freeze,

      # fr_colissimo.
      FR_COLISSIMO = 'FR_COLISSIMO'.freeze,

      # nacex_spain_reference.
      NACEX_SPAIN_REFERENCE = 'NACEX_SPAIN_REFERENCE'.freeze,

      # dhl_supply_chain_au.
      DHL_SUPPLY_CHAIN_AU = 'DHL_SUPPLY_CHAIN_AU'.freeze,

      # Eshipping.
      ESHIPPING = 'ESHIPPING'.freeze,

      # SHREE TIRUPATI COURIER SERVICES PVT. LTD..
      SHREETIRUPATI = 'SHREETIRUPATI'.freeze,

      # HX Express.
      HX_EXPRESS = 'HX_EXPRESS'.freeze,

      # INDOPAKET.
      INDOPAKET = 'INDOPAKET'.freeze,

      # 17 Post Service.
      CN_17POST = 'CN_17POST'.freeze,

      # K1 Express.
      K1_EXPRESS = 'K1_EXPRESS'.freeze,

      # CJ GLS.
      CJ_GLS = 'CJ_GLS'.freeze,

      # GDEX courier.
      MYS_GDEX = 'MYS_GDEX'.freeze,

      # Nationex courier.
      NATIONEX = 'NATIONEX'.freeze,

      # Anjun couriers.
      ANJUN = 'ANJUN'.freeze,

      # FarGood.
      FARGOOD = 'FARGOOD'.freeze,

      # SMG Direct.
      SMG_EXPRESS = 'SMG_EXPRESS'.freeze,

      # RZY Express.
      RZYEXPRESS = 'RZYEXPRESS'.freeze,

      # Southeastern Freight Lines.
      SEFL = 'SEFL'.freeze,

      # TNT-Click Italy.
      TNT_CLICK_IT = 'TNT_CLICK_IT'.freeze,

      # Haidaibao.
      HDB = 'HDB'.freeze,

      # Hipshipper.
      HIPSHIPPER = 'HIPSHIPPER'.freeze,

      # RPX Logistics.
      RPXLOGISTICS = 'RPXLOGISTICS'.freeze,

      # Kuehne + Nagel.
      KUEHNE = 'KUEHNE'.freeze,

      # Nexive (TNT Post Italy).
      IT_NEXIVE = 'IT_NEXIVE'.freeze,

      # PTS courier.
      PTS = 'PTS'.freeze,

      # Swiss Post FTP.
      SWISS_POST_FTP = 'SWISS_POST_FTP'.freeze,

      # Fastrak Services.
      FASTRK_SERV = 'FASTRK_SERV'.freeze,

      # 4-72 Entregando.
      _4_72 = '_4_72'.freeze,

      # YRC courier.
      US_YRC = 'US_YRC'.freeze,

      # PostNL International 3S.
      POSTNL_INTL_3S = 'POSTNL_INTL_3S'.freeze,

      # Yilian (Elian) Supply Chain.
      ELIAN_POST = 'ELIAN_POST'.freeze,

      # Cubyn.
      CUBYN = 'CUBYN'.freeze,

      # Saudi Post.
      SAU_SAUDI_POST = 'SAU_SAUDI_POST'.freeze,

      # ABX Express.
      ABXEXPRESS_MY = 'ABXEXPRESS_MY'.freeze,

      # HUAHANG EXPRESS.
      HUAHAN_EXPRESS = 'HUAHAN_EXPRESS'.freeze,

      # Eshun international Logistic.
      ZES_EXPRESS = 'ZES_EXPRESS'.freeze,

      # ZeptoExpress.
      ZEPTO_EXPRESS = 'ZEPTO_EXPRESS'.freeze,

      # Skynet World Wide Express South Africa.
      SKYNET_ZA = 'SKYNET_ZA'.freeze,

      # Zeek2Door.
      ZEEK_2_DOOR = 'ZEEK_2_DOOR'.freeze,

      # Blink.
      BLINKLASTMILE = 'BLINKLASTMILE'.freeze,

      # UkrPoshta.
      POSTA_UKR = 'POSTA_UKR'.freeze,

      # C.H. Robinson Worldwide.
      CHROBINSON = 'CHROBINSON'.freeze,

      # Post56.
      CN_POST56 = 'CN_POST56'.freeze,

      # Courant Plus.
      COURANT_PLUS = 'COURANT_PLUS'.freeze,

      # Scudex Express.
      SCUDEX_EXPRESS = 'SCUDEX_EXPRESS'.freeze,

      # ShipEntegra.
      SHIPENTEGRA = 'SHIPENTEGRA'.freeze,

      # B2C courier Europe.
      B_TWO_C_EUROPE = 'B_TWO_C_EUROPE'.freeze,

      # Cope Sensitive Freight.
      COPE = 'COPE'.freeze,

      # Gati-KWE.
      IND_GATI = 'IND_GATI'.freeze,

      # WishPost.
      CN_WISHPOST = 'CN_WISHPOST'.freeze,

      # NACEX Spain.
      NACEX_ES = 'NACEX_ES'.freeze,

      # TAQBIN Hong Kong.
      TAQBIN_HK = 'TAQBIN_HK'.freeze,

      # GlobalTranz.
      GLOBALTRANZ = 'GLOBALTRANZ'.freeze,

      # Qingdao HKD International Logistics.
      HKD = 'HKD'.freeze,

      # BJS Distribution courier.
      BJSHOMEDELIVERY = 'BJSHOMEDELIVERY'.freeze,

      # Omniva.
      OMNIVA = 'OMNIVA'.freeze,

      # Sutton Transport.
      SUTTON = 'SUTTON'.freeze,

      # Panther Reference.
      PANTHER_REFERENCE = 'PANTHER_REFERENCE'.freeze,

      # SFC Service.
      SFCSERVICE = 'SFCSERVICE'.freeze,

      # LTL COURIER.
      LTL = 'LTL'.freeze,

      # Park N Parcel.
      PARKNPARCEL = 'PARKNPARCEL'.freeze,

      # Spring GDS.
      SPRING_GDS = 'SPRING_GDS'.freeze,

      # ECexpress.
      ECEXPRESS = 'ECEXPRESS'.freeze,

      # Interparcel Australia.
      INTERPARCEL_AU = 'INTERPARCEL_AU'.freeze,

      # Agility.
      AGILITY = 'AGILITY'.freeze,

      # XL Express.
      XL_EXPRESS = 'XL_EXPRESS'.freeze,

      # Ader couriers.
      ADERONLINE = 'ADERONLINE'.freeze,

      # Direct Couriers.
      DIRECTCOURIERS = 'DIRECTCOURIERS'.freeze,

      # Planzer Group.
      PLANZER = 'PLANZER'.freeze,

      # Sending Transporte Urgente y Comunicacion.
      SENDING = 'SENDING'.freeze,

      # Ninjavan Webhook.
      NINJAVAN_WB = 'NINJAVAN_WB'.freeze,

      # Nationwide Express Courier Services Bhd (www.nationwide.com.my).
      NATIONWIDE_MY = 'NATIONWIDE_MY'.freeze,

      # Sendit.
      SENDIT = 'SENDIT'.freeze,

      # Arrow XL.
      GB_ARROW = 'GB_ARROW'.freeze,

      # GoJavas.
      IND_GOJAVAS = 'IND_GOJAVAS'.freeze,

      # Korea Post.
      KPOST = 'KPOST'.freeze,

      # DHL Freight.
      DHL_FREIGHT = 'DHL_FREIGHT'.freeze,

      # Bluecare Express Ltd.
      BLUECARE = 'BLUECARE'.freeze,

      # jindouyun courier.
      JINDOUYUN = 'JINDOUYUN'.freeze,

      # Trackon Couriers Pvt. Ltd.
      TRACKON = 'TRACKON'.freeze,

      # Tuffnells Parcels Express.
      GB_TUFFNELLS = 'GB_TUFFNELLS'.freeze,

      # TRUMPCARD LLC.
      TRUMPCARD = 'TRUMPCARD'.freeze,

      # eTotal Solution Limited.
      ETOTAL = 'ETOTAL'.freeze,

      # Zeek courier.
      SFPLUS_WEBHOOK = 'SFPLUS_WEBHOOK'.freeze,

      # SEKO Logistics.
      SEKOLOGISTICS = 'SEKOLOGISTICS'.freeze,

      # Hermes Einrichtungs Service GmbH & Co. KG.
      HERMES_2MANN_HANDLING = 'HERMES_2MANN_HANDLING'.freeze,

      # DPD Local reference.
      DPD_LOCAL_REF = 'DPD_LOCAL_REF'.freeze,

      # United Delivery Service.
      UDS = 'UDS'.freeze,

      # Specialised Freight.
      ZA_SPECIALISED_FREIGHT = 'ZA_SPECIALISED_FREIGHT'.freeze,

      # Kerry Express Thailand.
      THA_KERRY = 'THA_KERRY'.freeze,

      # SEUR International.
      PRT_INT_SEUR = 'PRT_INT_SEUR'.freeze,

      # Correios Brazil.
      BRA_CORREIOS = 'BRA_CORREIOS'.freeze,

      # New Zealand Post.
      NZ_NZ_POST = 'NZ_NZ_POST'.freeze,

      # Equick China.
      CN_EQUICK = 'CN_EQUICK'.freeze,

      # Malaysia Post EMS / Pos Laju.
      MYS_EMS = 'MYS_EMS'.freeze,

      # Norsk Global.
      GB_NORSK = 'GB_NORSK'.freeze,

      # MRW spain.
      ESP_MRW = 'ESP_MRW'.freeze,

      # Packlink.
      ESP_PACKLINK = 'ESP_PACKLINK'.freeze,

      # Kangaroo Worldwide Express.
      KANGAROO_MY = 'KANGAROO_MY'.freeze,

      # RPX Online.
      RPX = 'RPX'.freeze,

      # XDP Express Reference.
      XDP_UK_REFERENCE = 'XDP_UK_REFERENCE'.freeze,

      # ninja van (www.ninjavan.co).
      NINJAVAN_MY = 'NINJAVAN_MY'.freeze,

      # Adicional Logistics.
      ADICIONAL = 'ADICIONAL'.freeze,

      # Red Carpet Logistics.
      ROADBULL = 'ROADBULL'.freeze,

      # Yakit courier.
      YAKIT = 'YAKIT'.freeze,

      # MailAmericas.
      MAILAMERICAS = 'MAILAMERICAS'.freeze,

      # Mikropakket.
      MIKROPAKKET = 'MIKROPAKKET'.freeze,

      # Dynamic Logistics.
      DYNALOGIC = 'DYNALOGIC'.freeze,

      # DHL Spain(www.dhl.com).
      DHL_ES = 'DHL_ES'.freeze,

      # DHL Parcel NL.
      DHL_PARCEL_NL = 'DHL_PARCEL_NL'.freeze,

      # DHL Global Mail Asia (www.dhl.com).
      DHL_GLOBAL_MAIL_ASIA = 'DHL_GLOBAL_MAIL_ASIA'.freeze,

      # Dawn Wing.
      DAWN_WING = 'DAWN_WING'.freeze,

      # Geniki Taxydromiki.
      GENIKI_GR = 'GENIKI_GR'.freeze,

      # hermesworld_uk.
      HERMESWORLD_UK = 'HERMESWORLD_UK'.freeze,

      # Alphafast (www.alphafast.com).
      ALPHAFAST = 'ALPHAFAST'.freeze,

      # buylogic.
      BUYLOGIC = 'BUYLOGIC'.freeze,

      # Ekart logistics (ekartlogistics.com).
      EKART = 'EKART'.freeze,

      # mexico senda express.
      MEX_SENDA = 'MEX_SENDA'.freeze,

      # SFC.
      SFC_LOGISTICS = 'SFC_LOGISTICS'.freeze,

      # Posta Serbia.
      POST_SERBIA = 'POST_SERBIA'.freeze,

      # Delhivery India.
      IND_DELHIVERY = 'IND_DELHIVERY'.freeze,

      # DPD Germany.
      DE_DPD_DELISTRACK = 'DE_DPD_DELISTRACK'.freeze,

      # RPD2man Deliveries.
      RPD2MAN = 'RPD2MAN'.freeze,

      # SF Express (www.sf-express.com).
      CN_SF_EXPRESS = 'CN_SF_EXPRESS'.freeze,

      # Yanwen Logistics.
      YANWEN = 'YANWEN'.freeze,

      # Skynet Malaysia.
      MYS_SKYNET = 'MYS_SKYNET'.freeze,

      # correos mexico.
      CORREOS_DE_MEXICO = 'CORREOS_DE_MEXICO'.freeze,

      # CBL Logistica.
      CBL_LOGISTICA = 'CBL_LOGISTICA'.freeze,

      # Estafeta (www.estafeta.com).
      MEX_ESTAFETA = 'MEX_ESTAFETA'.freeze,

      # Austrian Post (Registered).
      AU_AUSTRIAN_POST = 'AU_AUSTRIAN_POST'.freeze,

      # Rincos.
      RINCOS = 'RINCOS'.freeze,

      # DHL Netherland.
      NLD_DHL = 'NLD_DHL'.freeze,

      # Russian post.
      RUSSIAN_POST = 'RUSSIAN_POST'.freeze,

      # CouriersPlease (couriersplease.com.au).
      COURIERS_PLEASE = 'COURIERS_PLEASE'.freeze,

      # PostNord Logistics.
      POSTNORD_LOGISTICS = 'POSTNORD_LOGISTICS'.freeze,

      # Fedex.
      FEDEX = 'FEDEX'.freeze,

      # DPE Express.
      DPE_EXPRESS = 'DPE_EXPRESS'.freeze,

      # DPD.
      DPD = 'DPD'.freeze,

      # ADSone.
      ADSONE = 'ADSONE'.freeze,

      # JNE Express (Jalur Nugraha Ekakurir).
      IDN_JNE = 'IDN_JNE'.freeze,

      # The Courier Guy.
      THECOURIERGUY = 'THECOURIERGUY'.freeze,

      # CNE Express.
      CNEXPS = 'CNEXPS'.freeze,

      # Chronopost Portugal.
      PRT_CHRONOPOST = 'PRT_CHRONOPOST'.freeze,

      # Landmark Global.
      LANDMARK_GLOBAL = 'LANDMARK_GLOBAL'.freeze,

      # DHL International.
      IT_DHL_ECOMMERCE = 'IT_DHL_ECOMMERCE'.freeze,

      # NACEX Spain.
      ESP_NACEX = 'ESP_NACEX'.freeze,

      # CTT Portugal.
      PRT_CTT = 'PRT_CTT'.freeze,

      # Kiala.
      BE_KIALA = 'BE_KIALA'.freeze,

      # Asendia UK.
      ASENDIA_UK = 'ASENDIA_UK'.freeze,

      # TNT global.
      GLOBAL_TNT = 'GLOBAL_TNT'.freeze,

      # Iceland Post.
      POSTUR_IS = 'POSTUR_IS'.freeze,

      # eParcel Korea.
      EPARCEL_KR = 'EPARCEL_KR'.freeze,

      # InPost Paczkomaty.
      INPOST_PACZKOMATY = 'INPOST_PACZKOMATY'.freeze,

      # Poste italiane (www.poste.it).
      IT_POSTE_ITALIA = 'IT_POSTE_ITALIA'.freeze,

      # Bpost (www.bpost.be).
      BE_BPOST = 'BE_BPOST'.freeze,

      # Poczta Polska (www.poczta-polska.pl).
      PL_POCZTA_POLSKA = 'PL_POCZTA_POLSKA'.freeze,

      # Malaysia Post.
      MYS_MYS_POST = 'MYS_MYS_POST'.freeze,

      # Singapore Post.
      SG_SG_POST = 'SG_SG_POST'.freeze,

      # Thailand Post (www.thailandpost.co.th).
      THA_THAILAND_POST = 'THA_THAILAND_POST'.freeze,

      # LexShip.
      LEXSHIP = 'LEXSHIP'.freeze,

      # Fastway New Zealand.
      FASTWAY_NZ = 'FASTWAY_NZ'.freeze,

      # DHL Supply Chain Australia.
      DHL_AU = 'DHL_AU'.freeze,

      # Cosmetics Now.
      COSTMETICSNOW = 'COSTMETICSNOW'.freeze,

      # PFL.
      PFLOGISTICS = 'PFLOGISTICS'.freeze,

      # Loomis Express.
      LOOMIS_EXPRESS = 'LOOMIS_EXPRESS'.freeze,

      # GLS Italy.
      GLS_ITALY = 'GLS_ITALY'.freeze,

      # Line Clear Express & Logistics Sdn Bhd.
      LINE = 'LINE'.freeze,

      # Gel Express Logistik.
      GEL_EXPRESS = 'GEL_EXPRESS'.freeze,

      # Huodull.
      HUODULL = 'HUODULL'.freeze,

      # Ninja van Singapore.
      NINJAVAN_SG = 'NINJAVAN_SG'.freeze,

      # Janio Asia.
      JANIO = 'JANIO'.freeze,

      # AO Logistics.
      AO_COURIER = 'AO_COURIER'.freeze,

      # BRT Bartolini(Sender Reference).
      BRT_IT_SENDER_REF = 'BRT_IT_SENDER_REF'.freeze,

      # SAILPOST.
      SAILPOST = 'SAILPOST'.freeze,

      # Lalamove.
      LALAMOVE = 'LALAMOVE'.freeze,

      # NEW ZEALAND COURIERS.
      NEWZEALAND_COURIERS = 'NEWZEALAND_COURIERS'.freeze,

      # Etomars.
      ETOMARS = 'ETOMARS'.freeze,

      # VIR Transport.
      VIRTRANSPORT = 'VIRTRANSPORT'.freeze,

      # Wizmo.
      WIZMO = 'WIZMO'.freeze,

      # Palletways.
      PALLETWAYS = 'PALLETWAYS'.freeze,

      # i-dika.
      I_DIKA = 'I_DIKA'.freeze,

      # CFL Logistics.
      CFL_LOGISTICS = 'CFL_LOGISTICS'.freeze,

      # GEM Worldwide.
      GEMWORLDWIDE = 'GEMWORLDWIDE'.freeze,

      # Tai Wan Global Business.
      GLOBAL_EXPRESS = 'GLOBAL_EXPRESS'.freeze,

      # Transgroup courier.
      LOGISTYX_TRANSGROUP = 'LOGISTYX_TRANSGROUP'.freeze,

      # West Bank Courier.
      WESTBANK_COURIER = 'WESTBANK_COURIER'.freeze,

      # Arco Spedizioni SP.
      ARCO_SPEDIZIONI = 'ARCO_SPEDIZIONI'.freeze,

      # YDH express.
      YDH_EXPRESS = 'YDH_EXPRESS'.freeze,

      # Parcelink Logistics.
      PARCELINKLOGISTICS = 'PARCELINKLOGISTICS'.freeze,

      # CND Express.
      CNDEXPRESS = 'CNDEXPRESS'.freeze,

      # NOX NightTimeExpress.
      NOX_NIGHT_TIME_EXPRESS = 'NOX_NIGHT_TIME_EXPRESS'.freeze,

      # Aeronet couriers.
      AERONET = 'AERONET'.freeze,

      # LTIAN EXP.
      LTIANEXP = 'LTIANEXP'.freeze,

      # Integra2.
      INTEGRA2_FTP = 'INTEGRA2_FTP'.freeze,

      # PARCEL ONE.
      PARCELONE = 'PARCELONE'.freeze,

      # Innight Express Germany GmbH (nox NachtExpress).
      NOX_NACHTEXPRESS = 'NOX_NACHTEXPRESS'.freeze,

      # China Post.
      CN_CHINA_POST_EMS = 'CN_CHINA_POST_EMS'.freeze,

      # Chukou1.
      CHUKOU1 = 'CHUKOU1'.freeze,

      # GLS General Logistics Systems Slovakia s.r.o..
      GLS_SLOV = 'GLS_SLOV'.freeze,

      # OrangeDS (Orange Distribution Solutions Inc).
      ORANGE_DS = 'ORANGE_DS'.freeze,

      # Joom Logistics.
      JOOM_LOGIS = 'JOOM_LOGIS'.freeze,

      # StarTrack (startrack.com.au).
      AUS_STARTRACK = 'AUS_STARTRACK'.freeze,

      # dhl Global.
      DHL = 'DHL'.freeze,

      # APC postal logistics germany.
      GB_APC = 'GB_APC'.freeze,

      # Bonds Courier Service (bondscouriers.com.au).
      BONDSCOURIERS = 'BONDSCOURIERS'.freeze,

      # Japan Post.
      JPN_JAPAN_POST = 'JPN_JAPAN_POST'.freeze,

      # United States Postal Service.
      USPS = 'USPS'.freeze,

      # WinIt.
      WINIT = 'WINIT'.freeze,

      # OCA Argentina.
      ARG_OCA = 'ARG_OCA'.freeze,

      # Taiwan Post.
      TW_TAIWAN_POST = 'TW_TAIWAN_POST'.freeze,

      # DMM Network.
      DMM_NETWORK = 'DMM_NETWORK'.freeze,

      # TNT Express.
      TNT = 'TNT'.freeze,

      # BH Posta (www.posta.ba).
      BH_POSTA = 'BH_POSTA'.freeze,

      # Postnord sweden.
      SWE_POSTNORD = 'SWE_POSTNORD'.freeze,

      # Canada Post.
      CA_CANADA_POST = 'CA_CANADA_POST'.freeze,

      # Wiseloads.
      WISELOADS = 'WISELOADS'.freeze,

      # Asendia HonKong.
      ASENDIA_HK = 'ASENDIA_HK'.freeze,

      # GLS Netherland.
      NLD_GLS = 'NLD_GLS'.freeze,

      # Redpack.
      MEX_REDPACK = 'MEX_REDPACK'.freeze,

      # Jet-Ship Worldwide.
      JET_SHIP = 'JET_SHIP'.freeze,

      # DHL Express.
      DE_DHL_EXPRESS = 'DE_DHL_EXPRESS'.freeze,

      # Ninja van Thai.
      NINJAVAN_THAI = 'NINJAVAN_THAI'.freeze,

      # Raben Group.
      RABEN_GROUP = 'RABEN_GROUP'.freeze,

      # ASM(GLS Spain).
      ESP_ASM = 'ESP_ASM'.freeze,

      # Hrvatska posta.
      HRV_HRVATSKA = 'HRV_HRVATSKA'.freeze,

      # Estes Express Lines.
      GLOBAL_ESTES = 'GLOBAL_ESTES'.freeze,

      # Lietuvos pastas.
      LTU_LIETUVOS = 'LTU_LIETUVOS'.freeze,

      # DHL Benelux.
      BEL_DHL = 'BEL_DHL'.freeze,

      # Australia Post.
      AU_AU_POST = 'AU_AU_POST'.freeze,

      # SPEEDEX couriers.
      SPEEDEXCOURIER = 'SPEEDEXCOURIER'.freeze,

      # Colissimo.
      FR_COLIS = 'FR_COLIS'.freeze,

      # Aramex.
      ARAMEX = 'ARAMEX'.freeze,

      # DPEX (www.dpex.com).
      DPEX = 'DPEX'.freeze,

      # Airpak Express.
      MYS_AIRPAK = 'MYS_AIRPAK'.freeze,

      # Cuckoo Express.
      CUCKOOEXPRESS = 'CUCKOOEXPRESS'.freeze,

      # DPD Poland.
      DPD_POLAND = 'DPD_POLAND'.freeze,

      # PostNL International.
      NLD_POSTNL = 'NLD_POSTNL'.freeze,

      # Nim Express.
      NIM_EXPRESS = 'NIM_EXPRESS'.freeze,

      # Quantium.
      QUANTIUM = 'QUANTIUM'.freeze,

      # Sendle.
      SENDLE = 'SENDLE'.freeze,

      # Redur Spain.
      ESP_REDUR = 'ESP_REDUR'.freeze,

      # Matkahuolto.
      MATKAHUOLTO = 'MATKAHUOLTO'.freeze,

      # Cpacket couriers.
      CPACKET = 'CPACKET'.freeze,

      # Posti courier.
      POSTI = 'POSTI'.freeze,

      # Hunter Express.
      HUNTER_EXPRESS = 'HUNTER_EXPRESS'.freeze,

      # Choir Express Indonesia.
      CHOIR_EXP = 'CHOIR_EXP'.freeze,

      # Legion Express.
      LEGION_EXPRESS = 'LEGION_EXPRESS'.freeze,

      # austrian post.
      AUSTRIAN_POST_EXPRESS = 'AUSTRIAN_POST_EXPRESS'.freeze,

      # Grupo ampm.
      GRUPO = 'GRUPO'.freeze,

      # Post Roman (www.posta-romana.ro).
      POSTA_RO = 'POSTA_RO'.freeze,

      # Interparcel UK.
      INTERPARCEL_UK = 'INTERPARCEL_UK'.freeze,

      # ABF Freight.
      GLOBAL_ABF = 'GLOBAL_ABF'.freeze,

      # Posten Norge (www.posten.no).
      POSTEN_NORGE = 'POSTEN_NORGE'.freeze,

      # Xpert Delivery.
      XPERT_DELIVERY = 'XPERT_DELIVERY'.freeze,

      # DHl (Reference number).
      DHL_REFR = 'DHL_REFR'.freeze,

      # DHL HonKong.
      DHL_HK = 'DHL_HK'.freeze,

      # SKYNET UAE.
      SKYNET_UAE = 'SKYNET_UAE'.freeze,

      # Gojek.
      GOJEK = 'GOJEK'.freeze,

      # Yodel International.
      YODEL_INTNL = 'YODEL_INTNL'.freeze,

      # Janco Ecommerce.
      JANCO = 'JANCO'.freeze,

      # YTO Express.
      YTO = 'YTO'.freeze,

      # Wise Express.
      WISE_EXPRESS = 'WISE_EXPRESS'.freeze,

      # J&T Express Vietnam.
      JTEXPRESS_VN = 'JTEXPRESS_VN'.freeze,

      # FedEx International MailService.
      FEDEX_INTL_MLSERV = 'FEDEX_INTL_MLSERV'.freeze,

      # VAMOX.
      VAMOX = 'VAMOX'.freeze,

      # AMS Group.
      AMS_GRP = 'AMS_GRP'.freeze,

      # DHL Japan.
      DHL_JP = 'DHL_JP'.freeze,

      # HR Parcel.
      HRPARCEL = 'HRPARCEL'.freeze,

      # GESWL Express.
      GESWL = 'GESWL'.freeze,

      # Blue Star.
      BLUESTAR = 'BLUESTAR'.freeze,

      # CDEK TR.
      CDEK_TR = 'CDEK_TR'.freeze,

      # Innovel courier.
      DESCARTES = 'DESCARTES'.freeze,

      # Deltec Courier.
      DELTEC_UK = 'DELTEC_UK'.freeze,

      # DTDC express.
      DTDC_EXPRESS = 'DTDC_EXPRESS'.freeze,

      # tourline.
      TOURLINE = 'TOURLINE'.freeze,

      # B&H Worldwide.
      BH_WORLDWIDE = 'BH_WORLDWIDE'.freeze,

      # OCS ANA Group.
      OCS = 'OCS'.freeze,

      # yingnuo logistics.
      YINGNUO_LOGISTICS = 'YINGNUO_LOGISTICS'.freeze,

      # United Parcel Service.
      UPS = 'UPS'.freeze,

      # Toll IPEC.
      TOLL = 'TOLL'.freeze,

      # SEUR portugal.
      PRT_SEUR = 'PRT_SEUR'.freeze,

      # DTDC Australia.
      DTDC_AU = 'DTDC_AU'.freeze,

      # Dynamic Logistics.
      THA_DYNAMIC_LOGISTICS = 'THA_DYNAMIC_LOGISTICS'.freeze,

      # UBI Smart Parcel.
      UBI_LOGISTICS = 'UBI_LOGISTICS'.freeze,

      # FedEx Cross Border.
      FEDEX_CROSSBORDER = 'FEDEX_CROSSBORDER'.freeze,

      # A1Post.
      A1POST = 'A1POST'.freeze,

      # Tazmanian Freight Systems.
      TAZMANIAN_FREIGHT = 'TAZMANIAN_FREIGHT'.freeze,

      # CJ International malaysia.
      CJ_INT_MY = 'CJ_INT_MY'.freeze,

      # Saia LTL Freight.
      SAIA_FREIGHT = 'SAIA_FREIGHT'.freeze,

      # Qxpress.
      SG_QXPRESS = 'SG_QXPRESS'.freeze,

      # Nhans Solutions.
      NHANS_SOLUTIONS = 'NHANS_SOLUTIONS'.freeze,

      # DPD France.
      DPD_FR = 'DPD_FR'.freeze,

      # Coordinadora.
      COORDINADORA = 'COORDINADORA'.freeze,

      # Grupo logistico Andreani.
      ANDREANI = 'ANDREANI'.freeze,

      # Doora Logistics.
      DOORA = 'DOORA'.freeze,

      # Interparcel New Zealand.
      INTERPARCEL_NZ = 'INTERPARCEL_NZ'.freeze,

      # Jam Express Philippines.
      PHL_JAMEXPRESS = 'PHL_JAMEXPRESS'.freeze,

      # bel_belgium_post.
      BEL_BELGIUM_POST = 'BEL_BELGIUM_POST'.freeze,

      # us_apc.
      US_APC = 'US_APC'.freeze,

      # idn_pos.
      IDN_POS = 'IDN_POS'.freeze,

      # fr_mondial.
      FR_MONDIAL = 'FR_MONDIAL'.freeze,

      # DE DHL.
      DE_DHL = 'DE_DHL'.freeze,

      # hk_rpx.
      HK_RPX = 'HK_RPX'.freeze,

      # dhl_pieceid.
      DHL_PIECEID = 'DHL_PIECEID'.freeze,

      # vnpost_ems.
      VNPOST_EMS = 'VNPOST_EMS'.freeze,

      # rrdonnelley.
      RRDONNELLEY = 'RRDONNELLEY'.freeze,

      # dpd_de.
      DPD_DE = 'DPD_DE'.freeze,

      # delcart_in.
      DELCART_IN = 'DELCART_IN'.freeze,

      # imexglobalsolutions.
      IMEXGLOBALSOLUTIONS = 'IMEXGLOBALSOLUTIONS'.freeze,

      # ACOMMERCE.
      ACOMMERCE = 'ACOMMERCE'.freeze,

      # eurodis.
      EURODIS = 'EURODIS'.freeze,

      # CANPAR.
      CANPAR = 'CANPAR'.freeze,

      # GLS.
      GLS = 'GLS'.freeze,

      # Ecom Express.
      IND_ECOM = 'IND_ECOM'.freeze,

      # Envialia.
      ESP_ENVIALIA = 'ESP_ENVIALIA'.freeze,

      # dhl UK.
      DHL_UK = 'DHL_UK'.freeze,

      # SMSA Express.
      SMSA_EXPRESS = 'SMSA_EXPRESS'.freeze,

      # TNT France.
      TNT_FR = 'TNT_FR'.freeze,

      # DEX-I courier.
      DEX_I = 'DEX_I'.freeze,

      # Budbee courier.
      BUDBEE_WEBHOOK = 'BUDBEE_WEBHOOK'.freeze,

      # Copa Airlines Courier.
      COPA_COURIER = 'COPA_COURIER'.freeze,

      # Vietnam Post.
      VNM_VIETNAM_POST = 'VNM_VIETNAM_POST'.freeze,

      # DPD HongKong.
      DPD_HK = 'DPD_HK'.freeze,

      # Toll New Zealand.
      TOLL_NZ = 'TOLL_NZ'.freeze,

      # Echo courier.
      ECHO = 'ECHO'.freeze,

      # FedEx® Freight.
      FEDEX_FR = 'FEDEX_FR'.freeze,

      # Border Express.
      BORDEREXPRESS = 'BORDEREXPRESS'.freeze,

      # MailPlus (Japan).
      MAILPLUS_JPN = 'MAILPLUS_JPN'.freeze,

      # TNT UK Reference.
      TNT_UK_REFR = 'TNT_UK_REFR'.freeze,

      # KEC courier.
      KEC = 'KEC'.freeze,

      # DPD Romania.
      DPD_RO = 'DPD_RO'.freeze,

      # TNT_JP.
      TNT_JP = 'TNT_JP'.freeze,

      # TH_CJ.
      TH_CJ = 'TH_CJ'.freeze,

      # EC_CN.
      EC_CN = 'EC_CN'.freeze,

      # FASTWAY_UK.
      FASTWAY_UK = 'FASTWAY_UK'.freeze,

      # FASTWAY_US.
      FASTWAY_US = 'FASTWAY_US'.freeze,

      # GLS_DE.
      GLS_DE = 'GLS_DE'.freeze,

      # GLS_ES.
      GLS_ES = 'GLS_ES'.freeze,

      # GLS_FR.
      GLS_FR = 'GLS_FR'.freeze,

      # MONDIAL_BE.
      MONDIAL_BE = 'MONDIAL_BE'.freeze,

      # SGT_IT.
      SGT_IT = 'SGT_IT'.freeze,

      # TNT_CN.
      TNT_CN = 'TNT_CN'.freeze,

      # TNT_DE.
      TNT_DE = 'TNT_DE'.freeze,

      # TNT_ES.
      TNT_ES = 'TNT_ES'.freeze,

      # TNT_PL.
      TNT_PL = 'TNT_PL'.freeze,

      # PARCELFORCE.
      PARCELFORCE = 'PARCELFORCE'.freeze,

      # SWISS POST.
      SWISS_POST = 'SWISS_POST'.freeze,

      # TOLL IPEC.
      TOLL_IPEC = 'TOLL_IPEC'.freeze,

      # AIR 21.
      AIR_21 = 'AIR_21'.freeze,

      # AIRSPEED.
      AIRSPEED = 'AIRSPEED'.freeze,

      # BERT.
      BERT = 'BERT'.freeze,

      # BLUEDART.
      BLUEDART = 'BLUEDART'.freeze,

      # COLLECTPLUS.
      COLLECTPLUS = 'COLLECTPLUS'.freeze,

      # COURIERPLUS.
      COURIERPLUS = 'COURIERPLUS'.freeze,

      # COURIER POST.
      COURIER_POST = 'COURIER_POST'.freeze,

      # dhl_global_mail.
      DHL_GLOBAL_MAIL = 'DHL_GLOBAL_MAIL'.freeze,

      # dpd_uk.
      DPD_UK = 'DPD_UK'.freeze,

      # DELTEC DE.
      DELTEC_DE = 'DELTEC_DE'.freeze,

      # deutsche_de.
      DEUTSCHE_DE = 'DEUTSCHE_DE'.freeze,

      # DOTZOT.
      DOTZOT = 'DOTZOT'.freeze,

      # elta_gr.
      ELTA_GR = 'ELTA_GR'.freeze,

      # ems_cn.
      EMS_CN = 'EMS_CN'.freeze,

      # ECARGO.
      ECARGO = 'ECARGO'.freeze,

      # ENSENDA.
      ENSENDA = 'ENSENDA'.freeze,

      # fercam_it.
      FERCAM_IT = 'FERCAM_IT'.freeze,

      # fastway_za.
      FASTWAY_ZA = 'FASTWAY_ZA'.freeze,

      # fastway_au.
      FASTWAY_AU = 'FASTWAY_AU'.freeze,

      # first_logisitcs.
      FIRST_LOGISITCS = 'FIRST_LOGISITCS'.freeze,

      # GEODIS.
      GEODIS = 'GEODIS'.freeze,

      # GLOBEGISTICS.
      GLOBEGISTICS = 'GLOBEGISTICS'.freeze,

      # GREYHOUND.
      GREYHOUND = 'GREYHOUND'.freeze,

      # jetship_my.
      JETSHIP_MY = 'JETSHIP_MY'.freeze,

      # LION PARCEL.
      LION_PARCEL = 'LION_PARCEL'.freeze,

      # AEROFLASH.
      AEROFLASH = 'AEROFLASH'.freeze,

      # ONTRAC.
      ONTRAC = 'ONTRAC'.freeze,

      # SAGAWA.
      SAGAWA = 'SAGAWA'.freeze,

      # SIODEMKA.
      SIODEMKA = 'SIODEMKA'.freeze,

      # startrack.
      STARTRACK = 'STARTRACK'.freeze,

      # tnt_au.
      TNT_AU = 'TNT_AU'.freeze,

      # tnt_it.
      TNT_IT = 'TNT_IT'.freeze,

      # TRANSMISSION.
      TRANSMISSION = 'TRANSMISSION'.freeze,

      # YAMATO.
      YAMATO = 'YAMATO'.freeze,

      # dhl_it.
      DHL_IT = 'DHL_IT'.freeze,

      # dhl_at.
      DHL_AT = 'DHL_AT'.freeze,

      # LOGISTICSWORLDWIDE KR.
      LOGISTICSWORLDWIDE_KR = 'LOGISTICSWORLDWIDE_KR'.freeze,

      # gls_spain.
      GLS_SPAIN = 'GLS_SPAIN'.freeze,

      # amazon_uk_api.
      AMAZON_UK_API = 'AMAZON_UK_API'.freeze,

      # dpd_fr_reference.
      DPD_FR_REFERENCE = 'DPD_FR_REFERENCE'.freeze,

      # dhlparcel_uk.
      DHLPARCEL_UK = 'DHLPARCEL_UK'.freeze,

      # megasave.
      MEGASAVE = 'MEGASAVE'.freeze,

      # qualitypost.
      QUALITYPOST = 'QUALITYPOST'.freeze,

      # ids_logistics.
      IDS_LOGISTICS = 'IDS_LOGISTICS'.freeze,

      # joyingbox.
      JOYINGBOX1 = 'JOYINGBOX'.freeze,

      # panther_order_number.
      PANTHER_ORDER_NUMBER = 'PANTHER_ORDER_NUMBER'.freeze,

      # watkins_shepard.
      WATKINS_SHEPARD = 'WATKINS_SHEPARD'.freeze,

      # fasttrack.
      FASTTRACK = 'FASTTRACK'.freeze,

      # up_express.
      UP_EXPRESS = 'UP_EXPRESS'.freeze,

      # elogistica.
      ELOGISTICA = 'ELOGISTICA'.freeze,

      # ecourier.
      ECOURIER = 'ECOURIER'.freeze,

      # cj_philippines.
      CJ_PHILIPPINES = 'CJ_PHILIPPINES'.freeze,

      # speedex.
      SPEEDEX = 'SPEEDEX'.freeze,

      # orangeconnex.
      ORANGECONNEX = 'ORANGECONNEX'.freeze,

      # tecor.
      TECOR = 'TECOR'.freeze,

      # saee.
      SAEE = 'SAEE'.freeze,

      # gls_italy_ftp.
      GLS_ITALY_FTP = 'GLS_ITALY_FTP'.freeze,

      # delivere.
      DELIVERE = 'DELIVERE'.freeze,

      # yycom.
      YYCOM = 'YYCOM'.freeze,

      # Adicional Logistics.
      ADICIONAL_PT = 'ADICIONAL_PT'.freeze,

      # DKSH.
      DKSH = 'DKSH'.freeze,

      # Nippon Express.
      NIPPON_EXPRESS_FTP = 'NIPPON_EXPRESS_FTP'.freeze,

      # GO Logistics & Storage.
      GOLS = 'GOLS'.freeze,

      # FUJIE EXPRESS.
      FUJEXP = 'FUJEXP'.freeze,

      # QTrack.
      QTRACK = 'QTRACK'.freeze,

      # OM LOGISTICS LTD.
      OMLOGISTICS_API = 'OMLOGISTICS_API'.freeze,

      # GDPharm Logistics.
      GDPHARM = 'GDPHARM'.freeze,

      # MISUMI Group Inc..
      MISUMI_CN = 'MISUMI_CN'.freeze,

      # Rivo.
      AIR_CANADA = 'AIR_CANADA'.freeze,

      # City Express.
      CITY56_WEBHOOK = 'CITY56_WEBHOOK'.freeze,

      # Sagawa.
      SAGAWA_API = 'SAGAWA_API'.freeze,

      # KedaEX.
      KEDAEX = 'KEDAEX'.freeze,

      # Pgeon.
      PGEON_API = 'PGEON_API'.freeze,

      # We World Express.
      WEWORLDEXPRESS = 'WEWORLDEXPRESS'.freeze,

      # J&T International logistics.
      JT_LOGISTICS = 'JT_LOGISTICS'.freeze,

      # Trusk France.
      TRUSK = 'TRUSK'.freeze,

      # ViaXpress.
      VIAXPRESS = 'VIAXPRESS'.freeze,

      # DHL Supply Chain Indonesia.
      DHL_SUPPLYCHAIN_ID = 'DHL_SUPPLYCHAIN_ID'.freeze,

      # Zuellig Pharma Korea.
      ZUELLIGPHARMA_SFTP = 'ZUELLIGPHARMA_SFTP'.freeze,

      # Meest.
      MEEST = 'MEEST'.freeze,

      # Toll Priority.
      TOLL_PRIORITY = 'TOLL_PRIORITY'.freeze,

      # Mothership.
      MOTHERSHIP_API = 'MOTHERSHIP_API'.freeze,

      # Capital Transport.
      CAPITAL = 'CAPITAL'.freeze,

      # Europacket+.
      EUROPAKET_API = 'EUROPAKET_API'.freeze,

      # HFD.
      HFD = 'HFD'.freeze,

      # Tourline Express.
      TOURLINE_REFERENCE = 'TOURLINE_REFERENCE'.freeze,

      # GIO Express Inc.
      GIO_ECOURIER = 'GIO_ECOURIER'.freeze,

      # CN Logistics.
      CN_LOGISTICS = 'CN_LOGISTICS'.freeze,

      # Pandion.
      PANDION = 'PANDION'.freeze,

      # Bpost API.
      BPOST_API = 'BPOST_API'.freeze,

      # Passport Shipping.
      PASSPORTSHIPPING = 'PASSPORTSHIPPING'.freeze,

      # Pakajo World.
      PAKAJO = 'PAKAJO'.freeze,

      # DACHSER.
      DACHSER = 'DACHSER'.freeze,

      # Yusen Logistics.
      YUSEN_SFTP = 'YUSEN_SFTP'.freeze,

      # Shypmax.
      SHYPLITE = 'SHYPLITE'.freeze,

      # Xingyunyi Logistics.
      XYY = 'XYY'.freeze,

      # Metropolitan Warehouse & Delivery.
      MWD = 'MWD'.freeze,

      # Faxe Cargo.
      FAXECARGO = 'FAXECARGO'.freeze,

      # Groupe Mazet.
      MAZET = 'MAZET'.freeze,

      # First Logistics.
      FIRST_LOGISTICS_API = 'FIRST_LOGISTICS_API'.freeze,

      # SPRINT PACK.
      SPRINT_PACK = 'SPRINT_PACK'.freeze,

      # Hermes Germany.
      HERMES_DE_FTP = 'HERMES_DE_FTP'.freeze,

      # Concise.
      CONCISE = 'CONCISE'.freeze,

      # Kerry Express TaiWan.
      KERRY_EXPRESS_TW_API = 'KERRY_EXPRESS_TW_API'.freeze,

      # EWE Global Express.
      EWE = 'EWE'.freeze,

      # Fast Despatch Logistics Limited.
      FASTDESPATCH = 'FASTDESPATCH'.freeze,

      # AB Custom Group.
      ABCUSTOM_SFTP = 'ABCUSTOM_SFTP'.freeze,

      # Chazki.
      CHAZKI = 'CHAZKI'.freeze,

      # Shippie.
      SHIPPIE = 'SHIPPIE'.freeze,

      # GEODIS - Distribution & Express.
      GEODIS_API = 'GEODIS_API'.freeze,

      # Naqel Express.
      NAQEL_EXPRESS = 'NAQEL_EXPRESS'.freeze,

      # Papa.
      PAPA_WEBHOOK = 'PAPA_WEBHOOK'.freeze,

      # Forward Air.
      FORWARDAIR = 'FORWARDAIR'.freeze,

      # Dialogo Logistica.
      DIALOGO_LOGISTICA_API = 'DIALOGO_LOGISTICA_API'.freeze,

      # Lalamove.
      LALAMOVE_API = 'LALAMOVE_API'.freeze,

      # Tomydoor.
      TOMYDOOR = 'TOMYDOOR'.freeze,

      # Kronos Express.
      KRONOS_WEBHOOK = 'KRONOS_WEBHOOK'.freeze,

      # J&T CARGO.
      JTCARGO = 'JTCARGO'.freeze,

      # T-cat.
      T_CAT = 'T_CAT'.freeze,

      # Concise.
      CONCISE_WEBHOOK = 'CONCISE_WEBHOOK'.freeze,

      # Teleport.
      TELEPORT_WEBHOOK = 'TELEPORT_WEBHOOK'.freeze,

      # The Custom Companies.
      CUSTOMCO_API = 'CUSTOMCO_API'.freeze,

      # Shopee Xpress.
      SPX_TH = 'SPX_TH'.freeze,

      # Bollore Logistics.
      BOLLORE_LOGISTICS = 'BOLLORE_LOGISTICS'.freeze,

      # ClickLink.
      CLICKLINK_SFTP = 'CLICKLINK_SFTP'.freeze,

      # M3 Logistics.
      M3LOGISTICS = 'M3LOGISTICS'.freeze,

      # Vietnam Post.
      VNPOST_API = 'VNPOST_API'.freeze,

      # Axlehire.
      AXLEHIRE_FTP = 'AXLEHIRE_FTP'.freeze,

      # Shadowfax.
      SHADOWFAX = 'SHADOWFAX'.freeze,

      # EVRi.
      MYHERMES_UK_API = 'MYHERMES_UK_API'.freeze,

      # Daiichi Freight System Inc.
      DAIICHI = 'DAIICHI'.freeze,

      # Mensajeros Urbanos.
      MENSAJEROSURBANOS_API = 'MENSAJEROSURBANOS_API'.freeze,

      # PolarSpeed Inc.
      POLARSPEED = 'POLARSPEED'.freeze,

      # iDexpress Indonesia.
      IDEXPRESS_ID = 'IDEXPRESS_ID'.freeze,

      # Payo.
      PAYO = 'PAYO'.freeze,

      # Whistl.
      WHISTL_SFTP = 'WHISTL_SFTP'.freeze,

      # INTEX Paketdienst GmbH.
      INTEX_DE = 'INTEX_DE'.freeze,

      # Trans2u.
      TRANS2U = 'TRANS2U'.freeze,

      # Product Care Services Limited.
      PRODUCTCAREGROUP_SFTP = 'PRODUCTCAREGROUP_SFTP'.freeze,

      # Big Smart.
      BIGSMART = 'BIGSMART'.freeze,

      # Expeditors API Reference.
      EXPEDITORS_API_REF = 'EXPEDITORS_API_REF'.freeze,

      # AIT.
      AITWORLDWIDE_API = 'AITWORLDWIDE_API'.freeze,

      # World Courier.
      WORLDCOURIER = 'WORLDCOURIER'.freeze,

      # Quiqup.
      QUIQUP = 'QUIQUP'.freeze,

      # Agediss.
      AGEDISS_SFTP = 'AGEDISS_SFTP'.freeze,

      # Andreani.
      ANDREANI_API = 'ANDREANI_API'.freeze,

      # CRL Express.
      CRLEXPRESS = 'CRLEXPRESS'.freeze,

      # SMARTCAT.
      SMARTCAT = 'SMARTCAT'.freeze,

      # Crossflight Limited.
      CROSSFLIGHT = 'CROSSFLIGHT'.freeze,

      # Pro Carrier.
      PROCARRIER = 'PROCARRIER'.freeze,

      # DHL (Reference number).
      DHL_REFERENCE_API = 'DHL_REFERENCE_API'.freeze,

      # Seino.
      SEINO_API = 'SEINO_API'.freeze,

      # WSP Express.
      WSPEXPRESS = 'WSPEXPRESS'.freeze,

      # Kronos Express.
      KRONOS = 'KRONOS'.freeze,

      # Total Express.
      TOTAL_EXPRESS_API = 'TOTAL_EXPRESS_API'.freeze,

      # PARCLL.
      PARCLL = 'PARCLL'.freeze,

      # Xpedigo.
      XPEDIGO = 'XPEDIGO'.freeze,

      # StarTrack.
      STAR_TRACK_WEBHOOK = 'STAR_TRACK_WEBHOOK'.freeze,

      # Georgian Post.
      GPOST = 'GPOST'.freeze,

      # UCS.
      UCS = 'UCS'.freeze,

      # DMF.
      DMFGROUP = 'DMFGROUP'.freeze,

      # Coordinadora.
      COORDINADORA_API = 'COORDINADORA_API'.freeze,

      # Marken.
      MARKEN = 'MARKEN'.freeze,

      # NTL logistics.
      NTL = 'NTL'.freeze,

      # Red je Pakketje.
      REDJEPAKKETJE = 'REDJEPAKKETJE'.freeze,

      # Allied Express (FTP).
      ALLIED_EXPRESS_FTP = 'ALLIED_EXPRESS_FTP'.freeze,

      # Mondial Relay Spain(Punto Pack).
      MONDIALRELAY_ES = 'MONDIALRELAY_ES'.freeze,

      # Naeko Logistics.
      NAEKO_FTP = 'NAEKO_FTP'.freeze,

      # Mhi.
      MHI = 'MHI'.freeze,

      # Shippify, Inc.
      SHIPPIFY = 'SHIPPIFY'.freeze,

      # Malca Amit.
      MALCA_AMIT_API = 'MALCA_AMIT_API'.freeze,

      # J&T Express Singapore.
      JTEXPRESS_SG_API = 'JTEXPRESS_SG_API'.freeze,

      # DACHSER.
      DACHSER_WEB = 'DACHSER_WEB'.freeze,

      # Flight Logistics Group.
      FLIGHTLG = 'FLIGHTLG'.freeze,

      # Cago.
      CAGO = 'CAGO'.freeze,

      # ComOne Express.
      COM1EXPRESS = 'COM1EXPRESS'.freeze,

      # Tonami.
      TONAMI_FTP = 'TONAMI_FTP'.freeze,

      # PACKFLEET.
      PACKFLEET = 'PACKFLEET'.freeze,

      # Purolator International.
      PUROLATOR_INTERNATIONAL = 'PUROLATOR_INTERNATIONAL'.freeze,

      # Wineshipping.
      WINESHIPPING_WEBHOOK = 'WINESHIPPING_WEBHOOK'.freeze,

      # DHL Spain Domestic.
      DHL_ES_SFTP = 'DHL_ES_SFTP'.freeze,

      # 網家速配股份有限公司.
      PCHOME_API = 'PCHOME_API'.freeze,

      # Czech Post.
      CESKAPOSTA_API = 'CESKAPOSTA_API'.freeze,

      # Go Rush.
      GORUSH = 'GORUSH'.freeze,

      # HomeRunner.
      HOMERUNNER = 'HOMERUNNER'.freeze,

      # Amazon order.
      AMAZON_ORDER = 'AMAZON_ORDER'.freeze,

      # Estes Forwarding Worldwide.
      EFWNOW_API = 'EFWNOW_API'.freeze,

      # CBL Logistica (API).
      CBL_LOGISTICA_API = 'CBL_LOGISTICA_API'.freeze,

      # NimbusPost.
      NIMBUSPOST = 'NIMBUSPOST'.freeze,

      # Logwin Logistics.
      LOGWIN_LOGISTICS = 'LOGWIN_LOGISTICS'.freeze,

      # Sequoialog.
      NOWLOG_API = 'NOWLOG_API'.freeze,

      # DPD Netherlands.
      DPD_NL = 'DPD_NL'.freeze,

      # Dependable Supply Chain Services.
      GODEPENDABLE = 'GODEPENDABLE'.freeze,

      # Top Ideal Express.
      ESDEX = 'ESDEX'.freeze,

      # Kiitäjät.
      LOGISYSTEMS_SFTP = 'LOGISYSTEMS_SFTP'.freeze,

      # Expeditors.
      EXPEDITORS = 'EXPEDITORS'.freeze,

      # Snt Global Etrax.
      SNTGLOBAL_API = 'SNTGLOBAL_API'.freeze,

      # ShipX.
      SHIPX = 'SHIPX'.freeze,

      # Quickstat Courier LLC.
      QINTL_API = 'QINTL_API'.freeze,

      # Packs.
      PACKS = 'PACKS'.freeze,

      # PostNL International.
      POSTNL_INTERNATIONAL = 'POSTNL_INTERNATIONAL'.freeze,

      # Amazon.
      AMAZON_EMAIL_PUSH = 'AMAZON_EMAIL_PUSH'.freeze,

      # DHL.
      DHL_API = 'DHL_API'.freeze,

      # Shopee Express.
      SPX = 'SPX'.freeze,

      # AxleHire.
      AXLEHIRE = 'AXLEHIRE'.freeze,

      # ICS COURIER.
      ICSCOURIER = 'ICSCOURIER'.freeze,

      # Dialogo Logistica.
      DIALOGO_LOGISTICA = 'DIALOGO_LOGISTICA'.freeze,

      # ShunBang Express.
      SHUNBANG_EXPRESS = 'SHUNBANG_EXPRESS'.freeze,

      # TCS.
      TCS_API = 'TCS_API'.freeze,

      # SF Express China.
      SF_EXPRESS_CN = 'SF_EXPRESS_CN'.freeze,

      # Packeta.
      PACKETA = 'PACKETA'.freeze,

      # Teliway SIC Express.
      SIC_TELIWAY = 'SIC_TELIWAY'.freeze,

      # Mondial Relay France.
      MONDIALRELAY_FR = 'MONDIALRELAY_FR'.freeze,

      # InTime.
      INTIME_FTP = 'INTIME_FTP'.freeze,

      # 京东物流.
      JD_EXPRESS = 'JD_EXPRESS'.freeze,

      # Fastbox.
      FASTBOX = 'FASTBOX'.freeze,

      # Patheon Logistics.
      PATHEON = 'PATHEON'.freeze,

      # India Post Domestic.
      INDIA_POST = 'INDIA_POST'.freeze,

      # Tipsa Reference.
      TIPSA_REF = 'TIPSA_REF'.freeze,

      # Eco Freight.
      ECOFREIGHT = 'ECOFREIGHT'.freeze,

      # VOX SOLUCION EMPRESARIAL SRL.
      VOX = 'VOX'.freeze,

      # Direct Freight Express.
      DIRECTFREIGHT_AU_REF = 'DIRECTFREIGHT_AU_REF'.freeze,

      # Best Transport.
      BESTTRANSPORT_SFTP = 'BESTTRANSPORT_SFTP'.freeze,

      # Australia Post.
      AUSTRALIA_POST_API = 'AUSTRALIA_POST_API'.freeze,

      # FragilePAK.
      FRAGILEPAK_SFTP = 'FRAGILEPAK_SFTP'.freeze,

      # FlipXpress.
      FLIPXP = 'FLIPXP'.freeze,

      # Value Logistics.
      VALUE_WEBHOOK = 'VALUE_WEBHOOK'.freeze,

      # Daeshin.
      DAESHIN = 'DAESHIN'.freeze,

      # Sherpa.
      SHERPA = 'SHERPA'.freeze,

      # Metropolitan Warehouse & Delivery.
      MWD_API = 'MWD_API'.freeze,

      # SmartKargo.
      SMARTKARGO = 'SMARTKARGO'.freeze,

      # DNJ Express.
      DNJ_EXPRESS = 'DNJ_EXPRESS'.freeze,

      # Go People.
      GOPEOPLE = 'GOPEOPLE'.freeze,

      # mySendle.
      MYSENDLE_API = 'MYSENDLE_API'.freeze,

      # Aramex.
      ARAMEX_API = 'ARAMEX_API'.freeze,

      # Pidge.
      PIDGE = 'PIDGE'.freeze,

      # TP Logistic.
      THAIPARCELS = 'THAIPARCELS'.freeze,

      # Panther Reference.
      PANTHER_REFERENCE_API = 'PANTHER_REFERENCE_API'.freeze,

      # Posta Plus.
      POSTAPLUS1 = 'POSTAPLUS'.freeze,

      # BUFFALO.
      BUFFALO = 'BUFFALO'.freeze,

      # U-ENVIOS.
      U_ENVIOS = 'U_ENVIOS'.freeze,

      # Elite Express.
      ELITE_CO = 'ELITE_CO'.freeze,

      # Roche Internal Courier.
      ROCHE_INTERNAL_SFTP = 'ROCHE_INTERNAL_SFTP'.freeze,

      # DB Schenker Iceland.
      DBSCHENKER_ICELAND = 'DBSCHENKER_ICELAND'.freeze,

      # TNT France Reference.
      TNT_FR_REFERENCE = 'TNT_FR_REFERENCE'.freeze,

      # Newgistics API.
      NEWGISTICSAPI = 'NEWGISTICSAPI'.freeze,

      # Glovo.
      GLOVO = 'GLOVO'.freeze,

      # G.I.G.
      GWLOGIS_API = 'GWLOGIS_API'.freeze,

      # Spreetail.
      SPREETAIL_API = 'SPREETAIL_API'.freeze,

      # Moova.
      MOOVA = 'MOOVA'.freeze,

      # Plycon Transportation Group.
      PLYCONGROUP = 'PLYCONGROUP'.freeze,

      # USPS Informed Visibility - Webhook.
      USPS_WEBHOOK = 'USPS_WEBHOOK'.freeze,

      # maergo.
      REIMAGINEDELIVERY = 'REIMAGINEDELIVERY'.freeze,

      # Eurodifarm.
      EDF_FTP = 'EDF_FTP'.freeze,

      # DAO365.
      DAO365 = 'DAO365'.freeze,

      # BioCair.
      BIOCAIR_FTP = 'BIOCAIR_FTP'.freeze,

      # Ransa.
      RANSA_WEBHOOK = 'RANSA_WEBHOOK'.freeze,

      # SHIPXPRESS.
      SHIPXPRES = 'SHIPXPRES'.freeze,

      # Courant Plus.
      COURANT_PLUS_API = 'COURANT_PLUS_API'.freeze,

      # SHIPA.
      SHIPA = 'SHIPA'.freeze,

      # Home Logistics.
      HOMELOGISTICS = 'HOMELOGISTICS'.freeze,

      # DX.
      DX = 'DX'.freeze,

      # Poste Italiane Paccocelere.
      POSTE_ITALIANE_PACCOCELERE = 'POSTE_ITALIANE_PACCOCELERE'.freeze,

      # Toll Group.
      TOLL_WEBHOOK = 'TOLL_WEBHOOK'.freeze,

      # LCT do Brasil.
      LCTBR_API = 'LCTBR_API'.freeze,

      # DX Freight.
      DX_FREIGHT = 'DX_FREIGHT'.freeze,

      # DHL Express.
      DHL_SFTP = 'DHL_SFTP'.freeze,

      # Shiprocket X.
      SHIPROCKET = 'SHIPROCKET'.freeze,

      # Uber.
      UBER_WEBHOOK = 'UBER_WEBHOOK'.freeze,

      # Stat Overnight.
      STATOVERNIGHT = 'STATOVERNIGHT'.freeze,

      # Burd Delivery.
      BURD = 'BURD'.freeze,

      # Fastship Express.
      FASTSHIP = 'FASTSHIP'.freeze,

      # IB Venture.
      IBVENTURE_WEBHOOK = 'IBVENTURE_WEBHOOK'.freeze,

      # Gati-KWE.
      GATI_KWE_API = 'GATI_KWE_API'.freeze,

      # CryoPDP.
      CRYOPDP_FTP = 'CRYOPDP_FTP'.freeze,

      # HUBBED.
      HUBBED = 'HUBBED'.freeze,

      # Tipsa API.
      TIPSA_API = 'TIPSA_API'.freeze,

      # Aras Cargo.
      ARASKARGO = 'ARASKARGO'.freeze,

      # Thijs Logistiek.
      THIJS_NL = 'THIJS_NL'.freeze,

      # ATS Healthcare.
      ATSHEALTHCARE_REFERENCE = 'ATSHEALTHCARE_REFERENCE'.freeze,

      # 99minutos.
      ENUM_99MINUTOS = '99MINUTOS'.freeze,

      # Hellenic (Greece) Post.
      HELLENIC_POST = 'HELLENIC_POST'.freeze,

      # HSM Global.
      HSM_GLOBAL = 'HSM_GLOBAL'.freeze,

      # MNX.
      MNX = 'MNX'.freeze,

      # N&M Transfer Co., Inc..
      NMTRANSFER = 'NMTRANSFER'.freeze,

      # Logysto.
      LOGYSTO = 'LOGYSTO'.freeze,

      # India Post International.
      INDIA_POST_INT = 'INDIA_POST_INT'.freeze,

      # Swiship IN.
      AMAZON_FBA_SWISHIP_IN = 'AMAZON_FBA_SWISHIP_IN'.freeze,

      # SRT Transport.
      SRT_TRANSPORT = 'SRT_TRANSPORT'.freeze,

      # Bomi Group.
      BOMI = 'BOMI'.freeze,

      # Deliverr.
      DELIVERR_SFTP = 'DELIVERR_SFTP'.freeze,

      # HSDEXPRESS.
      HSDEXPRESS = 'HSDEXPRESS'.freeze,

      # SimpleTire.
      SIMPLETIRE_WEBHOOK = 'SIMPLETIRE_WEBHOOK'.freeze,

      # Hunter Express.
      HUNTER_EXPRESS_SFTP = 'HUNTER_EXPRESS_SFTP'.freeze,

      # UPS.
      UPS_API = 'UPS_API'.freeze,

      # WOO YOUNG LOGISTICS CO.,LTD..
      WOOYOUNG_LOGISTICS_SFTP = 'WOOYOUNG_LOGISTICS_SFTP'.freeze,

      # PHSE.
      PHSE_API = 'PHSE_API'.freeze,

      # Wish.
      WISH_EMAIL_PUSH = 'WISH_EMAIL_PUSH'.freeze,

      # Northline.
      NORTHLINE = 'NORTHLINE'.freeze,

      # Med Africa Logistics.
      MEDAFRICA = 'MEDAFRICA'.freeze,

      # DPD Austria.
      DPD_AT_SFTP = 'DPD_AT_SFTP'.freeze,

      # Anteraja.
      ANTERAJA = 'ANTERAJA'.freeze,

      # DHL Global Forwarding API.
      DHL_GLOBAL_FORWARDING_API = 'DHL_GLOBAL_FORWARDING_API'.freeze,

      # LBC EXPRESS INC..
      LBCEXPRESS_API = 'LBCEXPRESS_API'.freeze,

      # Sims Global.
      SIMSGLOBAL = 'SIMSGLOBAL'.freeze,

      # CDL Last Mile.
      CDLDELIVERS = 'CDLDELIVERS'.freeze,

      # TYP.
      TYP = 'TYP'.freeze,

      # Testing Courier.
      TESTING_COURIER_WEBHOOK = 'TESTING_COURIER_WEBHOOK'.freeze,

      # Pandago.
      PANDAGO_API = 'PANDAGO_API'.freeze,

      # Royal Mail.
      ROYAL_MAIL_FTP = 'ROYAL_MAIL_FTP'.freeze,

      # Thunder Express Australia.
      THUNDEREXPRESS = 'THUNDEREXPRESS'.freeze,

      # Secretlab.
      SECRETLAB_WEBHOOK = 'SECRETLAB_WEBHOOK'.freeze,

      # Setel Express.
      SETEL = 'SETEL'.freeze,

      # JD Worldwide.
      JD_WORLDWIDE = 'JD_WORLDWIDE'.freeze,

      # DPD Russia.
      DPD_RU_API = 'DPD_RU_API'.freeze,

      # Argents Express Group.
      ARGENTS_WEBHOOK = 'ARGENTS_WEBHOOK'.freeze,

      # Post ONE.
      POSTONE = 'POSTONE'.freeze,

      # Tusk Logistics.
      TUSKLOGISTICS = 'TUSKLOGISTICS'.freeze,

      # Rhenus Logistics UK.
      RHENUS_UK_API = 'RHENUS_UK_API'.freeze,

      # Yamato Singapore.
      TAQBIN_SG_API = 'TAQBIN_SG_API'.freeze,

      # Inntralog GmbH.
      INNTRALOG_SFTP = 'INNTRALOG_SFTP'.freeze,

      # Day & Ross.
      DAYROSS = 'DAYROSS'.freeze,

      # Correos Express (API).
      CORREOSEXPRESS_API = 'CORREOSEXPRESS_API'.freeze,

      # International Seur API.
      INTERNATIONAL_SEUR_API = 'INTERNATIONAL_SEUR_API'.freeze,

      # Yodel API.
      YODEL_API = 'YODEL_API'.freeze,

      # Hero Express.
      HEROEXPRESS = 'HEROEXPRESS'.freeze,

      # DHL supply chain India.
      DHL_SUPPLYCHAIN_IN = 'DHL_SUPPLYCHAIN_IN'.freeze,

      # Urgent Cargus.
      URGENT_CARGUS = 'URGENT_CARGUS'.freeze,

      # FRONTdoor Collective.
      FRONTDOORCORP = 'FRONTDOORCORP'.freeze,

      # J&T Express Philippines.
      JTEXPRESS_PH = 'JTEXPRESS_PH'.freeze,

      # Parcelstars.
      PARCELSTARS_WEBHOOK = 'PARCELSTARS_WEBHOOK'.freeze,

      # DPD Slovakia.
      DPD_SK_SFTP = 'DPD_SK_SFTP'.freeze,

      # Movianto.
      MOVIANTO = 'MOVIANTO'.freeze,

      # Ozeparts Shipping.
      OZEPARTS_SHIPPING = 'OZEPARTS_SHIPPING'.freeze,

      # KargomKolay (CargoMini).
      KARGOMKOLAY = 'KARGOMKOLAY'.freeze,

      # Trunkrs.
      TRUNKRS = 'TRUNKRS'.freeze,

      # Omni Returns.
      OMNIRPS_WEBHOOK = 'OMNIRPS_WEBHOOK'.freeze,

      # Chile Express.
      CHILEXPRESS = 'CHILEXPRESS'.freeze,

      # Testing Courier.
      TESTING_COURIER = 'TESTING_COURIER'.freeze,

      # JNE (API).
      JNE_API = 'JNE_API'.freeze,

      # BJS Distribution, Storage & Couriers - FTP.
      BJSHOMEDELIVERY_FTP = 'BJSHOMEDELIVERY_FTP'.freeze,

      # D Express.
      DEXPRESS_WEBHOOK = 'DEXPRESS_WEBHOOK'.freeze,

      # USPS API.
      USPS_API = 'USPS_API'.freeze,

      # TransVirtual.
      TRANSVIRTUAL = 'TRANSVIRTUAL'.freeze,

      # solistica.
      SOLISTICA_API = 'SOLISTICA_API'.freeze,

      # Chienventure.
      CHIENVENTURE_WEBHOOK = 'CHIENVENTURE_WEBHOOK'.freeze,

      # DPD UK.
      DPD_UK_SFTP = 'DPD_UK_SFTP'.freeze,

      # InPost.
      INPOST_UK = 'INPOST_UK'.freeze,

      # Javit.
      JAVIT = 'JAVIT'.freeze,

      # ZTO Express China.
      ZTO_DOMESTIC = 'ZTO_DOMESTIC'.freeze,

      # DHL Global Forwarding Guatemala.
      DHL_GT_API = 'DHL_GT_API'.freeze,

      # CEVA Package.
      CEVA_TRACKING = 'CEVA_TRACKING'.freeze,

      # Komon Express.
      KOMON_EXPRESS = 'KOMON_EXPRESS'.freeze,

      # East West Courier Pte Ltd.
      EASTWESTCOURIER_FTP = 'EASTWESTCOURIER_FTP'.freeze,

      # Danniao.
      DANNIAO = 'DANNIAO'.freeze,

      # Spectran.
      SPECTRAN = 'SPECTRAN'.freeze,

      # Deliver-iT.
      DELIVER_IT = 'DELIVER_IT'.freeze,

      # Relais Colis.
      RELAISCOLIS = 'RELAISCOLIS'.freeze,

      # GLS Spain.
      GLS_SPAIN_API = 'GLS_SPAIN_API'.freeze,

      # PostPlus.
      POSTPLUS = 'POSTPLUS'.freeze,

      # Airterra.
      AIRTERRA = 'AIRTERRA'.freeze,

      # GIO Express Ecourier.
      GIO_ECOURIER_API = 'GIO_ECOURIER_API'.freeze,

      # DPD Switzerland.
      DPD_CH_SFTP = 'DPD_CH_SFTP'.freeze,

      # FedEx®.
      FEDEX_API = 'FEDEX_API'.freeze,

      # INTERSMARTTRANS & SOLUTIONS SL.
      INTERSMARTTRANS = 'INTERSMARTTRANS'.freeze,

      # Hermes UK.
      HERMES_UK_SFTP = 'HERMES_UK_SFTP'.freeze,

      # Exelot Ltd..
      EXELOT_FTP = 'EXELOT_FTP'.freeze,

      # DHL GLOBAL FORWARDING PANAMÁ.
      DHL_PA_API = 'DHL_PA_API'.freeze,

      # Vir Transport.
      VIRTRANSPORT_SFTP = 'VIRTRANSPORT_SFTP'.freeze,

      # Worldnet Logistics.
      WORLDNET = 'WORLDNET'.freeze,

      # Instabox.
      INSTABOX_WEBHOOK = 'INSTABOX_WEBHOOK'.freeze,

      # Keuhne + Nagel Global.
      KNG = 'KNG'.freeze,

      # Flash Express.
      FLASHEXPRESS_WEBHOOK = 'FLASHEXPRESS_WEBHOOK'.freeze,

      # Magyar Posta.
      MAGYAR_POSTA_API = 'MAGYAR_POSTA_API'.freeze,

      # WeShip.
      WESHIP_API = 'WESHIP_API'.freeze,

      # Ohi.
      OHI_WEBHOOK = 'OHI_WEBHOOK'.freeze,

      # MUDITA.
      MUDITA = 'MUDITA'.freeze,

      # Bluedart.
      BLUEDART_API = 'BLUEDART_API'.freeze,

      # T-cat.
      T_CAT_API = 'T_CAT_API'.freeze,

      # ADS Express.
      ADS = 'ADS'.freeze,

      # HR Parcel.
      HERMES_IT = 'HERMES_IT'.freeze,

      # FitzMark.
      FITZMARK_API = 'FITZMARK_API'.freeze,

      # Posti API.
      POSTI_API = 'POSTI_API'.freeze,

      # SMSA Express.
      SMSA_EXPRESS_WEBHOOK = 'SMSA_EXPRESS_WEBHOOK'.freeze,

      # Tamer Logistics.
      TAMERGROUP_WEBHOOK = 'TAMERGROUP_WEBHOOK'.freeze,

      # Livrapide.
      LIVRAPIDE = 'LIVRAPIDE'.freeze,

      # Nippon Express.
      NIPPON_EXPRESS = 'NIPPON_EXPRESS'.freeze,

      # Better Trucks.
      BETTERTRUCKS = 'BETTERTRUCKS'.freeze,

      # FAN COURIER EXPRESS.
      FAN = 'FAN'.freeze,

      # USPS Flats (Pitney Bowes).
      PB_USPSFLATS_FTP = 'PB_USPSFLATS_FTP'.freeze,

      # Parcel Right.
      PARCELRIGHT = 'PARCELRIGHT'.freeze,

      # iThink Logistics.
      ITHINKLOGISTICS = 'ITHINKLOGISTICS'.freeze,

      # Kerry Logistics.
      KERRY_EXPRESS_TH_WEBHOOK = 'KERRY_EXPRESS_TH_WEBHOOK'.freeze,

      # eCoutier.
      ECOUTIER = 'ECOUTIER'.freeze,

      # SENHONG INTERNATIONAL LOGISTICS.
      SHOWL = 'SHOWL'.freeze,

      # BRT Bartolini API.
      BRT_IT_API = 'BRT_IT_API'.freeze,

      # Rixon Logistics.
      RIXONHK_API = 'RIXONHK_API'.freeze,

      # DB Schenker.
      DBSCHENKER_API = 'DBSCHENKER_API'.freeze,

      # Ilyang logistics.
      ILYANGLOGIS = 'ILYANGLOGIS'.freeze,

      # Mail Boxes Etc..
      MAIL_BOX_ETC = 'MAIL_BOX_ETC'.freeze,

      # WeShip.
      WESHIP = 'WESHIP'.freeze,

      # DHL eCommerce Solutions.
      DHL_GLOBAL_MAIL_API = 'DHL_GLOBAL_MAIL_API'.freeze,

      # Activos24.
      ACTIVOS24_API = 'ACTIVOS24_API'.freeze,

      # ATS Healthcare.
      ATSHEALTHCARE = 'ATSHEALTHCARE'.freeze,

      # Luwjistik.
      LUWJISTIK = 'LUWJISTIK'.freeze,

      # Gebrüder Weiss.
      GW_WORLD = 'GW_WORLD'.freeze,

      # fairsenden.
      FAIRSENDEN_API = 'FAIRSENDEN_API'.freeze,

      # SerVIP.
      SERVIP_WEBHOOK = 'SERVIP_WEBHOOK'.freeze,

      # Swiship.
      SWISHIP = 'SWISHIP'.freeze,

      # Transport Ambientales.
      TANET = 'TANET'.freeze,

      # SHENZHEN HOTSIN CARGO INT'L FORWARDING CO.,LTD.
      HOTSIN_CARGO = 'HOTSIN_CARGO'.freeze,

      # Direx.
      DIREX = 'DIREX'.freeze,

      # HuanTong.
      HUANTONG = 'HUANTONG'.freeze,

      # iMile.
      IMILE_API = 'IMILE_API'.freeze,

      # Au Express.
      AUEXPRESS = 'AUEXPRESS'.freeze,

      # NYT SUPPLY CHAIN LOGISTICS Co.,LTD.
      NYTLOGISTICS = 'NYTLOGISTICS'.freeze,

      # DSV Futurewave.
      DSV_REFERENCE = 'DSV_REFERENCE'.freeze,

      # Novofarma.
      NOVOFARMA_WEBHOOK = 'NOVOFARMA_WEBHOOK'.freeze,

      # AIT.
      AITWORLDWIDE_SFTP = 'AITWORLDWIDE_SFTP'.freeze,

      # Olive.
      SHOPOLIVE = 'SHOPOLIVE'.freeze,

      # Fast & Furious.
      FNF_ZA = 'FNF_ZA'.freeze,

      # DHL eCommerce Greater China.
      DHL_ECOMMERCE_GC = 'DHL_ECOMMERCE_GC'.freeze,

      # Fetchr.
      FETCHR = 'FETCHR'.freeze,

      # Starlinks Global.
      STARLINKS_API = 'STARLINKS_API'.freeze,

      # YYEXPRESS.
      YYEXPRESS = 'YYEXPRESS'.freeze,

      # Servientrega.
      SERVIENTREGA = 'SERVIENTREGA'.freeze,

      # HanJin.
      HANJIN = 'HANJIN'.freeze,

      # Spanish Seur.
      SPANISH_SEUR_FTP = 'SPANISH_SEUR_FTP'.freeze,

      # DX (B2B).
      DX_B2B_CONNUM = 'DX_B2B_CONNUM'.freeze,

      # Helthjem.
      HELTHJEM_API = 'HELTHJEM_API'.freeze,

      # Inexpost.
      INEXPOST = 'INEXPOST'.freeze,

      # A2B Express Logistics.
      A2B_BA = 'A2B_BA'.freeze,

      # Rhenus Logistics.
      RHENUS_GROUP = 'RHENUS_GROUP'.freeze,

      # Sber Logistics.
      SBERLOGISTICS_RU = 'SBERLOGISTICS_RU'.freeze,

      # Malca-Amit.
      MALCA_AMIT = 'MALCA_AMIT'.freeze,

      # Professional Parcel Logistics.
      PPL = 'PPL'.freeze,

      # OSM Worldwide.
      OSM_WORLDWIDE_SFTP = 'OSM_WORLDWIDE_SFTP'.freeze,

      # ACI Logistix.
      ACILOGISTIX = 'ACILOGISTIX'.freeze,

      # Optima Courier.
      OPTIMACOURIER = 'OPTIMACOURIER'.freeze,

      # Nova Poshta API.
      NOVA_POSHTA_API = 'NOVA_POSHTA_API'.freeze,

      # Loggi.
      LOGGI = 'LOGGI'.freeze,

      # YiFan Express.
      YIFAN = 'YIFAN'.freeze,

      # My DynaLogic.
      MYDYNALOGIC = 'MYDYNALOGIC'.freeze,

      # Morning Global.
      MORNINGLOBAL = 'MORNINGLOBAL'.freeze,

      # Concise.
      CONCISE_API = 'CONCISE_API'.freeze,

      # Falcon Express.
      FXTRAN = 'FXTRAN'.freeze,

      # Deliver Your Parcel.
      DELIVERYOURPARCEL_ZA = 'DELIVERYOURPARCEL_ZA'.freeze,

      # uParcel.
      UPARCEL = 'UPARCEL'.freeze,

      # Mobi Logistica.
      MOBI_BR = 'MOBI_BR'.freeze,

      # T&W Delivery.
      LOGINEXT_WEBHOOK = 'LOGINEXT_WEBHOOK'.freeze,

      # EMS.
      EMS = 'EMS'.freeze,

      # Speedy.
      SPEEDY = 'SPEEDY'.freeze,

      # Zoom.
      ZOOM_RED = 'ZOOM_RED'.freeze,

      # Navlungo.
      NAVLUNGO = 'NAVLUNGO'.freeze,

      # Castle Parcels.
      CASTLEPARCELS = 'CASTLEPARCELS'.freeze,

      # Weee.
      WEEE = 'WEEE'.freeze,

      # Packaly.
      PACKALY = 'PACKALY'.freeze,

      # Yunhuipost.
      YUNHUIPOST = 'YUNHUIPOST'.freeze,

      # YouParcel.
      YOUPARCEL = 'YOUPARCEL'.freeze,

      # Leman.
      LEMAN = 'LEMAN'.freeze,

      # Moovin.
      MOOVIN = 'MOOVIN'.freeze,

      # Urb-it.
      URB_IT = 'URB_IT'.freeze,

      # Multientrega.
      MULTIENTREGAPANAMA = 'MULTIENTREGAPANAMA'.freeze,

      # Jusdasr.
      JUSDASR = 'JUSDASR'.freeze,

      # Discount Post.
      DISCOUNTPOST = 'DISCOUNTPOST'.freeze,

      # Rhenus Logistics UK.
      RHENUS_UK = 'RHENUS_UK'.freeze,

      # Swiship JP.
      SWISHIP_JP = 'SWISHIP_JP'.freeze,

      # GLS USA.
      GLS_US = 'GLS_US'.freeze,

      # Southwestern Motor Transport. Inc.
      SMTL = 'SMTL'.freeze,

      # Discount Post Emega.
      EMEGA = 'EMEGA'.freeze,

      # EXPRESSONE Slovenia.
      EXPRESSONE_SV = 'EXPRESSONE_SV'.freeze,

      # hepsiJET.
      HEPSIJET = 'HEPSIJET'.freeze,

      # Welivery.
      WELIVERY = 'WELIVERY'.freeze,

      # Bringer Parcel Services.
      BRINGER = 'BRINGER'.freeze,

      # EasyRoutes.
      EASYROUTES = 'EASYROUTES'.freeze,

      # MRW.
      MRW = 'MRW'.freeze,

      # RPM.
      RPM = 'RPM'.freeze,

      # DPD Portugal.
      DPD_PRT = 'DPD_PRT'.freeze,

      # GLS Romania.
      GLS_ROMANIA = 'GLS_ROMANIA'.freeze,

      # LM Parcel.
      LMPARCEL = 'LMPARCEL'.freeze,

      # GTA GSM.
      GTAGSM = 'GTAGSM'.freeze,

      # DOMINO.
      DOMINO = 'DOMINO'.freeze,

      # eShipper.
      ESHIPPER = 'ESHIPPER'.freeze,

      # Transpak Inc..
      TRANSPAK = 'TRANSPAK'.freeze,

      # Xindus.
      XINDUS = 'XINDUS'.freeze,

      # Aoyue.
      AOYUE = 'AOYUE'.freeze,

      # Easyparcel.
      EASYPARCEL = 'EASYPARCEL'.freeze,

      # EXPRESSONE.
      EXPRESSONE = 'EXPRESSONE'.freeze,

      # Sendeo Kargo.
      SENDEO_KARGO = 'SENDEO_KARGO'.freeze,

      # Speedaf Express.
      SPEEDAF = 'SPEEDAF'.freeze,

      # eTower.
      ETOWER = 'ETOWER'.freeze,

      # GC Express.
      GCX = 'GCX'.freeze,

      # Ninjavan Vietnam.
      NINJAVAN_VN = 'NINJAVAN_VN'.freeze,

      # Allegro.
      ALLEGRO = 'ALLEGRO'.freeze,

      # Jumppoint.
      JUMPPOINT = 'JUMPPOINT'.freeze,

      # ShipGlobal.
      SHIPGLOBAL_US = 'SHIPGLOBAL_US'.freeze,

      # Kinisi Transport Pty Ltd.
      KINISI = 'KINISI'.freeze,

      # Oakh Harbour Freight Lines.
      OAKH = 'OAKH'.freeze,

      # American West.
      AWEST = 'AWEST'.freeze,

      # Barsan Global Lojistik.
      BARSAN = 'BARSAN'.freeze,

      # Energo Logistic.
      ENERGOLOGISTIC = 'ENERGOLOGISTIC'.freeze,

      # Madrooex.
      MADROOEX = 'MADROOEX'.freeze,

      # GoBolt.
      GOBOLT = 'GOBOLT'.freeze,

      # Swiss Universal Express.
      SWISS_UNIVERSAL_EXPRESS = 'SWISS_UNIVERSAL_EXPRESS'.freeze,

      # IOR Direct Solutions.
      IORDIRECT = 'IORDIRECT'.freeze,

      # xmszm.
      XMSZM = 'XMSZM'.freeze,

      # GLS Hungary.
      GLS_HUN = 'GLS_HUN'.freeze,

      # Sendy Express.
      SENDY = 'SENDY'.freeze,

      # Brauns Express.
      BRAUNSEXPRESS = 'BRAUNSEXPRESS'.freeze,

      # Grand Slam Express.
      GRANDSLAMEXPRESS = 'GRANDSLAMEXPRESS'.freeze,

      # XGS.
      XGS = 'XGS'.freeze,

      # OTS.
      OTSCHILE = 'OTSCHILE'.freeze,

      # Pack-Up.
      PACK_UP = 'PACK_UP'.freeze,

      # Parcelstars.
      PARCELSTARS = 'PARCELSTARS'.freeze,

      # Team Express Service LLC.
      TEAMEXPRESSLLC = 'TEAMEXPRESSLLC'.freeze,

      # Asyad Express.
      ASYADEXPRESS = 'ASYADEXPRESS'.freeze,

      # TDN.
      TDN = 'TDN'.freeze,

      # Early Bird.
      EARLYBIRD = 'EARLYBIRD'.freeze,

      # Cacesa.
      CACESA = 'CACESA'.freeze,

      # Parceljet.
      PARCELJET = 'PARCELJET'.freeze,

      # MNG Kargo.
      MNG_KARGO = 'MNG_KARGO'.freeze,

      # Super Pac Line.
      SUPERPACKLINE = 'SUPERPACKLINE'.freeze,

      # SpeedX.
      SPEEDX = 'SPEEDX'.freeze,

      # Vesyl.
      VESYL = 'VESYL'.freeze,

      # Sky King.
      SKYKING = 'SKYKING'.freeze,

      # DIR.
      DIRMENSAJERIA = 'DIRMENSAJERIA'.freeze,

      # Netlogix.
      NETLOGIXGROUP = 'NETLOGIXGROUP'.freeze,

      # ZYEX.
      ZYOU = 'ZYOU'.freeze,

      # Jawar.
      JAWAR = 'JAWAR'.freeze,

      # Associate Global Systems.
      AGSYSTEMS = 'AGSYSTEMS'.freeze,

      # GPS.
      GPS = 'GPS'.freeze,

      # PTT Kargo.
      PTT_KARGO = 'PTT_KARGO'.freeze,

      # Maergo.
      MAERGO = 'MAERGO'.freeze,

      # AICS.
      ARIHANTCOURIER = 'ARIHANTCOURIER'.freeze,

      # VicTas Freight Express.
      VTFE = 'VTFE'.freeze,

      # Yunant.
      YUNANT = 'YUNANT'.freeze,

      # Urbify.
      URBIFY = 'URBIFY'.freeze,

      # pack-man.
      PACK_MAN = 'PACK_MAN'.freeze,

      # LIEFERGRUN.
      LIEFERGRUN = 'LIEFERGRUN'.freeze,

      # Obibox.
      OBIBOX = 'OBIBOX'.freeze,

      # Paikeda.
      PAIKEDA = 'PAIKEDA'.freeze,

      # Scotty.
      SCOTTY = 'SCOTTY'.freeze,

      # Intelcom.
      INTELCOM_CA = 'INTELCOM_CA'.freeze,

      # swe.
      SWE = 'SWE'.freeze,

      # Asendia Global.
      ASENDIA = 'ASENDIA'.freeze,

      # DPD Austria.
      DPD_AT = 'DPD_AT'.freeze,

      # Relay.
      RELAY = 'RELAY'.freeze,

      # ATA.
      ATA = 'ATA'.freeze,

      # SkyExpress Internationals.
      SKYEXPRESS_INTERNATIONAL = 'SKYEXPRESS_INTERNATIONAL'.freeze,

      # Surat Kargo.
      SURAT_KARGO = 'SURAT_KARGO'.freeze,

      # SG LINK.
      SGLINK = 'SGLINK'.freeze,

      # FleetOptics.
      FLEETOPTICSINC = 'FLEETOPTICSINC'.freeze,

      # shopline.
      SHOPLINE = 'SHOPLINE'.freeze,

      # PIGGYSHIP.
      PIGGYSHIP = 'PIGGYSHIP'.freeze,

      # LogoiX.
      LOGOIX = 'LOGOIX'.freeze,

      # Kolay Gelsin.
      KOLAY_GELSIN = 'KOLAY_GELSIN'.freeze,

      # Associated Couriers.
      ASSOCIATED_COURIERS = 'ASSOCIATED_COURIERS'.freeze,

      # ups-checker.
      UPS_CHECKER = 'UPS_CHECKER'.freeze,

      # Wineshipping.
      WINESHIPPING = 'WINESHIPPING'.freeze,

      # Spedisci online.
      SPEDISCI = 'SPEDISCI'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
