# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The shipping information.
  class ShippingInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The recipient's name.
    # @return [String]
    attr_accessor :name

    # The shipping method that is associated with this order.
    # @return [String]
    attr_accessor :method

    # A simple postal address with coarse-grained fields. Do not use for an
    # international address. Use for backward compatibility only. Does not
    # contain phone.
    # @return [SimplePostalAddressCoarseGrained]
    attr_accessor :address

    # A simple postal address with coarse-grained fields. Do not use for an
    # international address. Use for backward compatibility only. Does not
    # contain phone.
    # @return [SimplePostalAddressCoarseGrained]
    attr_accessor :secondary_shipping_address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['method'] = 'method'
      @_hash['address'] = 'address'
      @_hash['secondary_shipping_address'] = 'secondary_shipping_address'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        method
        address
        secondary_shipping_address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, method: SKIP, address: SKIP,
                   secondary_shipping_address: SKIP)
      @name = name unless name == SKIP
      @method = method unless method == SKIP
      @address = address unless address == SKIP
      unless secondary_shipping_address == SKIP
        @secondary_shipping_address =
          secondary_shipping_address
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      method = hash.key?('method') ? hash['method'] : SKIP
      address = SimplePostalAddressCoarseGrained.from_hash(hash['address']) if hash['address']
      if hash['secondary_shipping_address']
        secondary_shipping_address = SimplePostalAddressCoarseGrained.from_hash(hash['secondary_shipping_address'])
      end

      # Create object from extracted values.
      ShippingInformation.new(name: name,
                              method: method,
                              address: address,
                              secondary_shipping_address: secondary_shipping_address)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, method: #{@method}, address: #{@address},"\
      " secondary_shipping_address: #{@secondary_shipping_address}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, method: #{@method.inspect}, address:"\
      " #{@address.inspect}, secondary_shipping_address: #{@secondary_shipping_address.inspect}>"
    end
  end
end
