# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The store information.
  class StoreInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ID of a store for a merchant in the system of record.
    # @return [String]
    attr_accessor :store_id

    # The terminal ID for the checkout stand in a merchant store.
    # @return [String]
    attr_accessor :terminal_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['store_id'] = 'store_id'
      @_hash['terminal_id'] = 'terminal_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        store_id
        terminal_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(store_id: SKIP, terminal_id: SKIP)
      @store_id = store_id unless store_id == SKIP
      @terminal_id = terminal_id unless terminal_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      store_id = hash.key?('store_id') ? hash['store_id'] : SKIP
      terminal_id = hash.key?('terminal_id') ? hash['terminal_id'] : SKIP

      # Create object from extracted values.
      StoreInformation.new(store_id: store_id,
                           terminal_id: terminal_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} store_id: #{@store_id}, terminal_id: #{@terminal_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} store_id: #{@store_id.inspect}, terminal_id: #{@terminal_id.inspect}>"
    end
  end
end
