# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Indicates if this is a `first` or `subsequent` payment using a stored
  # payment source (also referred to as stored credential or card on file).
  class StoredPaymentSourceUsageType
    STORED_PAYMENT_SOURCE_USAGE_TYPE = [
      # Indicates the Initial/First payment with a payment_source that is
      # intended to be stored upon successful processing of the payment.
      FIRST = 'FIRST'.freeze,

      # Indicates a payment using a stored payment_source which has been
      # successfully used previously for a payment.
      SUBSEQUENT = 'SUBSEQUENT'.freeze,

      # Indicates that PayPal will derive the value of `FIRST` or `SUBSEQUENT`
      # based on data available to PayPal.
      DERIVED = 'DERIVED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
