# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The name of the party.
  class SubscriptionPayerName < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The prefix, or title, to the party's name.
    # @return [String]
    attr_accessor :prefix

    # When the party is a person, the party's given, or first, name.
    # @return [String]
    attr_accessor :given_name

    # When the party is a person, the party's surname or family name. Also known
    # as the last name. Required when the party is a person. Use also to store
    # multiple surnames including the matronymic, or mother's, surname.
    # @return [String]
    attr_accessor :surname

    # When the party is a person, the party's middle name. Use also to store
    # multiple middle names including the patronymic, or father's, middle name.
    # @return [String]
    attr_accessor :middle_name

    # The suffix for the party's name.
    # @return [String]
    attr_accessor :suffix

    # When the party is a person, the party's full name.
    # @return [String]
    attr_accessor :full_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['prefix'] = 'prefix'
      @_hash['given_name'] = 'given_name'
      @_hash['surname'] = 'surname'
      @_hash['middle_name'] = 'middle_name'
      @_hash['suffix'] = 'suffix'
      @_hash['full_name'] = 'full_name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        prefix
        given_name
        surname
        middle_name
        suffix
        full_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(prefix: SKIP, given_name: SKIP, surname: SKIP,
                   middle_name: SKIP, suffix: SKIP, full_name: SKIP)
      @prefix = prefix unless prefix == SKIP
      @given_name = given_name unless given_name == SKIP
      @surname = surname unless surname == SKIP
      @middle_name = middle_name unless middle_name == SKIP
      @suffix = suffix unless suffix == SKIP
      @full_name = full_name unless full_name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      prefix = hash.key?('prefix') ? hash['prefix'] : SKIP
      given_name = hash.key?('given_name') ? hash['given_name'] : SKIP
      surname = hash.key?('surname') ? hash['surname'] : SKIP
      middle_name = hash.key?('middle_name') ? hash['middle_name'] : SKIP
      suffix = hash.key?('suffix') ? hash['suffix'] : SKIP
      full_name = hash.key?('full_name') ? hash['full_name'] : SKIP

      # Create object from extracted values.
      SubscriptionPayerName.new(prefix: prefix,
                                given_name: given_name,
                                surname: surname,
                                middle_name: middle_name,
                                suffix: suffix,
                                full_name: full_name)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} prefix: #{@prefix}, given_name: #{@given_name}, surname: #{@surname},"\
      " middle_name: #{@middle_name}, suffix: #{@suffix}, full_name: #{@full_name}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} prefix: #{@prefix.inspect}, given_name: #{@given_name.inspect}, surname:"\
      " #{@surname.inspect}, middle_name: #{@middle_name.inspect}, suffix: #{@suffix.inspect},"\
      " full_name: #{@full_name.inspect}>"
    end
  end
end
