# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The billing cycle details.
  class SubscriptionBillingCycle < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The pricing scheme details.
    # @return [SubscriptionPricingScheme]
    attr_accessor :pricing_scheme

    # The frequency of the billing cycle.
    # @return [Frequency]
    attr_accessor :frequency

    # The tenure type of the billing cycle. In case of a plan having trial
    # cycle, only 2 trial cycles are allowed per plan.
    # @return [TenureType]
    attr_accessor :tenure_type

    # The order in which this cycle is to run among other billing cycles. For
    # example, a trial billing cycle has a `sequence` of `1` while a regular
    # billing cycle has a `sequence` of `2`, so that trial cycle runs before the
    # regular cycle.
    # @return [Integer]
    attr_accessor :sequence

    # The number of times this billing cycle gets executed. Trial billing cycles
    # can only be executed a finite number of times (value between 1 and 999 for
    # total_cycles). Regular billing cycles can be executed infinite times
    # (value of 0 for total_cycles) or a finite number of times (value between 1
    # and 999 for total_cycles).
    # @return [Integer]
    attr_accessor :total_cycles

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pricing_scheme'] = 'pricing_scheme'
      @_hash['frequency'] = 'frequency'
      @_hash['tenure_type'] = 'tenure_type'
      @_hash['sequence'] = 'sequence'
      @_hash['total_cycles'] = 'total_cycles'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pricing_scheme
        total_cycles
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(frequency:, tenure_type:, sequence:, pricing_scheme: SKIP,
                   total_cycles: 1)
      @pricing_scheme = pricing_scheme unless pricing_scheme == SKIP
      @frequency = frequency
      @tenure_type = tenure_type
      @sequence = sequence
      @total_cycles = total_cycles unless total_cycles == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      frequency = Frequency.from_hash(hash['frequency']) if hash['frequency']
      tenure_type = hash.key?('tenure_type') ? hash['tenure_type'] : nil
      sequence = hash.key?('sequence') ? hash['sequence'] : nil
      pricing_scheme = SubscriptionPricingScheme.from_hash(hash['pricing_scheme']) if
        hash['pricing_scheme']
      total_cycles = hash['total_cycles'] ||= 1

      # Create object from extracted values.
      SubscriptionBillingCycle.new(frequency: frequency,
                                   tenure_type: tenure_type,
                                   sequence: sequence,
                                   pricing_scheme: pricing_scheme,
                                   total_cycles: total_cycles)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} pricing_scheme: #{@pricing_scheme}, frequency: #{@frequency}, tenure_type:"\
      " #{@tenure_type}, sequence: #{@sequence}, total_cycles: #{@total_cycles}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} pricing_scheme: #{@pricing_scheme.inspect}, frequency:"\
      " #{@frequency.inspect}, tenure_type: #{@tenure_type.inspect}, sequence:"\
      " #{@sequence.inspect}, total_cycles: #{@total_cycles.inspect}>"
    end
  end
end
