# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The pricing scheme details.
  class SubscriptionPricingScheme < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The version of the pricing scheme.
    # @return [Integer]
    attr_accessor :version

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :fixed_price

    # The pricing model for tiered plan. The `tiers` parameter is required.
    # @return [SubscriptionPricingModel]
    attr_accessor :pricing_model

    # An array of pricing tiers which are used for billing volume/tiered plans.
    # pricing_model field has to be specified.
    # @return [Array[PricingTier]]
    attr_accessor :tiers

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :create_time

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :update_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['version'] = 'version'
      @_hash['fixed_price'] = 'fixed_price'
      @_hash['pricing_model'] = 'pricing_model'
      @_hash['tiers'] = 'tiers'
      @_hash['create_time'] = 'create_time'
      @_hash['update_time'] = 'update_time'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        version
        fixed_price
        pricing_model
        tiers
        create_time
        update_time
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(version: SKIP, fixed_price: SKIP, pricing_model: SKIP,
                   tiers: SKIP, create_time: SKIP, update_time: SKIP)
      @version = version unless version == SKIP
      @fixed_price = fixed_price unless fixed_price == SKIP
      @pricing_model = pricing_model unless pricing_model == SKIP
      @tiers = tiers unless tiers == SKIP
      @create_time = create_time unless create_time == SKIP
      @update_time = update_time unless update_time == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      version = hash.key?('version') ? hash['version'] : SKIP
      fixed_price = Money.from_hash(hash['fixed_price']) if hash['fixed_price']
      pricing_model = hash.key?('pricing_model') ? hash['pricing_model'] : SKIP
      # Parameter is an array, so we need to iterate through it
      tiers = nil
      unless hash['tiers'].nil?
        tiers = []
        hash['tiers'].each do |structure|
          tiers << (PricingTier.from_hash(structure) if structure)
        end
      end

      tiers = SKIP unless hash.key?('tiers')
      create_time = hash.key?('create_time') ? hash['create_time'] : SKIP
      update_time = hash.key?('update_time') ? hash['update_time'] : SKIP

      # Create object from extracted values.
      SubscriptionPricingScheme.new(version: version,
                                    fixed_price: fixed_price,
                                    pricing_model: pricing_model,
                                    tiers: tiers,
                                    create_time: create_time,
                                    update_time: update_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} version: #{@version}, fixed_price: #{@fixed_price}, pricing_model:"\
      " #{@pricing_model}, tiers: #{@tiers}, create_time: #{@create_time}, update_time:"\
      " #{@update_time}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} version: #{@version.inspect}, fixed_price: #{@fixed_price.inspect},"\
      " pricing_model: #{@pricing_model.inspect}, tiers: #{@tiers.inspect}, create_time:"\
      " #{@create_time.inspect}, update_time: #{@update_time.inspect}>"
    end
  end
end
