# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The subscription details.
  class Subscription < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The PayPal-generated ID for the subscription.
    # @return [String]
    attr_accessor :id

    # The ID of the plan.
    # @return [String]
    attr_accessor :plan_id

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :start_time

    # The quantity of the product in the subscription.
    # @return [String]
    attr_accessor :quantity

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :shipping_amount

    # The subscriber response information.
    # @return [Subscriber]
    attr_accessor :subscriber

    # The billing details for the subscription. If the subscription was or is
    # active, these fields are populated.
    # @return [SubscriptionBillingInformation]
    attr_accessor :billing_info

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :create_time

    # The date and time, in [Internet date and time
    # format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are
    # required while fractional seconds are optional. Note: The regular
    # expression provides guidance but does not reject all invalid dates.
    # @return [String]
    attr_accessor :update_time

    # The custom id for the subscription. Can be invoice id.
    # @return [String]
    attr_accessor :custom_id

    # Indicates whether the subscription has overridden any plan attributes.
    # @return [TrueClass | FalseClass]
    attr_accessor :plan_overridden

    # The plan details.
    # @return [PlanDetails]
    attr_accessor :plan

    # An array of request-related [HATEOAS
    # links](/docs/api/reference/api-responses/#hateoas-links).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['plan_id'] = 'plan_id'
      @_hash['start_time'] = 'start_time'
      @_hash['quantity'] = 'quantity'
      @_hash['shipping_amount'] = 'shipping_amount'
      @_hash['subscriber'] = 'subscriber'
      @_hash['billing_info'] = 'billing_info'
      @_hash['create_time'] = 'create_time'
      @_hash['update_time'] = 'update_time'
      @_hash['custom_id'] = 'custom_id'
      @_hash['plan_overridden'] = 'plan_overridden'
      @_hash['plan'] = 'plan'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        plan_id
        start_time
        quantity
        shipping_amount
        subscriber
        billing_info
        create_time
        update_time
        custom_id
        plan_overridden
        plan
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, plan_id: SKIP, start_time: SKIP, quantity: SKIP,
                   shipping_amount: SKIP, subscriber: SKIP, billing_info: SKIP,
                   create_time: SKIP, update_time: SKIP, custom_id: SKIP,
                   plan_overridden: SKIP, plan: SKIP, links: SKIP)
      @id = id unless id == SKIP
      @plan_id = plan_id unless plan_id == SKIP
      @start_time = start_time unless start_time == SKIP
      @quantity = quantity unless quantity == SKIP
      @shipping_amount = shipping_amount unless shipping_amount == SKIP
      @subscriber = subscriber unless subscriber == SKIP
      @billing_info = billing_info unless billing_info == SKIP
      @create_time = create_time unless create_time == SKIP
      @update_time = update_time unless update_time == SKIP
      @custom_id = custom_id unless custom_id == SKIP
      @plan_overridden = plan_overridden unless plan_overridden == SKIP
      @plan = plan unless plan == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      plan_id = hash.key?('plan_id') ? hash['plan_id'] : SKIP
      start_time = hash.key?('start_time') ? hash['start_time'] : SKIP
      quantity = hash.key?('quantity') ? hash['quantity'] : SKIP
      shipping_amount = Money.from_hash(hash['shipping_amount']) if hash['shipping_amount']
      subscriber = Subscriber.from_hash(hash['subscriber']) if hash['subscriber']
      billing_info = SubscriptionBillingInformation.from_hash(hash['billing_info']) if
        hash['billing_info']
      create_time = hash.key?('create_time') ? hash['create_time'] : SKIP
      update_time = hash.key?('update_time') ? hash['update_time'] : SKIP
      custom_id = hash.key?('custom_id') ? hash['custom_id'] : SKIP
      plan_overridden =
        hash.key?('plan_overridden') ? hash['plan_overridden'] : SKIP
      plan = PlanDetails.from_hash(hash['plan']) if hash['plan']
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      Subscription.new(id: id,
                       plan_id: plan_id,
                       start_time: start_time,
                       quantity: quantity,
                       shipping_amount: shipping_amount,
                       subscriber: subscriber,
                       billing_info: billing_info,
                       create_time: create_time,
                       update_time: update_time,
                       custom_id: custom_id,
                       plan_overridden: plan_overridden,
                       plan: plan,
                       links: links)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, plan_id: #{@plan_id}, start_time: #{@start_time}, quantity:"\
      " #{@quantity}, shipping_amount: #{@shipping_amount}, subscriber: #{@subscriber},"\
      " billing_info: #{@billing_info}, create_time: #{@create_time}, update_time:"\
      " #{@update_time}, custom_id: #{@custom_id}, plan_overridden: #{@plan_overridden}, plan:"\
      " #{@plan}, links: #{@links}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, plan_id: #{@plan_id.inspect}, start_time:"\
      " #{@start_time.inspect}, quantity: #{@quantity.inspect}, shipping_amount:"\
      " #{@shipping_amount.inspect}, subscriber: #{@subscriber.inspect}, billing_info:"\
      " #{@billing_info.inspect}, create_time: #{@create_time.inspect}, update_time:"\
      " #{@update_time.inspect}, custom_id: #{@custom_id.inspect}, plan_overridden:"\
      " #{@plan_overridden.inspect}, plan: #{@plan.inspect}, links: #{@links.inspect}>"
    end
  end
end
