# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The breakdown details for the amount. Includes the gross, tax, fee, and
  # shipping amounts.
  class SubscriptionAmountWithBreakdown < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :gross_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :total_item_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :fee_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :shipping_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :tax_amount

    # The currency and amount for a financial transaction, such as a balance or
    # payment due.
    # @return [Money]
    attr_accessor :net_amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['gross_amount'] = 'gross_amount'
      @_hash['total_item_amount'] = 'total_item_amount'
      @_hash['fee_amount'] = 'fee_amount'
      @_hash['shipping_amount'] = 'shipping_amount'
      @_hash['tax_amount'] = 'tax_amount'
      @_hash['net_amount'] = 'net_amount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        total_item_amount
        fee_amount
        shipping_amount
        tax_amount
        net_amount
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(gross_amount:, total_item_amount: SKIP, fee_amount: SKIP,
                   shipping_amount: SKIP, tax_amount: SKIP, net_amount: SKIP)
      @gross_amount = gross_amount
      @total_item_amount = total_item_amount unless total_item_amount == SKIP
      @fee_amount = fee_amount unless fee_amount == SKIP
      @shipping_amount = shipping_amount unless shipping_amount == SKIP
      @tax_amount = tax_amount unless tax_amount == SKIP
      @net_amount = net_amount unless net_amount == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      gross_amount = Money.from_hash(hash['gross_amount']) if hash['gross_amount']
      total_item_amount = Money.from_hash(hash['total_item_amount']) if hash['total_item_amount']
      fee_amount = Money.from_hash(hash['fee_amount']) if hash['fee_amount']
      shipping_amount = Money.from_hash(hash['shipping_amount']) if hash['shipping_amount']
      tax_amount = Money.from_hash(hash['tax_amount']) if hash['tax_amount']
      net_amount = Money.from_hash(hash['net_amount']) if hash['net_amount']

      # Create object from extracted values.
      SubscriptionAmountWithBreakdown.new(gross_amount: gross_amount,
                                          total_item_amount: total_item_amount,
                                          fee_amount: fee_amount,
                                          shipping_amount: shipping_amount,
                                          tax_amount: tax_amount,
                                          net_amount: net_amount)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} gross_amount: #{@gross_amount}, total_item_amount: #{@total_item_amount},"\
      " fee_amount: #{@fee_amount}, shipping_amount: #{@shipping_amount}, tax_amount:"\
      " #{@tax_amount}, net_amount: #{@net_amount}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} gross_amount: #{@gross_amount.inspect}, total_item_amount:"\
      " #{@total_item_amount.inspect}, fee_amount: #{@fee_amount.inspect}, shipping_amount:"\
      " #{@shipping_amount.inspect}, tax_amount: #{@tax_amount.inspect}, net_amount:"\
      " #{@net_amount.inspect}>"
    end
  end
end
