# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The pricing model for tiered plan. The `tiers` parameter is required.
  class SubscriptionPricingModel
    SUBSCRIPTION_PRICING_MODEL = [
      # A volume pricing model.
      VOLUME = 'VOLUME'.freeze,

      # A tiered pricing model.
      TIERED = 'TIERED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
