# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The subscriber request information .
  class SubscriberRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name of the party.
    # @return [Name]
    attr_accessor :name

    # The phone information.
    # @return [PhoneWithType]
    attr_accessor :phone

    # The shipping details.
    # @return [ShippingDetails]
    attr_accessor :shipping_address

    # The payment source definition. To be eligible to create subscription using
    # debit or credit card, you will need to sign up here
    # (https://www.paypal.com/bizsignup/entry/product/ppcp). Please note, its
    # available only for non-3DS cards and for merchants in US and AU regions.
    # @return [SubscriptionPaymentSource]
    attr_accessor :payment_source

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['phone'] = 'phone'
      @_hash['shipping_address'] = 'shipping_address'
      @_hash['payment_source'] = 'payment_source'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        phone
        shipping_address
        payment_source
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, phone: SKIP, shipping_address: SKIP,
                   payment_source: SKIP)
      @name = name unless name == SKIP
      @phone = phone unless phone == SKIP
      @shipping_address = shipping_address unless shipping_address == SKIP
      @payment_source = payment_source unless payment_source == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = Name.from_hash(hash['name']) if hash['name']
      phone = PhoneWithType.from_hash(hash['phone']) if hash['phone']
      shipping_address = ShippingDetails.from_hash(hash['shipping_address']) if
        hash['shipping_address']
      payment_source = SubscriptionPaymentSource.from_hash(hash['payment_source']) if
        hash['payment_source']

      # Create object from extracted values.
      SubscriberRequest.new(name: name,
                            phone: phone,
                            shipping_address: shipping_address,
                            payment_source: payment_source)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, phone: #{@phone}, shipping_address: #{@shipping_address},"\
      " payment_source: #{@payment_source}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, phone: #{@phone.inspect}, shipping_address:"\
      " #{@shipping_address.inspect}, payment_source: #{@payment_source.inspect}>"
    end
  end
end
