# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The status of the subscription.
  class SubscriptionStatus
    SUBSCRIPTION_STATUS = [
      # The subscription is created but not yet approved by the buyer.
      APPROVAL_PENDING = 'APPROVAL_PENDING'.freeze,

      # The buyer has approved the subscription.
      APPROVED = 'APPROVED'.freeze,

      # The subscription is active.
      ACTIVE = 'ACTIVE'.freeze,

      # The subscription is suspended.
      SUSPENDED = 'SUSPENDED'.freeze,

      # The subscription is cancelled.
      CANCELLED = 'CANCELLED'.freeze,

      # The subscription is expired.
      EXPIRED = 'EXPIRED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = APPROVAL_PENDING)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'approval_pending' then APPROVAL_PENDING
      when 'approved' then APPROVED
      when 'active' then ACTIVE
      when 'suspended' then SUSPENDED
      when 'cancelled' then CANCELLED
      when 'expired' then EXPIRED
      else
        default_value
      end
    end
  end
end
