# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The payment source used to fund the payment.
  class SubscriptionPaymentSourceResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The payment card used to fund the payment. Card can be a credit or debit
    # card.
    # @return [CardResponseWithBillingAddress]
    attr_accessor :card

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card'] = 'card'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        card
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(card: SKIP)
      @card = card unless card == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card = CardResponseWithBillingAddress.from_hash(hash['card']) if hash['card']

      # Create object from extracted values.
      SubscriptionPaymentSourceResponse.new(card: card)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} card: #{@card}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} card: #{@card.inspect}>"
    end
  end
end
