# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The customer's tax ID type.
  class TaxIdType
    TAX_ID_TYPE = [
      # The individual tax ID type, typically is 11 characters long.
      BR_CPF = 'BR_CPF'.freeze,

      # The business tax ID type, typically is 14 characters long.
      BR_CNPJ = 'BR_CNPJ'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
