# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The tax details.
  class Taxes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The percentage, as a fixed-point, signed decimal number. For example,
    # define a 19.99% interest rate as `19.99`.
    # @return [String]
    attr_accessor :percentage

    # Indicates whether the tax was already included in the billing amount.
    # @return [TrueClass | FalseClass]
    attr_accessor :inclusive

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['percentage'] = 'percentage'
      @_hash['inclusive'] = 'inclusive'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        inclusive
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(percentage:, inclusive: true)
      @percentage = percentage
      @inclusive = inclusive unless inclusive == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      percentage = hash.key?('percentage') ? hash['percentage'] : nil
      inclusive = hash['inclusive'] ||= true

      # Create object from extracted values.
      Taxes.new(percentage: percentage,
                inclusive: inclusive)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} percentage: #{@percentage}, inclusive: #{@inclusive}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} percentage: #{@percentage.inspect}, inclusive: #{@inclusive.inspect}>"
    end
  end
end
