# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Results of 3D Secure Authentication.
  class ThreeDSecureCardAuthenticationResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transactions status result identifier. The outcome of the issuer's
    # authentication.
    # @return [PaResStatus]
    attr_accessor :authentication_status

    # Status of Authentication eligibility.
    # @return [EnrollmentStatus]
    attr_accessor :enrollment_status

    # The externally received 3ds authentication id, to be returned in card
    # detokenization response.
    # @return [String]
    attr_accessor :authentication_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['authentication_status'] = 'authentication_status'
      @_hash['enrollment_status'] = 'enrollment_status'
      @_hash['authentication_id'] = 'authentication_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        authentication_status
        enrollment_status
        authentication_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(authentication_status: SKIP, enrollment_status: SKIP,
                   authentication_id: SKIP)
      @authentication_status = authentication_status unless authentication_status == SKIP
      @enrollment_status = enrollment_status unless enrollment_status == SKIP
      @authentication_id = authentication_id unless authentication_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      authentication_status =
        hash.key?('authentication_status') ? hash['authentication_status'] : SKIP
      enrollment_status =
        hash.key?('enrollment_status') ? hash['enrollment_status'] : SKIP
      authentication_id =
        hash.key?('authentication_id') ? hash['authentication_id'] : SKIP

      # Create object from extracted values.
      ThreeDSecureCardAuthenticationResponse.new(authentication_status: authentication_status,
                                                 enrollment_status: enrollment_status,
                                                 authentication_id: authentication_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} authentication_status: #{@authentication_status}, enrollment_status:"\
      " #{@enrollment_status}, authentication_id: #{@authentication_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} authentication_status: #{@authentication_status.inspect},"\
      " enrollment_status: #{@enrollment_status.inspect}, authentication_id:"\
      " #{@authentication_id.inspect}>"
    end
  end
end
