# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The transaction details.
  class TransactionDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The transaction information.
    # @return [TransactionInformation]
    attr_accessor :transaction_info

    # The payer information.
    # @return [PayerInformation]
    attr_accessor :payer_info

    # The shipping information.
    # @return [ShippingInformation]
    attr_accessor :shipping_info

    # The cart information.
    # @return [CartInformation]
    attr_accessor :cart_info

    # The store information.
    # @return [StoreInformation]
    attr_accessor :store_info

    # The auction information.
    # @return [AuctionInformation]
    attr_accessor :auction_info

    # The incentive details.
    # @return [IncentiveInformation]
    attr_accessor :incentive_info

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transaction_info'] = 'transaction_info'
      @_hash['payer_info'] = 'payer_info'
      @_hash['shipping_info'] = 'shipping_info'
      @_hash['cart_info'] = 'cart_info'
      @_hash['store_info'] = 'store_info'
      @_hash['auction_info'] = 'auction_info'
      @_hash['incentive_info'] = 'incentive_info'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        transaction_info
        payer_info
        shipping_info
        cart_info
        store_info
        auction_info
        incentive_info
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transaction_info: SKIP, payer_info: SKIP,
                   shipping_info: SKIP, cart_info: SKIP, store_info: SKIP,
                   auction_info: SKIP, incentive_info: SKIP)
      @transaction_info = transaction_info unless transaction_info == SKIP
      @payer_info = payer_info unless payer_info == SKIP
      @shipping_info = shipping_info unless shipping_info == SKIP
      @cart_info = cart_info unless cart_info == SKIP
      @store_info = store_info unless store_info == SKIP
      @auction_info = auction_info unless auction_info == SKIP
      @incentive_info = incentive_info unless incentive_info == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      transaction_info = TransactionInformation.from_hash(hash['transaction_info']) if
        hash['transaction_info']
      payer_info = PayerInformation.from_hash(hash['payer_info']) if hash['payer_info']
      shipping_info = ShippingInformation.from_hash(hash['shipping_info']) if
        hash['shipping_info']
      cart_info = CartInformation.from_hash(hash['cart_info']) if hash['cart_info']
      store_info = StoreInformation.from_hash(hash['store_info']) if hash['store_info']
      auction_info = AuctionInformation.from_hash(hash['auction_info']) if hash['auction_info']
      incentive_info = IncentiveInformation.from_hash(hash['incentive_info']) if
        hash['incentive_info']

      # Create object from extracted values.
      TransactionDetails.new(transaction_info: transaction_info,
                             payer_info: payer_info,
                             shipping_info: shipping_info,
                             cart_info: cart_info,
                             store_info: store_info,
                             auction_info: auction_info,
                             incentive_info: incentive_info)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_info: #{@transaction_info}, payer_info: #{@payer_info},"\
      " shipping_info: #{@shipping_info}, cart_info: #{@cart_info}, store_info: #{@store_info},"\
      " auction_info: #{@auction_info}, incentive_info: #{@incentive_info}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} transaction_info: #{@transaction_info.inspect}, payer_info:"\
      " #{@payer_info.inspect}, shipping_info: #{@shipping_info.inspect}, cart_info:"\
      " #{@cart_info.inspect}, store_info: #{@store_info.inspect}, auction_info:"\
      " #{@auction_info.inspect}, incentive_info: #{@incentive_info.inspect}>"
    end
  end
end
