# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The Universal Product Code type.
  class UpcType
    UPC_TYPE = [
      # TODO: Write general description for UPC_A
      UPC_A = 'UPC-A'.freeze,

      # TODO: Write general description for UPC_B
      UPC_B = 'UPC-B'.freeze,

      # TODO: Write general description for UPC_C
      UPC_C = 'UPC-C'.freeze,

      # TODO: Write general description for UPC_D
      UPC_D = 'UPC-D'.freeze,

      # TODO: Write general description for UPC_E
      UPC_E = 'UPC-E'.freeze,

      # TODO: Write general description for UPC_2
      UPC_2 = 'UPC-2'.freeze,

      # TODO: Write general description for UPC_5
      UPC_5 = 'UPC-5'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = UPC_A)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'upc_a' then UPC_A
      when 'upc_b' then UPC_B
      when 'upc_c' then UPC_C
      when 'upc_d' then UPC_D
      when 'upc_e' then UPC_E
      when 'upc_2' then UPC_2
      when 'upc_5' then UPC_5
      else
        default_value
      end
    end
  end
end
