# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # The update pricing scheme request details.
  class UpdatePricingScheme < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The billing cycle sequence.
    # @return [Integer]
    attr_accessor :billing_cycle_sequence

    # The pricing scheme details.
    # @return [SubscriptionPricingScheme]
    attr_accessor :pricing_scheme

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['billing_cycle_sequence'] = 'billing_cycle_sequence'
      @_hash['pricing_scheme'] = 'pricing_scheme'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(billing_cycle_sequence:, pricing_scheme:)
      @billing_cycle_sequence = billing_cycle_sequence
      @pricing_scheme = pricing_scheme
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      billing_cycle_sequence =
        hash.key?('billing_cycle_sequence') ? hash['billing_cycle_sequence'] : nil
      pricing_scheme = SubscriptionPricingScheme.from_hash(hash['pricing_scheme']) if
        hash['pricing_scheme']

      # Create object from extracted values.
      UpdatePricingScheme.new(billing_cycle_sequence: billing_cycle_sequence,
                              pricing_scheme: pricing_scheme)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_cycle_sequence: #{@billing_cycle_sequence}, pricing_scheme:"\
      " #{@pricing_scheme}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} billing_cycle_sequence: #{@billing_cycle_sequence.inspect}, pricing_scheme:"\
      " #{@pricing_scheme.inspect}>"
    end
  end
end
