# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The vault status.
  class VaultStatus
    VAULT_STATUS = [
      # The payment source has been saved in your customer's vault. This vault
      # status reflects `/v3/vault` status.
      VAULTED = 'VAULTED'.freeze,

      # DEPRECATED. The payment source has been saved in your customer's vault.
      # This status applies to deprecated integration patterns and will not be
      # returned for v3/vault integrations.
      CREATED = 'CREATED'.freeze,

      # Customer has approved the action of saving the specified payment_source
      # into their vault. Use v3/vault/payment-tokens with given setup_token to
      # save the payment source in the vault
      APPROVED = 'APPROVED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
