# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # User Action on action to be performed after a successful payer approval.
  class VaultUserAction
    VAULT_USER_ACTION = [
      # After you redirect the customer to the PayPal payment page, a Setup Now
      # button appears. Use this option when no additional inputs are needed
      # from merchant site and to create the billing agreement immediately when
      # the customer clicks Setup Now.
      SETUP_NOW = 'SETUP_NOW'.freeze,

      # After you redirect the customer to the PayPal payment page, a Continue
      # button appears. Use this option when you want to redirect the customer
      # from the completed payment page to the merchant site for additional
      # inputs without immediately creating the billing agreement.
      CONTINUE = 'CONTINUE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = SETUP_NOW)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'setup_now' then SETUP_NOW
      when 'continue' then CONTINUE
      else
        default_value
      end
    end
  end
end
