# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # A resource representing a request to vault Apple Pay.
  class VaultApplePayRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Encrypted Apple Pay token, containing card information. This token would
    # be base64 encoded.
    # @return [String]
    attr_accessor :token

    # The payment card to be used to fund a payment. Can be a credit or debit
    # card.
    # @return [ApplePayRequestCard]
    attr_accessor :card

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash['card'] = 'card'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        token
        card
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(token: SKIP, card: SKIP)
      @token = token unless token == SKIP
      @card = card unless card == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = hash.key?('token') ? hash['token'] : SKIP
      card = ApplePayRequestCard.from_hash(hash['card']) if hash['card']

      # Create object from extracted values.
      VaultApplePayRequest.new(token: token,
                               card: card)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token}, card: #{@card}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} token: #{@token.inspect}, card: #{@card.inspect}>"
    end
  end
end
