# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # Vault Instruction on action to be performed after a successful payer
  # approval.
  class VaultInstructionAction
    VAULT_INSTRUCTION_ACTION = [
      # Vault the payment method after API caller performs a successful POST on
      # Payment Tokens.
      ON_CREATE_PAYMENT_TOKENS = 'ON_CREATE_PAYMENT_TOKENS'.freeze,

      # Vault the payment method on successful payer authentication and
      # approval.
      ON_PAYER_APPROVAL = 'ON_PAYER_APPROVAL'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ON_CREATE_PAYMENT_TOKENS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'on_create_payment_tokens' then ON_CREATE_PAYMENT_TOKENS
      when 'on_payer_approval' then ON_PAYER_APPROVAL
      else
        default_value
      end
    end
  end
end
