# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # A resource representing an experience context of vault a venmo account.
  class VenmoExperienceContext < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The label that overrides the business name in the PayPal account on the
    # PayPal site. The pattern is defined by an external party and supports
    # Unicode.
    # @return [String]
    attr_accessor :brand_name

    # The shipping preference. This only applies to PayPal payment source.
    # @return [ExperienceContextShippingPreference]
    attr_accessor :shipping_preference

    # DEPRECATED. Vault Instruction on action to be performed after a successful
    # payer approval.
    # @return [VaultInstructionAction]
    attr_accessor :vault_instruction

    # User Action on action to be performed after a successful payer approval.
    # @return [VaultUserAction]
    attr_accessor :user_action

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['brand_name'] = 'brand_name'
      @_hash['shipping_preference'] = 'shipping_preference'
      @_hash['vault_instruction'] = 'vault_instruction'
      @_hash['user_action'] = 'user_action'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        brand_name
        shipping_preference
        vault_instruction
        user_action
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(
      brand_name: SKIP,
      shipping_preference: ExperienceContextShippingPreference::GET_FROM_FILE,
      vault_instruction: SKIP, user_action: VaultUserAction::CONTINUE
    )
      @brand_name = brand_name unless brand_name == SKIP
      @shipping_preference = shipping_preference unless shipping_preference == SKIP
      @vault_instruction = vault_instruction unless vault_instruction == SKIP
      @user_action = user_action unless user_action == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      brand_name = hash.key?('brand_name') ? hash['brand_name'] : SKIP
      shipping_preference =
        hash['shipping_preference'] ||= ExperienceContextShippingPreference::GET_FROM_FILE
      vault_instruction =
        hash.key?('vault_instruction') ? hash['vault_instruction'] : SKIP
      user_action = hash['user_action'] ||= VaultUserAction::CONTINUE

      # Create object from extracted values.
      VenmoExperienceContext.new(brand_name: brand_name,
                                 shipping_preference: shipping_preference,
                                 vault_instruction: vault_instruction,
                                 user_action: user_action)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} brand_name: #{@brand_name}, shipping_preference: #{@shipping_preference},"\
      " vault_instruction: #{@vault_instruction}, user_action: #{@user_action}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} brand_name: #{@brand_name.inspect}, shipping_preference:"\
      " #{@shipping_preference.inspect}, vault_instruction: #{@vault_instruction.inspect},"\
      " user_action: #{@user_action.inspect}>"
    end
  end
end
