# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # SubscriptionsController
  class SubscriptionsController < BaseController
    # Creates a plan that defines pricing and billing cycle details for
    # subscriptions.
    # @param [String] prefer Optional parameter: The preferred server response
    # upon successful completion of the request. Value is: return=minimal. The
    # server returns a minimal response to optimize communication between the
    # API caller and the server. A minimal response includes the id, status and
    # HATEOAS links. return=representation. The server returns a complete
    # resource representation, including the current state of the resource.
    # @param [String] paypal_request_id Optional parameter: The server stores
    # keys for 72 hours.
    # @param [PlanRequest] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_billing_plan(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/plans',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .header_param(new_parameter(options['prefer'], key: 'Prefer'))
                   .header_param(new_parameter(options['paypal_request_id'], key: 'PayPal-Request-Id'))
                   .body_param(new_parameter(options['body']))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(BillingPlan.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Lists billing plans.
    # @param [String] prefer Optional parameter: The preferred server response
    # upon successful completion of the request. Value is: return=minimal. The
    # server returns a minimal response to optimize communication between the
    # API caller and the server. A minimal response includes the id, name,
    # description and HATEOAS links. return=representation. The server returns a
    # complete resource representation, including the current state of the
    # resource.
    # @param [String] product_id Optional parameter: Filters the response by a
    # Product ID.
    # @param [Integer] page_size Optional parameter: The number of items to
    # return in the response.
    # @param [Integer] page Optional parameter: A non-zero integer which is the
    # start index of the entire list of items to return in the response. The
    # combination of `page=1` and `page_size=20` returns the first 20 items. The
    # combination of `page=2` and `page_size=20` returns the next 20 items.
    # @param [TrueClass | FalseClass] total_required Optional parameter:
    # Indicates whether to show the total count in the response.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_billing_plans(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/billing/plans',
                                     Server::DEFAULT)
                   .header_param(new_parameter(options['prefer'], key: 'Prefer'))
                   .query_param(new_parameter(options['product_id'], key: 'product_id'))
                   .query_param(new_parameter(options['page_size'], key: 'page_size'))
                   .query_param(new_parameter(options['page'], key: 'page'))
                   .query_param(new_parameter(options['total_required'], key: 'total_required'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(PlanCollection.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Request is not well-formed, syntactically incorrect, or'\
                                  ' violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Shows details for a plan, by ID.
    # @param [String] id Required parameter: The ID of the plan.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_billing_plan(id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/billing/plans/{id}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(id, key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(BillingPlan.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Updates a plan with the `CREATED` or `ACTIVE` status. For an `INACTIVE`
    # plan, you can make only status updates. You can patch these attributes and
    # objects: Attribute or object Operations description replace
    # payment_preferences.auto_bill_outstanding replace taxes.percentage replace
    # payment_preferences.payment_failure_threshold replace
    # payment_preferences.setup_fee replace
    # payment_preferences.setup_fee_failure_action replace name replace
    # @param [String] id Required parameter: The ID of the plan.
    # @param [Array[Patch]] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def patch_billing_plan(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/v1/billing/plans/{id}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Request is not well-formed, syntactically incorrect, or'\
                                  ' violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Activates a plan, by ID.
    # @param [String] id Required parameter: The ID of the plan.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def activate_billing_plan(id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/plans/{id}/activate',
                                     Server::DEFAULT)
                   .template_param(new_parameter(id, key: 'id')
                                    .should_encode(true))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Deactivates a plan, by ID.
    # @param [String] id Required parameter: The ID of the plan.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def deactivate_billing_plan(id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/plans/{id}/deactivate',
                                     Server::DEFAULT)
                   .template_param(new_parameter(id, key: 'id')
                                    .should_encode(true))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Updates pricing for a plan. For example, you can update a regular billing
    # cycle from $5 per month to $7 per month.
    # @param [String] id Required parameter: The ID for the plan.
    # @param [UpdatePricingSchemesRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_billing_plan_pricing_schemes(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/plans/{id}/update-pricing-schemes',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Creates a subscription.
    # @param [String] prefer Optional parameter: The preferred server response
    # upon successful completion of the request. Value is: return=minimal. The
    # server returns a minimal response to optimize communication between the
    # API caller and the server. A minimal response includes the id, status and
    # HATEOAS links. return=representation. The server returns a complete
    # resource representation, including the current state of the resource.
    # @param [String] paypal_request_id Optional parameter: The server stores
    # keys for 72 hours.
    # @param [String] paypal_client_metadata_id Optional parameter: The PayPal
    # Client Metadata Id(CMID) is used to provide device-specific information to
    # PayPal's risk engine. This is crucial for transactions that require
    # device-specific risk assessments. Merchants typically use the Paypal SDK
    # that automatically submits the CMID or they use tools like Fraudnet JS for
    # web or Magnes JS for mobile to generate the CMID on the frontend and then
    # pass it to the API as part of the request headers.
    # @param [CreateSubscriptionRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .header_param(new_parameter(options['prefer'], key: 'Prefer'))
                   .header_param(new_parameter(options['paypal_request_id'], key: 'PayPal-Request-Id'))
                   .header_param(new_parameter(options['paypal_client_metadata_id'], key: 'PayPal-Client-Metadata-Id'))
                   .body_param(new_parameter(options['body']))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Subscription.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # List all subscriptions for merchant account.
    # @param [String] plan_ids Optional parameter: Filters the response by list
    # of plan IDs. Filter supports upto 70 plan IDs. URLs should not exceed a
    # length of 2000 characters.
    # @param [String] statuses Optional parameter: Filters the response by list
    # of subscription statuses.
    # @param [String] created_after Optional parameter: Filters the response by
    # subscription creation start time for a range of subscriptions.
    # @param [String] created_before Optional parameter: Filters the response by
    # subscription creation end time for a range of subscriptions.
    # @param [String] status_updated_before Optional parameter: Filters the
    # response by status update start time for a range of subscriptions.
    # @param [String] status_updated_after Optional parameter: Filters the
    # response by status update end time for a range of subscriptions.
    # @param [String] filter Optional parameter: Filter the response using
    # complex expressions that could use comparison operators like ge, gt, le,
    # lt and logical operators such as 'and' and 'or'.
    # @param [Integer] page_size Optional parameter: The number of items to
    # return in the response.
    # @param [Integer] page Optional parameter: A non-zero integer which is the
    # start index of the entire list of items to return in the response. The
    # combination of `page=1` and `page_size=20` returns the first 20 items. The
    # combination of `page=2` and `page_size=20` returns the next 20 items.
    # @param [Array[String]] customer_ids Optional parameter: Filters the
    # response by comma separated vault customer IDs (FSS subscriptions only).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_subscriptions(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/billing/subscriptions',
                                     Server::DEFAULT)
                   .query_param(new_parameter(options['plan_ids'], key: 'plan_ids'))
                   .query_param(new_parameter(options['statuses'], key: 'statuses'))
                   .query_param(new_parameter(options['created_after'], key: 'created_after'))
                   .query_param(new_parameter(options['created_before'], key: 'created_before'))
                   .query_param(new_parameter(options['status_updated_before'], key: 'status_updated_before'))
                   .query_param(new_parameter(options['status_updated_after'], key: 'status_updated_after'))
                   .query_param(new_parameter(options['filter'], key: 'filter'))
                   .query_param(new_parameter(options['page_size'], key: 'page_size'))
                   .query_param(new_parameter(options['page'], key: 'page'))
                   .query_param(new_parameter(options['customer_ids'], key: 'customer_ids'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SubscriptionCollection.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Request is not well-formed, syntactically incorrect, or'\
                                  ' violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Shows details for a subscription, by ID.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [String] fields Optional parameter: List of fields that are to be
    # returned in the response. Possible value for fields are
    # last_failed_payment and plan.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def get_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/billing/subscriptions/{id}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .query_param(new_parameter(options['fields'], key: 'fields'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Subscription.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Updates a subscription which could be in ACTIVE or SUSPENDED status. You
    # can override plan level default attributes by providing customised values
    # for plan path in the patch request. You cannot update attributes that have
    # already completed (Example - trial cycles can’t be updated if completed).
    # Once overridden, changes to plan resource will not impact subscription.
    # Any price update will not impact billing cycles within next 10 days
    # (Applicable only for subscriptions funded by PayPal account). Following
    # are the fields eligible for patch. Attribute or object Operations
    # billing_info.outstanding_balance replace custom_id add,replace
    # plan.billing_cycles[@sequence==n]. pricing_scheme.fixed_price add,replace
    # plan.billing_cycles[@sequence==n]. pricing_scheme.tiers replace
    # plan.billing_cycles[@sequence==n]. total_cycles replace
    # plan.payment_preferences. auto_bill_outstanding replace
    # plan.payment_preferences. payment_failure_threshold replace
    # plan.taxes.inclusive add,replace plan.taxes.percentage add,replace
    # shipping_amount add,replace start_time replace subscriber.shipping_address
    # add,replace subscriber.payment_source (for subscriptions funded by card
    # payments) replace
    # @param [String] id Required parameter: The ID for the subscription.
    # @param [Array[Patch]] body Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def patch_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::PATCH,
                                     '/v1/billing/subscriptions/{id}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Request is not well-formed, syntactically incorrect, or'\
                                  ' violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Updates the quantity of the product or service in a subscription. You can
    # also use this method to switch the plan and update the `shipping_amount`,
    # `shipping_address` values for the subscription. This type of update
    # requires the buyer's consent.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [ModifySubscriptionRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def revise_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions/{id}/revise',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ModifySubscriptionResponse.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Suspends the subscription.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [SuspendSubscription] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def suspend_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions/{id}/suspend',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Cancels the subscription.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [CancelSubscriptionRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cancel_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions/{id}/cancel',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Activates the subscription.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [ActivateSubscriptionRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def activate_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions/{id}/activate',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(options['body']))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Captures an authorized payment from the subscriber on the subscription.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [String] paypal_request_id Optional parameter: The server stores
    # keys for 72 hours.
    # @param [CaptureSubscriptionRequest] body Optional parameter: TODO: type
    # description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def capture_subscription(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/billing/subscriptions/{id}/capture',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .header_param(new_parameter(options['paypal_request_id'], key: 'PayPal-Request-Id'))
                   .body_param(new_parameter(options['body']))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .is_nullable_response(true)
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(SubscriptionTransactionDetails.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('422',
                                 'The requested action could not be performed, semantically'\
                                  ' incorrect, or failed business validation.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end

    # Lists transactions for a subscription.
    # @param [String] id Required parameter: The ID of the subscription.
    # @param [String] start_time Required parameter: The start time of the range
    # of transactions to list.
    # @param [String] end_time Required parameter: The end time of the range of
    # transactions to list.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_subscription_transactions(options = {})
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/billing/subscriptions/{id}/transactions',
                                     Server::DEFAULT)
                   .template_param(new_parameter(options['id'], key: 'id')
                                    .should_encode(true))
                   .query_param(new_parameter(options['start_time'], key: 'start_time'))
                   .query_param(new_parameter(options['end_time'], key: 'end_time'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('Oauth2')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(TransactionsList.method(:from_hash))
                    .is_api_response(true)
                    .local_error('400',
                                 'Bad Request. Request is not well-formed, syntactically'\
                                  ' incorrect, or violates schema.',
                                 SubscriptionErrorException)
                    .local_error('401',
                                 'Authentication failed due to missing authorization header, or'\
                                  ' invalid authentication credentials.',
                                 SubscriptionErrorException)
                    .local_error('403',
                                 'Authorization failed due to insufficient permissions.',
                                 SubscriptionErrorException)
                    .local_error('404',
                                 'The specified resource does not exist.',
                                 SubscriptionErrorException)
                    .local_error('500',
                                 'An internal server error has occurred.',
                                 SubscriptionErrorException)
                    .local_error('default',
                                 'The error response.',
                                 SubscriptionErrorException))
        .execute
    end
  end
end
