# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v3.0
# ( https://www.apimatic.io ).

module PaypalServerSdk
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
