# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/proveit'
require 'pay_pal_restap_is'
require 'dotenv'

class ControllerTestBase < Minitest::Test
  include PayPalRestapIs
  include CoreLibrary
  Dotenv.load

  # Create configuration and set any test parameters
  def create_configuration
    Configuration.new(environment: Environment::SANDBOX,
                      client_credentials_auth_credentials: ClientCredentialsAuthCredentials.new(
                        o_auth_client_id: ENV['CLIENT_ID'],
                        o_auth_client_secret: ENV['CLIENT_SECRET']
                      )
    )
  end

  # Initializes the base test controller
  def setup_class
    _config = create_configuration
    @client = Client.new(config: _config)
  end
end
